// GENERATED BY dartway generate. DO NOT EDIT.
part of 'people.dart';

mixin _$UserProfileRow on DwTableRow {
  UserProfileRow get _self => this as UserProfileRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfileRow &&
          other.id == _self.id &&
          other.accountId == _self.accountId &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.gender == _self.gender &&
          other.avatarFileId == _self.avatarFileId &&
          other.role == _self.role &&
          other.agreedForMarketing == _self.agreedForMarketing &&
          other.termsAcceptedAt == _self.termsAcceptedAt &&
          other.testVerificationCode == _self.testVerificationCode &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.accountId,
    _self.firstName,
    _self.lastName,
    _self.gender,
    _self.avatarFileId,
    _self.role,
    _self.agreedForMarketing,
    _self.termsAcceptedAt,
    _self.testVerificationCode,
    _self.createdAt,
  );

  @override
  String toString() =>
      'UserProfileRow(id: ${_self.id}, accountId: ${_self.accountId}, firstName: ${_self.firstName}, lastName: ${_self.lastName}, gender: ${_self.gender}, avatarFileId: ${_self.avatarFileId}, role: ${_self.role}, agreedForMarketing: ${_self.agreedForMarketing}, termsAcceptedAt: ${_self.termsAcceptedAt}, testVerificationCode: ${_self.testVerificationCode}, createdAt: ${_self.createdAt})';
}

extension UserProfileRowCopyWith on UserProfileRow {
  UserProfileRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? accountId,
    String? firstName,
    DwFieldPatch<String> lastName = const DwFieldPatch.keep(),
    DwFieldPatch<UserGender> gender = const DwFieldPatch.keep(),
    DwFieldPatch<int> avatarFileId = const DwFieldPatch.keep(),
    UserRole? role,
    bool? agreedForMarketing,
    DwFieldPatch<DateTime> termsAcceptedAt = const DwFieldPatch.keep(),
    DwFieldPatch<String> testVerificationCode = const DwFieldPatch.keep(),
    DateTime? createdAt,
  }) => UserProfileRow(
    id: id.apply(this.id),
    accountId: accountId ?? this.accountId,
    firstName: firstName ?? this.firstName,
    lastName: lastName.apply(this.lastName),
    gender: gender.apply(this.gender),
    avatarFileId: avatarFileId.apply(this.avatarFileId),
    role: role ?? this.role,
    agreedForMarketing: agreedForMarketing ?? this.agreedForMarketing,
    termsAcceptedAt: termsAcceptedAt.apply(this.termsAcceptedAt),
    testVerificationCode: testVerificationCode.apply(this.testVerificationCode),
    createdAt: createdAt ?? this.createdAt,
  );
}

final class UserProfileTable extends DwTableDef<UserProfileRow> {
  const UserProfileTable() : super('user_profile');

  DwTableColumn<int> get accountId => const DwTableColumn(
    'account_id',
    DwColumnType.bigint,
    unique: true,
    references: DwForeignKey('dw_account', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<String> get firstName =>
      const DwTableColumn('first_name', DwColumnType.text);

  DwTableColumn<String?> get lastName =>
      const DwTableColumn('last_name', DwColumnType.text);

  DwTableColumn<UserGender?> get gender =>
      const DwTableColumn('gender', DwEnumType(UserGender.values));

  DwTableColumn<int?> get avatarFileId => const DwTableColumn(
    'avatar_file_id',
    DwColumnType.bigint,
    references: DwForeignKey('dw_stored_file', onDelete: DwOnDelete.setNull),
  );

  DwTableColumn<UserRole> get role =>
      const DwTableColumn('role', DwEnumType(UserRole.values));

  DwTableColumn<bool> get agreedForMarketing =>
      const DwTableColumn('agreed_for_marketing', DwColumnType.boolean);

  DwTableColumn<DateTime?> get termsAcceptedAt =>
      const DwTableColumn('terms_accepted_at', DwColumnType.timestamptz);

  DwTableColumn<String?> get testVerificationCode =>
      const DwTableColumn('test_verification_code', DwColumnType.text);

  DwTableColumn<DateTime> get createdAt =>
      const DwTableColumn('created_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    accountId,
    firstName,
    lastName,
    gender,
    avatarFileId,
    role,
    agreedForMarketing,
    termsAcceptedAt,
    testVerificationCode,
    createdAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('user_profile_created_at_idx', ['created_at']),
  ];

  @override
  UserProfileRow fromRow(DwResultRow row) => UserProfileRow(
    id: row.decode(id),
    accountId: row.decode(accountId),
    firstName: row.decode(firstName),
    lastName: row.decode(lastName),
    gender: row.decode(gender),
    avatarFileId: row.decode(avatarFileId),
    role: row.decode(role),
    agreedForMarketing: row.decode(agreedForMarketing),
    termsAcceptedAt: row.decode(termsAcceptedAt),
    testVerificationCode: row.decode(testVerificationCode),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(UserProfileRow row) => {
    if (row.id != null) 'id': row.id,
    'account_id': row.accountId,
    'first_name': row.firstName,
    'last_name': row.lastName,
    'gender': row.gender,
    'avatar_file_id': row.avatarFileId,
    'role': row.role,
    'agreed_for_marketing': row.agreedForMarketing,
    'terms_accepted_at': row.termsAcceptedAt,
    'test_verification_code': row.testVerificationCode,
    'created_at': row.createdAt,
  };
}
