// GENERATED BY dartway generate. DO NOT EDIT.
part of 'settings.dart';

mixin _$AppSettingRow on DwTableRow {
  AppSettingRow get _self => this as AppSettingRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettingRow &&
          other.id == _self.id &&
          other.key == _self.key &&
          other.value == _self.value;

  @override
  int get hashCode => Object.hash(_self.id, _self.key, _self.value);

  @override
  String toString() =>
      'AppSettingRow(id: ${_self.id}, key: ${_self.key}, value: ${_self.value})';
}

extension AppSettingRowCopyWith on AppSettingRow {
  AppSettingRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    String? key,
    String? value,
  }) => AppSettingRow(
    id: id.apply(this.id),
    key: key ?? this.key,
    value: value ?? this.value,
  );
}

final class AppSettingTable extends DwTableDef<AppSettingRow> {
  const AppSettingTable() : super('app_setting');

  DwTableColumn<String> get key =>
      const DwTableColumn('key', DwColumnType.text, unique: true);

  DwTableColumn<String> get value =>
      const DwTableColumn('value', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [id, key, value];

  @override
  AppSettingRow fromRow(DwResultRow row) => AppSettingRow(
    id: row.decode(id),
    key: row.decode(key),
    value: row.decode(value),
  );

  @override
  Map<String, Object?> toRow(AppSettingRow row) => {
    if (row.id != null) 'id': row.id,
    'key': row.key,
    'value': row.value,
  };
}
