// GENERATED BY dartway generate. DO NOT EDIT.
part of 'app_setting.dart';

mixin _$AppSettingRow on DwTableRow {
  AppSettingRow get _self => this as AppSettingRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettingRow &&
          other.id == _self.id &&
          other.key == _self.key &&
          other.value == _self.value &&
          dwMapEquals(other.limits, _self.limits) &&
          other.featuredServiceId == _self.featuredServiceId &&
          other.updatedAt == _self.updatedAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.key,
    _self.value,
    Object.hashAllUnordered(
      _self.limits.entries.map((e) => Object.hash(e.key, e.value)),
    ),
    _self.featuredServiceId,
    _self.updatedAt,
  );

  @override
  String toString() =>
      'AppSettingRow(id: ${_self.id}, key: ${_self.key}, value: ${_self.value}, limits: ${_self.limits}, featuredServiceId: ${_self.featuredServiceId}, updatedAt: ${_self.updatedAt})';
}

extension AppSettingRowCopyWith on AppSettingRow {
  AppSettingRow copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    String? key,
    String? value,
    Map<String, int>? limits,
    DwPatch<int> featuredServiceId = const DwPatch.keep(),
    DateTime? updatedAt,
  }) => AppSettingRow(
    id: id.apply(this.id),
    key: key ?? this.key,
    value: value ?? this.value,
    limits: limits ?? this.limits,
    featuredServiceId: featuredServiceId.apply(this.featuredServiceId),
    updatedAt: updatedAt ?? this.updatedAt,
  );
}

final class AppSettingTable extends DwTableDef<AppSettingRow> {
  const AppSettingTable() : super('app_setting');

  DwColumn<String> get key => const DwColumn('key', DwType.text, unique: true);

  DwColumn<String> get value => const DwColumn('value', DwType.text);

  DwColumn<Map<String, int>> get limits =>
      const DwColumn('limits', DwJsonMapType<int>());

  DwColumn<int?> get featuredServiceId => const DwColumn(
    'featured_service_id',
    DwType.bigint,
    unique: true,
    references: DwReferences('club_service', onDelete: DwOnDelete.setNull),
  );

  DwColumn<DateTime> get updatedAt => const DwColumn(
    'updated_at',
    DwType.timestamptz,
    defaultValue: DwDefault.now(),
  );

  @override
  List<DwColumn<Object?>> get columns => [
    id,
    key,
    value,
    limits,
    featuredServiceId,
    updatedAt,
  ];

  @override
  AppSettingRow fromRow(DwResultRow row) => AppSettingRow(
    id: row.decode(id),
    key: row.decode(key),
    value: row.decode(value),
    limits: row.decode(limits),
    featuredServiceId: row.decode(featuredServiceId),
    updatedAt: row.decode(updatedAt),
  );

  @override
  Map<String, Object?> toRow(AppSettingRow row) => {
    if (row.id != null) 'id': row.id,
    'key': row.key,
    'value': row.value,
    'limits': row.limits,
    'featured_service_id': row.featuredServiceId,
    'updated_at': row.updatedAt,
  };
}
