// GENERATED BY dartway generate. DO NOT EDIT.
part of 'club_service.dart';

mixin _$ClubServiceRow on DwTableRow {
  ClubServiceRow get _self => this as ClubServiceRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubServiceRow &&
          other.id == _self.id &&
          other.title == _self.title &&
          other.kind == _self.kind &&
          other.price == _self.price &&
          other.duration == _self.duration &&
          dwListEquals(other.tags, _self.tags) &&
          other.createdAt == _self.createdAt &&
          other.archivedAt == _self.archivedAt &&
          dwListEquals(other.cover, _self.cover) &&
          other.active == _self.active;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.title,
    _self.kind,
    _self.price,
    _self.duration,
    Object.hashAll(_self.tags),
    _self.createdAt,
    _self.archivedAt,
    _self.cover == null ? null : Object.hashAll(_self.cover!),
    _self.active,
  );

  @override
  String toString() =>
      'ClubServiceRow(id: ${_self.id}, title: ${_self.title}, kind: ${_self.kind}, price: ${_self.price}, duration: ${_self.duration}, tags: ${_self.tags}, createdAt: ${_self.createdAt}, archivedAt: ${_self.archivedAt}, cover: ${_self.cover}, active: ${_self.active})';
}

extension ClubServiceRowCopyWith on ClubServiceRow {
  ClubServiceRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    String? title,
    ClubServiceKind? kind,
    DwFieldPatch<double> price = const DwFieldPatch.keep(),
    Duration? duration,
    List<String>? tags,
    DateTime? createdAt,
    DwFieldPatch<DateTime> archivedAt = const DwFieldPatch.keep(),
    DwFieldPatch<Uint8List> cover = const DwFieldPatch.keep(),
    bool? active,
  }) => ClubServiceRow(
    id: id.apply(this.id),
    title: title ?? this.title,
    kind: kind ?? this.kind,
    price: price.apply(this.price),
    duration: duration ?? this.duration,
    tags: tags ?? this.tags,
    createdAt: createdAt ?? this.createdAt,
    archivedAt: archivedAt.apply(this.archivedAt),
    cover: cover.apply(this.cover),
    active: active ?? this.active,
  );
}

final class ClubServiceTable extends DwTableDef<ClubServiceRow> {
  const ClubServiceTable() : super('club_service');

  DwTableColumn<String> get title =>
      const DwTableColumn('title', DwColumnType.text);

  DwTableColumn<ClubServiceKind> get kind =>
      const DwTableColumn('kind', DwEnumType(ClubServiceKind.values));

  DwTableColumn<double?> get price =>
      const DwTableColumn('price', DwColumnType.doublePrecision);

  DwTableColumn<Duration> get duration =>
      const DwTableColumn('duration', DwColumnType.duration);

  DwTableColumn<List<String>> get tags =>
      const DwTableColumn('tags', DwJsonListType<String>());

  DwTableColumn<DateTime> get createdAt => const DwTableColumn(
    'created_at',
    DwColumnType.timestamptz,
    defaultValue: DwDefaultValue.now(),
  );

  DwTableColumn<DateTime?> get archivedAt =>
      const DwTableColumn('archived_at', DwColumnType.timestamptz);

  DwTableColumn<Uint8List?> get cover =>
      const DwTableColumn('cover', DwColumnType.bytea);

  DwTableColumn<bool> get active => const DwTableColumn(
    'active',
    DwColumnType.boolean,
    defaultValue: DwDefaultValue('true'),
  );

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    title,
    kind,
    price,
    duration,
    tags,
    createdAt,
    archivedAt,
    cover,
    active,
  ];

  @override
  ClubServiceRow fromRow(DwResultRow row) => ClubServiceRow(
    id: row.decode(id),
    title: row.decode(title),
    kind: row.decode(kind),
    price: row.decode(price),
    duration: row.decode(duration),
    tags: row.decode(tags),
    createdAt: row.decode(createdAt),
    archivedAt: row.decode(archivedAt),
    cover: row.decode(cover),
    active: row.decode(active),
  );

  @override
  Map<String, Object?> toRow(ClubServiceRow row) => {
    if (row.id != null) 'id': row.id,
    'title': row.title,
    'kind': row.kind,
    'price': row.price,
    'duration': row.duration,
    'tags': row.tags,
    'created_at': row.createdAt,
    'archived_at': row.archivedAt,
    'cover': row.cover,
    'active': row.active,
  };
}
