// GENERATED BY dartway generate. DO NOT EDIT.
part of 'club_session.dart';

mixin _$ClubSessionRow on DwTableRow {
  ClubSessionRow get _self => this as ClubSessionRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubSessionRow &&
          other.id == _self.id &&
          other.serviceId == _self.serviceId &&
          other.previousSessionId == _self.previousSessionId &&
          other.startsAt == _self.startsAt &&
          other.capacity == _self.capacity &&
          other.note == _self.note &&
          dwListEquals(other.labels, _self.labels);

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.serviceId,
    _self.previousSessionId,
    _self.startsAt,
    _self.capacity,
    _self.note,
    _self.labels == null ? null : Object.hashAll(_self.labels!),
  );

  @override
  String toString() =>
      'ClubSessionRow(id: ${_self.id}, serviceId: ${_self.serviceId}, previousSessionId: ${_self.previousSessionId}, startsAt: ${_self.startsAt}, capacity: ${_self.capacity}, note: ${_self.note}, labels: ${_self.labels})';
}

extension ClubSessionRowCopyWith on ClubSessionRow {
  ClubSessionRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? serviceId,
    DwFieldPatch<int> previousSessionId = const DwFieldPatch.keep(),
    DateTime? startsAt,
    int? capacity,
    DwFieldPatch<String> note = const DwFieldPatch.keep(),
    DwFieldPatch<List<String>> labels = const DwFieldPatch.keep(),
  }) => ClubSessionRow(
    id: id.apply(this.id),
    serviceId: serviceId ?? this.serviceId,
    previousSessionId: previousSessionId.apply(this.previousSessionId),
    startsAt: startsAt ?? this.startsAt,
    capacity: capacity ?? this.capacity,
    note: note.apply(this.note),
    labels: labels.apply(this.labels),
  );
}

final class ClubSessionTable extends DwTableDef<ClubSessionRow> {
  const ClubSessionTable() : super('club_session');

  DwTableColumn<int> get serviceId => const DwTableColumn(
    'service_id',
    DwColumnType.bigint,
    references: DwForeignKey('club_service', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int?> get previousSessionId => const DwTableColumn(
    'previous_session_id',
    DwColumnType.bigint,
    references: DwForeignKey('club_session', onDelete: DwOnDelete.setNull),
  );

  DwTableColumn<DateTime> get startsAt =>
      const DwTableColumn('starts_at', DwColumnType.timestamptz);

  DwTableColumn<int> get capacity =>
      const DwTableColumn('capacity', DwColumnType.bigint);

  DwTableColumn<String?> get note =>
      const DwTableColumn('note_text', DwColumnType.text);

  DwTableColumn<List<String>?> get labels =>
      const DwTableColumn('labels', DwJsonListType<String>());

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    serviceId,
    previousSessionId,
    startsAt,
    capacity,
    note,
    labels,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('club_session_service_id_starts_at_key', [
      'service_id',
      'starts_at',
    ], unique: true),
    DwIndexSchema('club_session_starts_at_idx', ['starts_at']),
  ];

  @override
  ClubSessionRow fromRow(DwResultRow row) => ClubSessionRow(
    id: row.decode(id),
    serviceId: row.decode(serviceId),
    previousSessionId: row.decode(previousSessionId),
    startsAt: row.decode(startsAt),
    capacity: row.decode(capacity),
    note: row.decode(note),
    labels: row.decode(labels),
  );

  @override
  Map<String, Object?> toRow(ClubSessionRow row) => {
    if (row.id != null) 'id': row.id,
    'service_id': row.serviceId,
    'previous_session_id': row.previousSessionId,
    'starts_at': row.startsAt,
    'capacity': row.capacity,
    'note_text': row.note,
    'labels': row.labels,
  };
}
