// GENERATED BY dartway generate. DO NOT EDIT.
part of 'club_service.dart';

mixin _$ClubService on DwEntity {
  ClubService get _self => this as ClubService;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubService &&
          other.id == _self.id &&
          other.title == _self.title &&
          other.kind == _self.kind &&
          other.price == _self.price &&
          other.duration == _self.duration &&
          dwListEquals(other.tags, _self.tags) &&
          other.createdAt == _self.createdAt &&
          other.archivedAt == _self.archivedAt &&
          dwListEquals(other.cover, _self.cover) &&
          other.active == _self.active;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.title,
    _self.kind,
    _self.price,
    _self.duration,
    Object.hashAll(_self.tags),
    _self.createdAt,
    _self.archivedAt,
    _self.cover == null ? null : Object.hashAll(_self.cover!),
    _self.active,
  );

  @override
  String toString() =>
      'ClubService(id: ${_self.id}, title: ${_self.title}, kind: ${_self.kind}, price: ${_self.price}, duration: ${_self.duration}, tags: ${_self.tags}, createdAt: ${_self.createdAt}, archivedAt: ${_self.archivedAt}, cover: ${_self.cover}, active: ${_self.active})';
}

extension ClubServiceCopyWith on ClubService {
  ClubService copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    String? title,
    ClubServiceKind? kind,
    DwPatch<double> price = const DwPatch.keep(),
    Duration? duration,
    List<String>? tags,
    DateTime? createdAt,
    DwPatch<DateTime> archivedAt = const DwPatch.keep(),
    DwPatch<Uint8List> cover = const DwPatch.keep(),
    bool? active,
  }) => ClubService(
    id: id.apply(this.id),
    title: title ?? this.title,
    kind: kind ?? this.kind,
    price: price.apply(this.price),
    duration: duration ?? this.duration,
    tags: tags ?? this.tags,
    createdAt: createdAt ?? this.createdAt,
    archivedAt: archivedAt.apply(this.archivedAt),
    cover: cover.apply(this.cover),
    active: active ?? this.active,
  );
}

final class ClubServiceTable extends DwTableDef<ClubService> {
  const ClubServiceTable() : super('club_service');

  DwColumn<String> get title => const DwColumn('title', DwType.text);

  DwColumn<ClubServiceKind> get kind =>
      const DwColumn('kind', DwEnumType(ClubServiceKind.values));

  DwColumn<double?> get price =>
      const DwColumn('price', DwType.doublePrecision);

  DwColumn<Duration> get duration =>
      const DwColumn('duration', DwType.duration);

  DwColumn<List<String>> get tags =>
      const DwColumn('tags', DwJsonListType<String>());

  DwColumn<DateTime> get createdAt => const DwColumn(
    'created_at',
    DwType.timestamptz,
    defaultValue: DwDefault.now(),
  );

  DwColumn<DateTime?> get archivedAt =>
      const DwColumn('archived_at', DwType.timestamptz);

  DwColumn<Uint8List?> get cover => const DwColumn('cover', DwType.bytea);

  DwColumn<bool> get active =>
      const DwColumn('active', DwType.boolean, defaultValue: DwDefault('true'));

  @override
  List<DwColumn<Object?>> get columns => [
    id,
    title,
    kind,
    price,
    duration,
    tags,
    createdAt,
    archivedAt,
    cover,
    active,
  ];

  @override
  ClubService fromRow(DwRow row) => ClubService(
    id: row.decode(id),
    title: row.decode(title),
    kind: row.decode(kind),
    price: row.decode(price),
    duration: row.decode(duration),
    tags: row.decode(tags),
    createdAt: row.decode(createdAt),
    archivedAt: row.decode(archivedAt),
    cover: row.decode(cover),
    active: row.decode(active),
  );

  @override
  Map<String, Object?> toRow(ClubService entity) => {
    if (entity.id != null) 'id': entity.id,
    'title': entity.title,
    'kind': entity.kind,
    'price': entity.price,
    'duration': entity.duration,
    'tags': entity.tags,
    'created_at': entity.createdAt,
    'archived_at': entity.archivedAt,
    'cover': entity.cover,
    'active': entity.active,
  };
}
