// GENERATED BY dartway generate. DO NOT EDIT.
part of 'chat.dart';

mixin _$ChatChannelRow on DwTableRow {
  ChatChannelRow get _self => this as ChatChannelRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChannelRow &&
          other.id == _self.id &&
          other.title == _self.title;

  @override
  int get hashCode => Object.hash(_self.id, _self.title);

  @override
  String toString() => 'ChatChannelRow(id: ${_self.id}, title: ${_self.title})';
}

extension ChatChannelRowCopyWith on ChatChannelRow {
  ChatChannelRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    String? title,
  }) => ChatChannelRow(id: id.apply(this.id), title: title ?? this.title);
}

final class ChatChannelTable extends DwTableDef<ChatChannelRow> {
  const ChatChannelTable() : super('chat_channel');

  DwTableColumn<String> get title =>
      const DwTableColumn('title', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [id, title];

  @override
  ChatChannelRow fromRow(DwResultRow row) =>
      ChatChannelRow(id: row.decode(id), title: row.decode(title));

  @override
  Map<String, Object?> toRow(ChatChannelRow row) => {
    if (row.id != null) 'id': row.id,
    'title': row.title,
  };
}

mixin _$ChatMessageRow on DwTableRow {
  ChatMessageRow get _self => this as ChatMessageRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageRow &&
          other.id == _self.id &&
          other.channelId == _self.channelId &&
          other.authorProfileId == _self.authorProfileId &&
          other.text == _self.text &&
          other.sentAt == _self.sentAt &&
          other.editedAt == _self.editedAt &&
          other.pinnedAt == _self.pinnedAt &&
          other.pinnedByProfileId == _self.pinnedByProfileId &&
          other.replyToMessageId == _self.replyToMessageId &&
          other.deletedAt == _self.deletedAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.channelId,
    _self.authorProfileId,
    _self.text,
    _self.sentAt,
    _self.editedAt,
    _self.pinnedAt,
    _self.pinnedByProfileId,
    _self.replyToMessageId,
    _self.deletedAt,
  );

  @override
  String toString() =>
      'ChatMessageRow(id: ${_self.id}, channelId: ${_self.channelId}, authorProfileId: ${_self.authorProfileId}, text: ${_self.text}, sentAt: ${_self.sentAt}, editedAt: ${_self.editedAt}, pinnedAt: ${_self.pinnedAt}, pinnedByProfileId: ${_self.pinnedByProfileId}, replyToMessageId: ${_self.replyToMessageId}, deletedAt: ${_self.deletedAt})';
}

extension ChatMessageRowCopyWith on ChatMessageRow {
  ChatMessageRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? channelId,
    int? authorProfileId,
    String? text,
    DateTime? sentAt,
    DwFieldPatch<DateTime> editedAt = const DwFieldPatch.keep(),
    DwFieldPatch<DateTime> pinnedAt = const DwFieldPatch.keep(),
    DwFieldPatch<int> pinnedByProfileId = const DwFieldPatch.keep(),
    DwFieldPatch<int> replyToMessageId = const DwFieldPatch.keep(),
    DwFieldPatch<DateTime> deletedAt = const DwFieldPatch.keep(),
  }) => ChatMessageRow(
    id: id.apply(this.id),
    channelId: channelId ?? this.channelId,
    authorProfileId: authorProfileId ?? this.authorProfileId,
    text: text ?? this.text,
    sentAt: sentAt ?? this.sentAt,
    editedAt: editedAt.apply(this.editedAt),
    pinnedAt: pinnedAt.apply(this.pinnedAt),
    pinnedByProfileId: pinnedByProfileId.apply(this.pinnedByProfileId),
    replyToMessageId: replyToMessageId.apply(this.replyToMessageId),
    deletedAt: deletedAt.apply(this.deletedAt),
  );
}

final class ChatMessageTable extends DwTableDef<ChatMessageRow> {
  const ChatMessageTable() : super('chat_message');

  DwTableColumn<int> get channelId => const DwTableColumn(
    'channel_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_channel', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get authorProfileId => const DwTableColumn(
    'author_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<String> get text =>
      const DwTableColumn('text', DwColumnType.text);

  DwTableColumn<DateTime> get sentAt =>
      const DwTableColumn('sent_at', DwColumnType.timestamptz);

  DwTableColumn<DateTime?> get editedAt =>
      const DwTableColumn('edited_at', DwColumnType.timestamptz);

  DwTableColumn<DateTime?> get pinnedAt =>
      const DwTableColumn('pinned_at', DwColumnType.timestamptz);

  DwTableColumn<int?> get pinnedByProfileId => const DwTableColumn(
    'pinned_by_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.setNull),
  );

  DwTableColumn<int?> get replyToMessageId => const DwTableColumn(
    'reply_to_message_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_message', onDelete: DwOnDelete.setNull),
  );

  DwTableColumn<DateTime?> get deletedAt =>
      const DwTableColumn('deleted_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    channelId,
    authorProfileId,
    text,
    sentAt,
    editedAt,
    pinnedAt,
    pinnedByProfileId,
    replyToMessageId,
    deletedAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('chat_message_channel_id_sent_at_id_idx', [
      'channel_id',
      'sent_at',
      'id',
    ]),
  ];

  @override
  ChatMessageRow fromRow(DwResultRow row) => ChatMessageRow(
    id: row.decode(id),
    channelId: row.decode(channelId),
    authorProfileId: row.decode(authorProfileId),
    text: row.decode(text),
    sentAt: row.decode(sentAt),
    editedAt: row.decode(editedAt),
    pinnedAt: row.decode(pinnedAt),
    pinnedByProfileId: row.decode(pinnedByProfileId),
    replyToMessageId: row.decode(replyToMessageId),
    deletedAt: row.decode(deletedAt),
  );

  @override
  Map<String, Object?> toRow(ChatMessageRow row) => {
    if (row.id != null) 'id': row.id,
    'channel_id': row.channelId,
    'author_profile_id': row.authorProfileId,
    'text': row.text,
    'sent_at': row.sentAt,
    'edited_at': row.editedAt,
    'pinned_at': row.pinnedAt,
    'pinned_by_profile_id': row.pinnedByProfileId,
    'reply_to_message_id': row.replyToMessageId,
    'deleted_at': row.deletedAt,
  };
}

mixin _$ChatMessageAttachmentRow on DwTableRow {
  ChatMessageAttachmentRow get _self => this as ChatMessageAttachmentRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageAttachmentRow &&
          other.id == _self.id &&
          other.messageId == _self.messageId &&
          other.fileId == _self.fileId &&
          other.position == _self.position &&
          other.width == _self.width &&
          other.height == _self.height;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.messageId,
    _self.fileId,
    _self.position,
    _self.width,
    _self.height,
  );

  @override
  String toString() =>
      'ChatMessageAttachmentRow(id: ${_self.id}, messageId: ${_self.messageId}, fileId: ${_self.fileId}, position: ${_self.position}, width: ${_self.width}, height: ${_self.height})';
}

extension ChatMessageAttachmentRowCopyWith on ChatMessageAttachmentRow {
  ChatMessageAttachmentRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? messageId,
    int? fileId,
    int? position,
    DwFieldPatch<int> width = const DwFieldPatch.keep(),
    DwFieldPatch<int> height = const DwFieldPatch.keep(),
  }) => ChatMessageAttachmentRow(
    id: id.apply(this.id),
    messageId: messageId ?? this.messageId,
    fileId: fileId ?? this.fileId,
    position: position ?? this.position,
    width: width.apply(this.width),
    height: height.apply(this.height),
  );
}

final class ChatMessageAttachmentTable
    extends DwTableDef<ChatMessageAttachmentRow> {
  const ChatMessageAttachmentTable() : super('chat_message_attachment');

  DwTableColumn<int> get messageId => const DwTableColumn(
    'message_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_message', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get fileId => const DwTableColumn(
    'file_id',
    DwColumnType.bigint,
    unique: true,
    references: DwForeignKey('dw_stored_file', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get position =>
      const DwTableColumn('position', DwColumnType.bigint);

  DwTableColumn<int?> get width =>
      const DwTableColumn('width', DwColumnType.bigint);

  DwTableColumn<int?> get height =>
      const DwTableColumn('height', DwColumnType.bigint);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    messageId,
    fileId,
    position,
    width,
    height,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('chat_message_attachment_message_id_position_idx', [
      'message_id',
      'position',
    ]),
  ];

  @override
  ChatMessageAttachmentRow fromRow(DwResultRow row) => ChatMessageAttachmentRow(
    id: row.decode(id),
    messageId: row.decode(messageId),
    fileId: row.decode(fileId),
    position: row.decode(position),
    width: row.decode(width),
    height: row.decode(height),
  );

  @override
  Map<String, Object?> toRow(ChatMessageAttachmentRow row) => {
    if (row.id != null) 'id': row.id,
    'message_id': row.messageId,
    'file_id': row.fileId,
    'position': row.position,
    'width': row.width,
    'height': row.height,
  };
}

mixin _$ChatMessageReactionRow on DwTableRow {
  ChatMessageReactionRow get _self => this as ChatMessageReactionRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageReactionRow &&
          other.id == _self.id &&
          other.messageId == _self.messageId &&
          other.profileId == _self.profileId &&
          other.reaction == _self.reaction;

  @override
  int get hashCode =>
      Object.hash(_self.id, _self.messageId, _self.profileId, _self.reaction);

  @override
  String toString() =>
      'ChatMessageReactionRow(id: ${_self.id}, messageId: ${_self.messageId}, profileId: ${_self.profileId}, reaction: ${_self.reaction})';
}

extension ChatMessageReactionRowCopyWith on ChatMessageReactionRow {
  ChatMessageReactionRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? messageId,
    int? profileId,
    ChatReaction? reaction,
  }) => ChatMessageReactionRow(
    id: id.apply(this.id),
    messageId: messageId ?? this.messageId,
    profileId: profileId ?? this.profileId,
    reaction: reaction ?? this.reaction,
  );
}

final class ChatMessageReactionTable
    extends DwTableDef<ChatMessageReactionRow> {
  const ChatMessageReactionTable() : super('chat_message_reaction');

  DwTableColumn<int> get messageId => const DwTableColumn(
    'message_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_message', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get profileId => const DwTableColumn(
    'profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<ChatReaction> get reaction =>
      const DwTableColumn('reaction', DwEnumType(ChatReaction.values));

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    messageId,
    profileId,
    reaction,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('chat_message_reaction_message_id_profile_id_key', [
      'message_id',
      'profile_id',
    ], unique: true),
  ];

  @override
  ChatMessageReactionRow fromRow(DwResultRow row) => ChatMessageReactionRow(
    id: row.decode(id),
    messageId: row.decode(messageId),
    profileId: row.decode(profileId),
    reaction: row.decode(reaction),
  );

  @override
  Map<String, Object?> toRow(ChatMessageReactionRow row) => {
    if (row.id != null) 'id': row.id,
    'message_id': row.messageId,
    'profile_id': row.profileId,
    'reaction': row.reaction,
  };
}

mixin _$ChatReadPositionRow on DwTableRow {
  ChatReadPositionRow get _self => this as ChatReadPositionRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatReadPositionRow &&
          other.id == _self.id &&
          other.profileId == _self.profileId &&
          other.channelId == _self.channelId &&
          other.messageId == _self.messageId &&
          other.sentAt == _self.sentAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.profileId,
    _self.channelId,
    _self.messageId,
    _self.sentAt,
  );

  @override
  String toString() =>
      'ChatReadPositionRow(id: ${_self.id}, profileId: ${_self.profileId}, channelId: ${_self.channelId}, messageId: ${_self.messageId}, sentAt: ${_self.sentAt})';
}

extension ChatReadPositionRowCopyWith on ChatReadPositionRow {
  ChatReadPositionRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? profileId,
    int? channelId,
    int? messageId,
    DateTime? sentAt,
  }) => ChatReadPositionRow(
    id: id.apply(this.id),
    profileId: profileId ?? this.profileId,
    channelId: channelId ?? this.channelId,
    messageId: messageId ?? this.messageId,
    sentAt: sentAt ?? this.sentAt,
  );
}

final class ChatReadPositionTable extends DwTableDef<ChatReadPositionRow> {
  const ChatReadPositionTable() : super('chat_read_position');

  DwTableColumn<int> get profileId => const DwTableColumn(
    'profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get channelId => const DwTableColumn(
    'channel_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_channel', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get messageId => const DwTableColumn(
    'message_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_message', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<DateTime> get sentAt =>
      const DwTableColumn('sent_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    profileId,
    channelId,
    messageId,
    sentAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('chat_read_position_profile_id_channel_id_key', [
      'profile_id',
      'channel_id',
    ], unique: true),
  ];

  @override
  ChatReadPositionRow fromRow(DwResultRow row) => ChatReadPositionRow(
    id: row.decode(id),
    profileId: row.decode(profileId),
    channelId: row.decode(channelId),
    messageId: row.decode(messageId),
    sentAt: row.decode(sentAt),
  );

  @override
  Map<String, Object?> toRow(ChatReadPositionRow row) => {
    if (row.id != null) 'id': row.id,
    'profile_id': row.profileId,
    'channel_id': row.channelId,
    'message_id': row.messageId,
    'sent_at': row.sentAt,
  };
}
