// GENERATED BY dartway generate. DO NOT EDIT.
part of 'club.dart';

mixin _$ClubService on DwEntity {
  ClubService get _self => this as ClubService;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubService &&
          other.id == _self.id &&
          other.title == _self.title &&
          other.description == _self.description &&
          other.durationMinutes == _self.durationMinutes &&
          other.price == _self.price &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.title,
    _self.description,
    _self.durationMinutes,
    _self.price,
    _self.imageUrl,
  );

  @override
  String toString() =>
      'ClubService(id: ${_self.id}, title: ${_self.title}, description: ${_self.description}, durationMinutes: ${_self.durationMinutes}, price: ${_self.price}, imageUrl: ${_self.imageUrl})';
}

extension ClubServiceCopyWith on ClubService {
  ClubService copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    String? title,
    String? description,
    int? durationMinutes,
    int? price,
    DwPatch<String> imageUrl = const DwPatch.keep(),
  }) => ClubService(
    id: id.apply(this.id),
    title: title ?? this.title,
    description: description ?? this.description,
    durationMinutes: durationMinutes ?? this.durationMinutes,
    price: price ?? this.price,
    imageUrl: imageUrl.apply(this.imageUrl),
  );
}

final class ClubServiceTable extends DwTableDef<ClubService> {
  const ClubServiceTable() : super('club_service');

  DwColumn<String> get title => const DwColumn('title', DwType.text);

  DwColumn<String> get description =>
      const DwColumn('description', DwType.text);

  DwColumn<int> get durationMinutes =>
      const DwColumn('duration_minutes', DwType.bigint);

  DwColumn<int> get price => const DwColumn('price', DwType.bigint);

  DwColumn<String?> get imageUrl => const DwColumn('image_url', DwType.text);

  @override
  List<DwColumn<Object?>> get columns => [
    id,
    title,
    description,
    durationMinutes,
    price,
    imageUrl,
  ];

  @override
  ClubService fromRow(DwRow row) => ClubService(
    id: row.decode(id),
    title: row.decode(title),
    description: row.decode(description),
    durationMinutes: row.decode(durationMinutes),
    price: row.decode(price),
    imageUrl: row.decode(imageUrl),
  );

  @override
  Map<String, Object?> toRow(ClubService entity) => {
    if (entity.id != null) 'id': entity.id,
    'title': entity.title,
    'description': entity.description,
    'duration_minutes': entity.durationMinutes,
    'price': entity.price,
    'image_url': entity.imageUrl,
  };
}

mixin _$ClubSession on DwEntity {
  ClubSession get _self => this as ClubSession;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubSession &&
          other.id == _self.id &&
          other.serviceId == _self.serviceId &&
          other.coachProfileId == _self.coachProfileId &&
          other.startsAt == _self.startsAt &&
          other.capacity == _self.capacity &&
          other.bookedCount == _self.bookedCount;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.serviceId,
    _self.coachProfileId,
    _self.startsAt,
    _self.capacity,
    _self.bookedCount,
  );

  @override
  String toString() =>
      'ClubSession(id: ${_self.id}, serviceId: ${_self.serviceId}, coachProfileId: ${_self.coachProfileId}, startsAt: ${_self.startsAt}, capacity: ${_self.capacity}, bookedCount: ${_self.bookedCount})';
}

extension ClubSessionCopyWith on ClubSession {
  ClubSession copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    int? serviceId,
    DwPatch<int> coachProfileId = const DwPatch.keep(),
    DateTime? startsAt,
    int? capacity,
    int? bookedCount,
  }) => ClubSession(
    id: id.apply(this.id),
    serviceId: serviceId ?? this.serviceId,
    coachProfileId: coachProfileId.apply(this.coachProfileId),
    startsAt: startsAt ?? this.startsAt,
    capacity: capacity ?? this.capacity,
    bookedCount: bookedCount ?? this.bookedCount,
  );
}

final class ClubSessionTable extends DwTableDef<ClubSession> {
  const ClubSessionTable() : super('club_session');

  DwColumn<int> get serviceId => const DwColumn(
    'service_id',
    DwType.bigint,
    references: DwReferences('club_service', onDelete: DwOnDelete.cascade),
  );

  DwColumn<int?> get coachProfileId => const DwColumn(
    'coach_profile_id',
    DwType.bigint,
    references: DwReferences('user_profile', onDelete: DwOnDelete.setNull),
  );

  DwColumn<DateTime> get startsAt =>
      const DwColumn('starts_at', DwType.timestamptz);

  DwColumn<int> get capacity => const DwColumn('capacity', DwType.bigint);

  DwColumn<int> get bookedCount =>
      const DwColumn('booked_count', DwType.bigint);

  @override
  List<DwColumn<Object?>> get columns => [
    id,
    serviceId,
    coachProfileId,
    startsAt,
    capacity,
    bookedCount,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('club_session_starts_at_idx', ['starts_at']),
  ];

  @override
  ClubSession fromRow(DwRow row) => ClubSession(
    id: row.decode(id),
    serviceId: row.decode(serviceId),
    coachProfileId: row.decode(coachProfileId),
    startsAt: row.decode(startsAt),
    capacity: row.decode(capacity),
    bookedCount: row.decode(bookedCount),
  );

  @override
  Map<String, Object?> toRow(ClubSession entity) => {
    if (entity.id != null) 'id': entity.id,
    'service_id': entity.serviceId,
    'coach_profile_id': entity.coachProfileId,
    'starts_at': entity.startsAt,
    'capacity': entity.capacity,
    'booked_count': entity.bookedCount,
  };
}

mixin _$SessionBooking on DwEntity {
  SessionBooking get _self => this as SessionBooking;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionBooking &&
          other.id == _self.id &&
          other.sessionId == _self.sessionId &&
          other.clientProfileId == _self.clientProfileId &&
          other.status == _self.status &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.sessionId,
    _self.clientProfileId,
    _self.status,
    _self.createdAt,
  );

  @override
  String toString() =>
      'SessionBooking(id: ${_self.id}, sessionId: ${_self.sessionId}, clientProfileId: ${_self.clientProfileId}, status: ${_self.status}, createdAt: ${_self.createdAt})';
}

extension SessionBookingCopyWith on SessionBooking {
  SessionBooking copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    int? sessionId,
    int? clientProfileId,
    BookingStatus? status,
    DateTime? createdAt,
  }) => SessionBooking(
    id: id.apply(this.id),
    sessionId: sessionId ?? this.sessionId,
    clientProfileId: clientProfileId ?? this.clientProfileId,
    status: status ?? this.status,
    createdAt: createdAt ?? this.createdAt,
  );
}

final class SessionBookingTable extends DwTableDef<SessionBooking> {
  const SessionBookingTable() : super('session_booking');

  DwColumn<int> get sessionId => const DwColumn(
    'session_id',
    DwType.bigint,
    references: DwReferences('club_session', onDelete: DwOnDelete.cascade),
  );

  DwColumn<int> get clientProfileId => const DwColumn(
    'client_profile_id',
    DwType.bigint,
    references: DwReferences('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwColumn<BookingStatus> get status =>
      const DwColumn('status', DwEnumType(BookingStatus.values));

  DwColumn<DateTime> get createdAt =>
      const DwColumn('created_at', DwType.timestamptz);

  @override
  List<DwColumn<Object?>> get columns => [
    id,
    sessionId,
    clientProfileId,
    status,
    createdAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('session_booking_client_profile_id_created_at_idx', [
      'client_profile_id',
      'created_at',
    ]),
    DwIndexSchema('session_booking_session_id_status_idx', [
      'session_id',
      'status',
    ]),
  ];

  @override
  SessionBooking fromRow(DwRow row) => SessionBooking(
    id: row.decode(id),
    sessionId: row.decode(sessionId),
    clientProfileId: row.decode(clientProfileId),
    status: row.decode(status),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(SessionBooking entity) => {
    if (entity.id != null) 'id': entity.id,
    'session_id': entity.sessionId,
    'client_profile_id': entity.clientProfileId,
    'status': entity.status,
    'created_at': entity.createdAt,
  };
}

mixin _$SessionReview on DwEntity {
  SessionReview get _self => this as SessionReview;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionReview &&
          other.id == _self.id &&
          other.bookingId == _self.bookingId &&
          other.rating == _self.rating &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.bookingId,
    _self.rating,
    _self.text,
    _self.createdAt,
  );

  @override
  String toString() =>
      'SessionReview(id: ${_self.id}, bookingId: ${_self.bookingId}, rating: ${_self.rating}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

extension SessionReviewCopyWith on SessionReview {
  SessionReview copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    int? bookingId,
    int? rating,
    DwPatch<String> text = const DwPatch.keep(),
    DateTime? createdAt,
  }) => SessionReview(
    id: id.apply(this.id),
    bookingId: bookingId ?? this.bookingId,
    rating: rating ?? this.rating,
    text: text.apply(this.text),
    createdAt: createdAt ?? this.createdAt,
  );
}

final class SessionReviewTable extends DwTableDef<SessionReview> {
  const SessionReviewTable() : super('session_review');

  DwColumn<int> get bookingId => const DwColumn(
    'booking_id',
    DwType.bigint,
    unique: true,
    references: DwReferences('session_booking', onDelete: DwOnDelete.cascade),
  );

  DwColumn<int> get rating => const DwColumn('rating', DwType.bigint);

  DwColumn<String?> get text => const DwColumn('text', DwType.text);

  DwColumn<DateTime> get createdAt =>
      const DwColumn('created_at', DwType.timestamptz);

  @override
  List<DwColumn<Object?>> get columns => [
    id,
    bookingId,
    rating,
    text,
    createdAt,
  ];

  @override
  SessionReview fromRow(DwRow row) => SessionReview(
    id: row.decode(id),
    bookingId: row.decode(bookingId),
    rating: row.decode(rating),
    text: row.decode(text),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(SessionReview entity) => {
    if (entity.id != null) 'id': entity.id,
    'booking_id': entity.bookingId,
    'rating': entity.rating,
    'text': entity.text,
    'created_at': entity.createdAt,
  };
}
