// GENERATED BY dartway generate. DO NOT EDIT.
part of 'content.dart';

mixin _$NewsPostRow on DwTableRow {
  NewsPostRow get _self => this as NewsPostRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewsPostRow &&
          other.id == _self.id &&
          other.authorProfileId == _self.authorProfileId &&
          other.title == _self.title &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.authorProfileId,
    _self.title,
    _self.text,
    _self.createdAt,
  );

  @override
  String toString() =>
      'NewsPostRow(id: ${_self.id}, authorProfileId: ${_self.authorProfileId}, title: ${_self.title}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

extension NewsPostRowCopyWith on NewsPostRow {
  NewsPostRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? authorProfileId,
    String? title,
    String? text,
    DateTime? createdAt,
  }) => NewsPostRow(
    id: id.apply(this.id),
    authorProfileId: authorProfileId ?? this.authorProfileId,
    title: title ?? this.title,
    text: text ?? this.text,
    createdAt: createdAt ?? this.createdAt,
  );
}

final class NewsPostTable extends DwTableDef<NewsPostRow> {
  const NewsPostTable() : super('news_post');

  DwTableColumn<int> get authorProfileId => const DwTableColumn(
    'author_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<String> get title =>
      const DwTableColumn('title', DwColumnType.text);

  DwTableColumn<String> get text =>
      const DwTableColumn('text', DwColumnType.text);

  DwTableColumn<DateTime> get createdAt =>
      const DwTableColumn('created_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    authorProfileId,
    title,
    text,
    createdAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('news_post_created_at_idx', ['created_at']),
  ];

  @override
  NewsPostRow fromRow(DwResultRow row) => NewsPostRow(
    id: row.decode(id),
    authorProfileId: row.decode(authorProfileId),
    title: row.decode(title),
    text: row.decode(text),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(NewsPostRow row) => {
    if (row.id != null) 'id': row.id,
    'author_profile_id': row.authorProfileId,
    'title': row.title,
    'text': row.text,
    'created_at': row.createdAt,
  };
}

mixin _$AppSettingRow on DwTableRow {
  AppSettingRow get _self => this as AppSettingRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettingRow &&
          other.id == _self.id &&
          other.key == _self.key &&
          other.value == _self.value;

  @override
  int get hashCode => Object.hash(_self.id, _self.key, _self.value);

  @override
  String toString() =>
      'AppSettingRow(id: ${_self.id}, key: ${_self.key}, value: ${_self.value})';
}

extension AppSettingRowCopyWith on AppSettingRow {
  AppSettingRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    String? key,
    String? value,
  }) => AppSettingRow(
    id: id.apply(this.id),
    key: key ?? this.key,
    value: value ?? this.value,
  );
}

final class AppSettingTable extends DwTableDef<AppSettingRow> {
  const AppSettingTable() : super('app_setting');

  DwTableColumn<String> get key =>
      const DwTableColumn('key', DwColumnType.text, unique: true);

  DwTableColumn<String> get value =>
      const DwTableColumn('value', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [id, key, value];

  @override
  AppSettingRow fromRow(DwResultRow row) => AppSettingRow(
    id: row.decode(id),
    key: row.decode(key),
    value: row.decode(value),
  );

  @override
  Map<String, Object?> toRow(AppSettingRow row) => {
    if (row.id != null) 'id': row.id,
    'key': row.key,
    'value': row.value,
  };
}
