// GENERATED BY dartway generate. DO NOT EDIT.
part of 'content.dart';

mixin _$NewsPostRow on DwTableRow {
  NewsPostRow get _self => this as NewsPostRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewsPostRow &&
          other.id == _self.id &&
          other.authorProfileId == _self.authorProfileId &&
          other.title == _self.title &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.authorProfileId,
    _self.title,
    _self.text,
    _self.createdAt,
  );

  @override
  String toString() =>
      'NewsPostRow(id: ${_self.id}, authorProfileId: ${_self.authorProfileId}, title: ${_self.title}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

extension NewsPostRowCopyWith on NewsPostRow {
  NewsPostRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? authorProfileId,
    String? title,
    String? text,
    DateTime? createdAt,
  }) => NewsPostRow(
    id: id.apply(this.id),
    authorProfileId: authorProfileId ?? this.authorProfileId,
    title: title ?? this.title,
    text: text ?? this.text,
    createdAt: createdAt ?? this.createdAt,
  );
}

final class NewsPostTable extends DwTableDef<NewsPostRow> {
  const NewsPostTable() : super('news_post');

  DwTableColumn<int> get authorProfileId => const DwTableColumn(
    'author_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<String> get title =>
      const DwTableColumn('title', DwColumnType.text);

  DwTableColumn<String> get text =>
      const DwTableColumn('text', DwColumnType.text);

  DwTableColumn<DateTime> get createdAt =>
      const DwTableColumn('created_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get columns => [
    id,
    authorProfileId,
    title,
    text,
    createdAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('news_post_created_at_idx', ['created_at']),
  ];

  @override
  NewsPostRow fromRow(DwResultRow row) => NewsPostRow(
    id: row.decode(id),
    authorProfileId: row.decode(authorProfileId),
    title: row.decode(title),
    text: row.decode(text),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(NewsPostRow row) => {
    if (row.id != null) 'id': row.id,
    'author_profile_id': row.authorProfileId,
    'title': row.title,
    'text': row.text,
    'created_at': row.createdAt,
  };
}

mixin _$ChatChannelRow on DwTableRow {
  ChatChannelRow get _self => this as ChatChannelRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChannelRow &&
          other.id == _self.id &&
          other.title == _self.title;

  @override
  int get hashCode => Object.hash(_self.id, _self.title);

  @override
  String toString() => 'ChatChannelRow(id: ${_self.id}, title: ${_self.title})';
}

extension ChatChannelRowCopyWith on ChatChannelRow {
  ChatChannelRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    String? title,
  }) => ChatChannelRow(id: id.apply(this.id), title: title ?? this.title);
}

final class ChatChannelTable extends DwTableDef<ChatChannelRow> {
  const ChatChannelTable() : super('chat_channel');

  DwTableColumn<String> get title =>
      const DwTableColumn('title', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get columns => [id, title];

  @override
  ChatChannelRow fromRow(DwResultRow row) =>
      ChatChannelRow(id: row.decode(id), title: row.decode(title));

  @override
  Map<String, Object?> toRow(ChatChannelRow row) => {
    if (row.id != null) 'id': row.id,
    'title': row.title,
  };
}

mixin _$ChatMessageRow on DwTableRow {
  ChatMessageRow get _self => this as ChatMessageRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageRow &&
          other.id == _self.id &&
          other.channelId == _self.channelId &&
          other.authorProfileId == _self.authorProfileId &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.channelId,
    _self.authorProfileId,
    _self.text,
    _self.createdAt,
  );

  @override
  String toString() =>
      'ChatMessageRow(id: ${_self.id}, channelId: ${_self.channelId}, authorProfileId: ${_self.authorProfileId}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

extension ChatMessageRowCopyWith on ChatMessageRow {
  ChatMessageRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? channelId,
    int? authorProfileId,
    String? text,
    DateTime? createdAt,
  }) => ChatMessageRow(
    id: id.apply(this.id),
    channelId: channelId ?? this.channelId,
    authorProfileId: authorProfileId ?? this.authorProfileId,
    text: text ?? this.text,
    createdAt: createdAt ?? this.createdAt,
  );
}

final class ChatMessageTable extends DwTableDef<ChatMessageRow> {
  const ChatMessageTable() : super('chat_message');

  DwTableColumn<int> get channelId => const DwTableColumn(
    'channel_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_channel', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get authorProfileId => const DwTableColumn(
    'author_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<String> get text =>
      const DwTableColumn('text', DwColumnType.text);

  DwTableColumn<DateTime> get createdAt =>
      const DwTableColumn('created_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get columns => [
    id,
    channelId,
    authorProfileId,
    text,
    createdAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('chat_message_channel_id_created_at_id_idx', [
      'channel_id',
      'created_at',
      'id',
    ]),
  ];

  @override
  ChatMessageRow fromRow(DwResultRow row) => ChatMessageRow(
    id: row.decode(id),
    channelId: row.decode(channelId),
    authorProfileId: row.decode(authorProfileId),
    text: row.decode(text),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(ChatMessageRow row) => {
    if (row.id != null) 'id': row.id,
    'channel_id': row.channelId,
    'author_profile_id': row.authorProfileId,
    'text': row.text,
    'created_at': row.createdAt,
  };
}

mixin _$AppSettingRow on DwTableRow {
  AppSettingRow get _self => this as AppSettingRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettingRow &&
          other.id == _self.id &&
          other.key == _self.key &&
          other.value == _self.value;

  @override
  int get hashCode => Object.hash(_self.id, _self.key, _self.value);

  @override
  String toString() =>
      'AppSettingRow(id: ${_self.id}, key: ${_self.key}, value: ${_self.value})';
}

extension AppSettingRowCopyWith on AppSettingRow {
  AppSettingRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    String? key,
    String? value,
  }) => AppSettingRow(
    id: id.apply(this.id),
    key: key ?? this.key,
    value: value ?? this.value,
  );
}

final class AppSettingTable extends DwTableDef<AppSettingRow> {
  const AppSettingTable() : super('app_setting');

  DwTableColumn<String> get key =>
      const DwTableColumn('key', DwColumnType.text, unique: true);

  DwTableColumn<String> get value =>
      const DwTableColumn('value', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get columns => [id, key, value];

  @override
  AppSettingRow fromRow(DwResultRow row) => AppSettingRow(
    id: row.decode(id),
    key: row.decode(key),
    value: row.decode(value),
  );

  @override
  Map<String, Object?> toRow(AppSettingRow row) => {
    if (row.id != null) 'id': row.id,
    'key': row.key,
    'value': row.value,
  };
}
