// GENERATED BY dartway generate. DO NOT EDIT.
part of 'content.dart';

mixin _$NewsPost on DwEntity {
  NewsPost get _self => this as NewsPost;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewsPost &&
          other.id == _self.id &&
          other.authorProfileId == _self.authorProfileId &&
          other.title == _self.title &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.authorProfileId,
    _self.title,
    _self.text,
    _self.createdAt,
  );

  @override
  String toString() =>
      'NewsPost(id: ${_self.id}, authorProfileId: ${_self.authorProfileId}, title: ${_self.title}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

extension NewsPostCopyWith on NewsPost {
  NewsPost copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    int? authorProfileId,
    String? title,
    String? text,
    DateTime? createdAt,
  }) => NewsPost(
    id: id.apply(this.id),
    authorProfileId: authorProfileId ?? this.authorProfileId,
    title: title ?? this.title,
    text: text ?? this.text,
    createdAt: createdAt ?? this.createdAt,
  );
}

final class NewsPostTable extends DwTableDef<NewsPost> {
  const NewsPostTable() : super('news_post');

  DwColumn<int> get authorProfileId => const DwColumn(
    'author_profile_id',
    DwType.bigint,
    references: DwReferences('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwColumn<String> get title => const DwColumn('title', DwType.text);

  DwColumn<String> get text => const DwColumn('text', DwType.text);

  DwColumn<DateTime> get createdAt =>
      const DwColumn('created_at', DwType.timestamptz);

  @override
  List<DwColumn<Object?>> get columns => [
    id,
    authorProfileId,
    title,
    text,
    createdAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('news_post_created_at_idx', ['created_at']),
  ];

  @override
  NewsPost fromRow(DwRow row) => NewsPost(
    id: row.decode(id),
    authorProfileId: row.decode(authorProfileId),
    title: row.decode(title),
    text: row.decode(text),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(NewsPost entity) => {
    if (entity.id != null) 'id': entity.id,
    'author_profile_id': entity.authorProfileId,
    'title': entity.title,
    'text': entity.text,
    'created_at': entity.createdAt,
  };
}

mixin _$ChatChannel on DwEntity {
  ChatChannel get _self => this as ChatChannel;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChannel &&
          other.id == _self.id &&
          other.title == _self.title;

  @override
  int get hashCode => Object.hash(_self.id, _self.title);

  @override
  String toString() => 'ChatChannel(id: ${_self.id}, title: ${_self.title})';
}

extension ChatChannelCopyWith on ChatChannel {
  ChatChannel copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    String? title,
  }) => ChatChannel(id: id.apply(this.id), title: title ?? this.title);
}

final class ChatChannelTable extends DwTableDef<ChatChannel> {
  const ChatChannelTable() : super('chat_channel');

  DwColumn<String> get title => const DwColumn('title', DwType.text);

  @override
  List<DwColumn<Object?>> get columns => [id, title];

  @override
  ChatChannel fromRow(DwRow row) =>
      ChatChannel(id: row.decode(id), title: row.decode(title));

  @override
  Map<String, Object?> toRow(ChatChannel entity) => {
    if (entity.id != null) 'id': entity.id,
    'title': entity.title,
  };
}

mixin _$ChatMessage on DwEntity {
  ChatMessage get _self => this as ChatMessage;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          other.id == _self.id &&
          other.channelId == _self.channelId &&
          other.authorProfileId == _self.authorProfileId &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.channelId,
    _self.authorProfileId,
    _self.text,
    _self.createdAt,
  );

  @override
  String toString() =>
      'ChatMessage(id: ${_self.id}, channelId: ${_self.channelId}, authorProfileId: ${_self.authorProfileId}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

extension ChatMessageCopyWith on ChatMessage {
  ChatMessage copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    int? channelId,
    int? authorProfileId,
    String? text,
    DateTime? createdAt,
  }) => ChatMessage(
    id: id.apply(this.id),
    channelId: channelId ?? this.channelId,
    authorProfileId: authorProfileId ?? this.authorProfileId,
    text: text ?? this.text,
    createdAt: createdAt ?? this.createdAt,
  );
}

final class ChatMessageTable extends DwTableDef<ChatMessage> {
  const ChatMessageTable() : super('chat_message');

  DwColumn<int> get channelId => const DwColumn(
    'channel_id',
    DwType.bigint,
    references: DwReferences('chat_channel', onDelete: DwOnDelete.cascade),
  );

  DwColumn<int> get authorProfileId => const DwColumn(
    'author_profile_id',
    DwType.bigint,
    references: DwReferences('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwColumn<String> get text => const DwColumn('text', DwType.text);

  DwColumn<DateTime> get createdAt =>
      const DwColumn('created_at', DwType.timestamptz);

  @override
  List<DwColumn<Object?>> get columns => [
    id,
    channelId,
    authorProfileId,
    text,
    createdAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('chat_message_channel_id_id_idx', ['channel_id', 'id']),
  ];

  @override
  ChatMessage fromRow(DwRow row) => ChatMessage(
    id: row.decode(id),
    channelId: row.decode(channelId),
    authorProfileId: row.decode(authorProfileId),
    text: row.decode(text),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(ChatMessage entity) => {
    if (entity.id != null) 'id': entity.id,
    'channel_id': entity.channelId,
    'author_profile_id': entity.authorProfileId,
    'text': entity.text,
    'created_at': entity.createdAt,
  };
}

mixin _$AppSetting on DwEntity {
  AppSetting get _self => this as AppSetting;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSetting &&
          other.id == _self.id &&
          other.key == _self.key &&
          other.value == _self.value;

  @override
  int get hashCode => Object.hash(_self.id, _self.key, _self.value);

  @override
  String toString() =>
      'AppSetting(id: ${_self.id}, key: ${_self.key}, value: ${_self.value})';
}

extension AppSettingCopyWith on AppSetting {
  AppSetting copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    String? key,
    String? value,
  }) => AppSetting(
    id: id.apply(this.id),
    key: key ?? this.key,
    value: value ?? this.value,
  );
}

final class AppSettingTable extends DwTableDef<AppSetting> {
  const AppSettingTable() : super('app_setting');

  DwColumn<String> get key => const DwColumn('key', DwType.text, unique: true);

  DwColumn<String> get value => const DwColumn('value', DwType.text);

  @override
  List<DwColumn<Object?>> get columns => [id, key, value];

  @override
  AppSetting fromRow(DwRow row) => AppSetting(
    id: row.decode(id),
    key: row.decode(key),
    value: row.decode(value),
  );

  @override
  Map<String, Object?> toRow(AppSetting entity) => {
    if (entity.id != null) 'id': entity.id,
    'key': entity.key,
    'value': entity.value,
  };
}
