// GENERATED BY dartway generate. DO NOT EDIT.
part of 'people.dart';

mixin _$UserProfile on DwEntity {
  UserProfile get _self => this as UserProfile;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          other.id == _self.id &&
          other.accountId == _self.accountId &&
          other.phone == _self.phone &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.imageUrl == _self.imageUrl &&
          other.gender == _self.gender &&
          other.role == _self.role &&
          other.agreedForMarketing == _self.agreedForMarketing &&
          other.conditionsAcceptedAt == _self.conditionsAcceptedAt &&
          other.testVerificationCode == _self.testVerificationCode;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.accountId,
    _self.phone,
    _self.firstName,
    _self.lastName,
    _self.imageUrl,
    _self.gender,
    _self.role,
    _self.agreedForMarketing,
    _self.conditionsAcceptedAt,
    _self.testVerificationCode,
  );

  @override
  String toString() =>
      'UserProfile(id: ${_self.id}, accountId: ${_self.accountId}, phone: ${_self.phone}, firstName: ${_self.firstName}, lastName: ${_self.lastName}, imageUrl: ${_self.imageUrl}, gender: ${_self.gender}, role: ${_self.role}, agreedForMarketing: ${_self.agreedForMarketing}, conditionsAcceptedAt: ${_self.conditionsAcceptedAt}, testVerificationCode: ${_self.testVerificationCode})';
}

extension UserProfileCopyWith on UserProfile {
  UserProfile copyWith({
    DwPatch<int> id = const DwPatch.keep(),
    int? accountId,
    String? phone,
    String? firstName,
    DwPatch<String> lastName = const DwPatch.keep(),
    DwPatch<String> imageUrl = const DwPatch.keep(),
    DwPatch<UserGender> gender = const DwPatch.keep(),
    UserRole? role,
    bool? agreedForMarketing,
    DateTime? conditionsAcceptedAt,
    DwPatch<String> testVerificationCode = const DwPatch.keep(),
  }) => UserProfile(
    id: id.apply(this.id),
    accountId: accountId ?? this.accountId,
    phone: phone ?? this.phone,
    firstName: firstName ?? this.firstName,
    lastName: lastName.apply(this.lastName),
    imageUrl: imageUrl.apply(this.imageUrl),
    gender: gender.apply(this.gender),
    role: role ?? this.role,
    agreedForMarketing: agreedForMarketing ?? this.agreedForMarketing,
    conditionsAcceptedAt: conditionsAcceptedAt ?? this.conditionsAcceptedAt,
    testVerificationCode: testVerificationCode.apply(this.testVerificationCode),
  );
}

final class UserProfileTable extends DwTableDef<UserProfile> {
  const UserProfileTable() : super('user_profile');

  DwColumn<int> get accountId => const DwColumn(
    'account_id',
    DwType.bigint,
    unique: true,
    references: DwReferences('dw_account', onDelete: DwOnDelete.cascade),
  );

  DwColumn<String> get phone => const DwColumn('phone', DwType.text);

  DwColumn<String> get firstName => const DwColumn('first_name', DwType.text);

  DwColumn<String?> get lastName => const DwColumn('last_name', DwType.text);

  DwColumn<String?> get imageUrl => const DwColumn('image_url', DwType.text);

  DwColumn<UserGender?> get gender =>
      const DwColumn('gender', DwEnumType(UserGender.values));

  DwColumn<UserRole> get role =>
      const DwColumn('role', DwEnumType(UserRole.values));

  DwColumn<bool> get agreedForMarketing =>
      const DwColumn('agreed_for_marketing', DwType.boolean);

  DwColumn<DateTime> get conditionsAcceptedAt =>
      const DwColumn('conditions_accepted_at', DwType.timestamptz);

  DwColumn<String?> get testVerificationCode =>
      const DwColumn('test_verification_code', DwType.text);

  @override
  List<DwColumn<Object?>> get columns => [
    id,
    accountId,
    phone,
    firstName,
    lastName,
    imageUrl,
    gender,
    role,
    agreedForMarketing,
    conditionsAcceptedAt,
    testVerificationCode,
  ];

  @override
  UserProfile fromRow(DwRow row) => UserProfile(
    id: row.decode(id),
    accountId: row.decode(accountId),
    phone: row.decode(phone),
    firstName: row.decode(firstName),
    lastName: row.decode(lastName),
    imageUrl: row.decode(imageUrl),
    gender: row.decode(gender),
    role: row.decode(role),
    agreedForMarketing: row.decode(agreedForMarketing),
    conditionsAcceptedAt: row.decode(conditionsAcceptedAt),
    testVerificationCode: row.decode(testVerificationCode),
  );

  @override
  Map<String, Object?> toRow(UserProfile entity) => {
    if (entity.id != null) 'id': entity.id,
    'account_id': entity.accountId,
    'phone': entity.phone,
    'first_name': entity.firstName,
    'last_name': entity.lastName,
    'image_url': entity.imageUrl,
    'gender': entity.gender,
    'role': entity.role,
    'agreed_for_marketing': entity.agreedForMarketing,
    'conditions_accepted_at': entity.conditionsAcceptedAt,
    'test_verification_code': entity.testVerificationCode,
  };
}
