// GENERATED BY dartway generate. DO NOT EDIT.
part of 'people.dart';

mixin _$UserProfileRow on DwTableRow {
  UserProfileRow get _self => this as UserProfileRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfileRow &&
          other.id == _self.id &&
          other.accountId == _self.accountId &&
          other.phone == _self.phone &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.imageUrl == _self.imageUrl &&
          other.gender == _self.gender &&
          other.role == _self.role &&
          other.agreedForMarketing == _self.agreedForMarketing &&
          other.conditionsAcceptedAt == _self.conditionsAcceptedAt &&
          other.testVerificationCode == _self.testVerificationCode;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.accountId,
    _self.phone,
    _self.firstName,
    _self.lastName,
    _self.imageUrl,
    _self.gender,
    _self.role,
    _self.agreedForMarketing,
    _self.conditionsAcceptedAt,
    _self.testVerificationCode,
  );

  @override
  String toString() =>
      'UserProfileRow(id: ${_self.id}, accountId: ${_self.accountId}, phone: ${_self.phone}, firstName: ${_self.firstName}, lastName: ${_self.lastName}, imageUrl: ${_self.imageUrl}, gender: ${_self.gender}, role: ${_self.role}, agreedForMarketing: ${_self.agreedForMarketing}, conditionsAcceptedAt: ${_self.conditionsAcceptedAt}, testVerificationCode: ${_self.testVerificationCode})';
}

extension UserProfileRowCopyWith on UserProfileRow {
  UserProfileRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? accountId,
    String? phone,
    String? firstName,
    DwFieldPatch<String> lastName = const DwFieldPatch.keep(),
    DwFieldPatch<String> imageUrl = const DwFieldPatch.keep(),
    DwFieldPatch<UserGender> gender = const DwFieldPatch.keep(),
    UserRole? role,
    bool? agreedForMarketing,
    DateTime? conditionsAcceptedAt,
    DwFieldPatch<String> testVerificationCode = const DwFieldPatch.keep(),
  }) => UserProfileRow(
    id: id.apply(this.id),
    accountId: accountId ?? this.accountId,
    phone: phone ?? this.phone,
    firstName: firstName ?? this.firstName,
    lastName: lastName.apply(this.lastName),
    imageUrl: imageUrl.apply(this.imageUrl),
    gender: gender.apply(this.gender),
    role: role ?? this.role,
    agreedForMarketing: agreedForMarketing ?? this.agreedForMarketing,
    conditionsAcceptedAt: conditionsAcceptedAt ?? this.conditionsAcceptedAt,
    testVerificationCode: testVerificationCode.apply(this.testVerificationCode),
  );
}

final class UserProfileTable extends DwTableDef<UserProfileRow> {
  const UserProfileTable() : super('user_profile');

  DwTableColumn<int> get accountId => const DwTableColumn(
    'account_id',
    DwColumnType.bigint,
    unique: true,
    references: DwForeignKey('dw_account', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<String> get phone =>
      const DwTableColumn('phone', DwColumnType.text);

  DwTableColumn<String> get firstName =>
      const DwTableColumn('first_name', DwColumnType.text);

  DwTableColumn<String?> get lastName =>
      const DwTableColumn('last_name', DwColumnType.text);

  DwTableColumn<String?> get imageUrl =>
      const DwTableColumn('image_url', DwColumnType.text);

  DwTableColumn<UserGender?> get gender =>
      const DwTableColumn('gender', DwEnumType(UserGender.values));

  DwTableColumn<UserRole> get role =>
      const DwTableColumn('role', DwEnumType(UserRole.values));

  DwTableColumn<bool> get agreedForMarketing =>
      const DwTableColumn('agreed_for_marketing', DwColumnType.boolean);

  DwTableColumn<DateTime> get conditionsAcceptedAt =>
      const DwTableColumn('conditions_accepted_at', DwColumnType.timestamptz);

  DwTableColumn<String?> get testVerificationCode =>
      const DwTableColumn('test_verification_code', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    accountId,
    phone,
    firstName,
    lastName,
    imageUrl,
    gender,
    role,
    agreedForMarketing,
    conditionsAcceptedAt,
    testVerificationCode,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('user_profile_first_name_idx', ['first_name']),
  ];

  @override
  UserProfileRow fromRow(DwResultRow row) => UserProfileRow(
    id: row.decode(id),
    accountId: row.decode(accountId),
    phone: row.decode(phone),
    firstName: row.decode(firstName),
    lastName: row.decode(lastName),
    imageUrl: row.decode(imageUrl),
    gender: row.decode(gender),
    role: row.decode(role),
    agreedForMarketing: row.decode(agreedForMarketing),
    conditionsAcceptedAt: row.decode(conditionsAcceptedAt),
    testVerificationCode: row.decode(testVerificationCode),
  );

  @override
  Map<String, Object?> toRow(UserProfileRow row) => {
    if (row.id != null) 'id': row.id,
    'account_id': row.accountId,
    'phone': row.phone,
    'first_name': row.firstName,
    'last_name': row.lastName,
    'image_url': row.imageUrl,
    'gender': row.gender,
    'role': row.role,
    'agreed_for_marketing': row.agreedForMarketing,
    'conditions_accepted_at': row.conditionsAcceptedAt,
    'test_verification_code': row.testVerificationCode,
  };
}
