// GENERATED BY dartway generate. DO NOT EDIT.
part of 'settings_rows.dart';

mixin _$AppSettingRow on DwTableRow {
  AppSettingRow get _self => this as AppSettingRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettingRow &&
          other.id == _self.id &&
          other.key == _self.key &&
          other.value == _self.value;

  @override
  int get hashCode => Object.hash(_self.id, _self.key, _self.value);

  @override
  String toString() =>
      'AppSettingRow(id: ${_self.id}, key: ${_self.key}, value: ${_self.value})';
}

extension AppSettingRowCopyWith on AppSettingRow {
  AppSettingRow copyWith({String? key, String? value}) =>
      AppSettingRow(id: id, key: key ?? this.key, value: value ?? this.value);
}

/// A [AppSettingRow] before insert: every column but the id.
final class NewAppSettingRow extends DwRowDraft<AppSettingRow> {
  const NewAppSettingRow({required this.key, required this.value});

  final String key;
  final String value;
}

extension NewAppSettingRowCopyWith on NewAppSettingRow {
  NewAppSettingRow copyWith({String? key, String? value}) =>
      NewAppSettingRow(key: key ?? this.key, value: value ?? this.value);
}

extension NewAppSettingRowWithId on NewAppSettingRow {
  /// The row stored under [id], for `update`.
  AppSettingRow withId(int id) => AppSettingRow(id: id, key: key, value: value);
}

final class AppSettingTable extends DwTableDef<AppSettingRow> {
  const AppSettingTable() : super('app_setting');

  DwTableColumn<String> get key =>
      const DwTableColumn('key', DwColumnType.text, unique: true);

  DwTableColumn<String> get value =>
      const DwTableColumn('value', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [id, key, value];

  @override
  AppSettingRow fromRow(DwResultRow row) => AppSettingRow(
    id: row.decode(id),
    key: row.decode(key),
    value: row.decode(value),
  );

  @override
  Map<String, Object?> toRow(AppSettingRow row) => {
    'key': row.key,
    'value': row.value,
  };

  @override
  Map<String, Object?> toDraftRow(NewAppSettingRow draft) => {
    'key': draft.key,
    'value': draft.value,
  };
}
