// GENERATED BY dartway generate. DO NOT EDIT.
part of 'club_rows.dart';

mixin _$ClubServiceRow on DwTableRow {
  ClubServiceRow get _self => this as ClubServiceRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubServiceRow &&
          other.id == _self.id &&
          other.title == _self.title &&
          other.description == _self.description &&
          other.durationMinutes == _self.durationMinutes &&
          other.price == _self.price &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.title,
    _self.description,
    _self.durationMinutes,
    _self.price,
    _self.imageUrl,
  );

  @override
  String toString() =>
      'ClubServiceRow(id: ${_self.id}, title: ${_self.title}, description: ${_self.description}, durationMinutes: ${_self.durationMinutes}, price: ${_self.price}, imageUrl: ${_self.imageUrl})';
}

extension ClubServiceRowCopyWith on ClubServiceRow {
  ClubServiceRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    String? title,
    String? description,
    int? durationMinutes,
    int? price,
    DwFieldPatch<String> imageUrl = const DwFieldPatch.keep(),
  }) => ClubServiceRow(
    id: id.apply(this.id),
    title: title ?? this.title,
    description: description ?? this.description,
    durationMinutes: durationMinutes ?? this.durationMinutes,
    price: price ?? this.price,
    imageUrl: imageUrl.apply(this.imageUrl),
  );
}

final class ClubServiceTable extends DwTableDef<ClubServiceRow> {
  const ClubServiceTable() : super('club_service');

  DwTableColumn<String> get title =>
      const DwTableColumn('title', DwColumnType.text);

  DwTableColumn<String> get description =>
      const DwTableColumn('description', DwColumnType.text);

  DwTableColumn<int> get durationMinutes =>
      const DwTableColumn('duration_minutes', DwColumnType.bigint);

  DwTableColumn<int> get price =>
      const DwTableColumn('price', DwColumnType.bigint);

  DwTableColumn<String?> get imageUrl =>
      const DwTableColumn('image_url', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    title,
    description,
    durationMinutes,
    price,
    imageUrl,
  ];

  @override
  ClubServiceRow fromRow(DwResultRow row) => ClubServiceRow(
    id: row.decode(id),
    title: row.decode(title),
    description: row.decode(description),
    durationMinutes: row.decode(durationMinutes),
    price: row.decode(price),
    imageUrl: row.decode(imageUrl),
  );

  @override
  Map<String, Object?> toRow(ClubServiceRow row) => {
    if (row.id != null) 'id': row.id,
    'title': row.title,
    'description': row.description,
    'duration_minutes': row.durationMinutes,
    'price': row.price,
    'image_url': row.imageUrl,
  };
}

mixin _$ClubSessionRow on DwTableRow {
  ClubSessionRow get _self => this as ClubSessionRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubSessionRow &&
          other.id == _self.id &&
          other.serviceId == _self.serviceId &&
          other.coachProfileId == _self.coachProfileId &&
          other.startsAt == _self.startsAt &&
          other.capacity == _self.capacity &&
          other.bookedCount == _self.bookedCount;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.serviceId,
    _self.coachProfileId,
    _self.startsAt,
    _self.capacity,
    _self.bookedCount,
  );

  @override
  String toString() =>
      'ClubSessionRow(id: ${_self.id}, serviceId: ${_self.serviceId}, coachProfileId: ${_self.coachProfileId}, startsAt: ${_self.startsAt}, capacity: ${_self.capacity}, bookedCount: ${_self.bookedCount})';
}

extension ClubSessionRowCopyWith on ClubSessionRow {
  ClubSessionRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? serviceId,
    DwFieldPatch<int> coachProfileId = const DwFieldPatch.keep(),
    DateTime? startsAt,
    int? capacity,
    int? bookedCount,
  }) => ClubSessionRow(
    id: id.apply(this.id),
    serviceId: serviceId ?? this.serviceId,
    coachProfileId: coachProfileId.apply(this.coachProfileId),
    startsAt: startsAt ?? this.startsAt,
    capacity: capacity ?? this.capacity,
    bookedCount: bookedCount ?? this.bookedCount,
  );
}

final class ClubSessionTable extends DwTableDef<ClubSessionRow> {
  const ClubSessionTable() : super('club_session');

  DwTableColumn<int> get serviceId => const DwTableColumn(
    'service_id',
    DwColumnType.bigint,
    references: DwForeignKey('club_service', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int?> get coachProfileId => const DwTableColumn(
    'coach_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.setNull),
  );

  DwTableColumn<DateTime> get startsAt =>
      const DwTableColumn('starts_at', DwColumnType.timestamptz);

  DwTableColumn<int> get capacity =>
      const DwTableColumn('capacity', DwColumnType.bigint);

  DwTableColumn<int> get bookedCount =>
      const DwTableColumn('booked_count', DwColumnType.bigint);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    serviceId,
    coachProfileId,
    startsAt,
    capacity,
    bookedCount,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('club_session_starts_at_idx', ['starts_at']),
  ];

  @override
  ClubSessionRow fromRow(DwResultRow row) => ClubSessionRow(
    id: row.decode(id),
    serviceId: row.decode(serviceId),
    coachProfileId: row.decode(coachProfileId),
    startsAt: row.decode(startsAt),
    capacity: row.decode(capacity),
    bookedCount: row.decode(bookedCount),
  );

  @override
  Map<String, Object?> toRow(ClubSessionRow row) => {
    if (row.id != null) 'id': row.id,
    'service_id': row.serviceId,
    'coach_profile_id': row.coachProfileId,
    'starts_at': row.startsAt,
    'capacity': row.capacity,
    'booked_count': row.bookedCount,
  };
}

mixin _$SessionBookingRow on DwTableRow {
  SessionBookingRow get _self => this as SessionBookingRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionBookingRow &&
          other.id == _self.id &&
          other.sessionId == _self.sessionId &&
          other.clientProfileId == _self.clientProfileId &&
          other.status == _self.status &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.sessionId,
    _self.clientProfileId,
    _self.status,
    _self.createdAt,
  );

  @override
  String toString() =>
      'SessionBookingRow(id: ${_self.id}, sessionId: ${_self.sessionId}, clientProfileId: ${_self.clientProfileId}, status: ${_self.status}, createdAt: ${_self.createdAt})';
}

extension SessionBookingRowCopyWith on SessionBookingRow {
  SessionBookingRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? sessionId,
    int? clientProfileId,
    BookingStatus? status,
    DateTime? createdAt,
  }) => SessionBookingRow(
    id: id.apply(this.id),
    sessionId: sessionId ?? this.sessionId,
    clientProfileId: clientProfileId ?? this.clientProfileId,
    status: status ?? this.status,
    createdAt: createdAt ?? this.createdAt,
  );
}

final class SessionBookingTable extends DwTableDef<SessionBookingRow> {
  const SessionBookingTable() : super('session_booking');

  DwTableColumn<int> get sessionId => const DwTableColumn(
    'session_id',
    DwColumnType.bigint,
    references: DwForeignKey('club_session', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get clientProfileId => const DwTableColumn(
    'client_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<BookingStatus> get status =>
      const DwTableColumn('status', DwEnumType(BookingStatus.values));

  DwTableColumn<DateTime> get createdAt =>
      const DwTableColumn('created_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    sessionId,
    clientProfileId,
    status,
    createdAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('session_booking_client_profile_id_created_at_idx', [
      'client_profile_id',
      'created_at',
    ]),
    DwIndexSchema('session_booking_session_id_status_idx', [
      'session_id',
      'status',
    ]),
  ];

  @override
  SessionBookingRow fromRow(DwResultRow row) => SessionBookingRow(
    id: row.decode(id),
    sessionId: row.decode(sessionId),
    clientProfileId: row.decode(clientProfileId),
    status: row.decode(status),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(SessionBookingRow row) => {
    if (row.id != null) 'id': row.id,
    'session_id': row.sessionId,
    'client_profile_id': row.clientProfileId,
    'status': row.status,
    'created_at': row.createdAt,
  };
}

mixin _$SessionReviewRow on DwTableRow {
  SessionReviewRow get _self => this as SessionReviewRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionReviewRow &&
          other.id == _self.id &&
          other.bookingId == _self.bookingId &&
          other.rating == _self.rating &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.bookingId,
    _self.rating,
    _self.text,
    _self.createdAt,
  );

  @override
  String toString() =>
      'SessionReviewRow(id: ${_self.id}, bookingId: ${_self.bookingId}, rating: ${_self.rating}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

extension SessionReviewRowCopyWith on SessionReviewRow {
  SessionReviewRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? bookingId,
    int? rating,
    DwFieldPatch<String> text = const DwFieldPatch.keep(),
    DateTime? createdAt,
  }) => SessionReviewRow(
    id: id.apply(this.id),
    bookingId: bookingId ?? this.bookingId,
    rating: rating ?? this.rating,
    text: text.apply(this.text),
    createdAt: createdAt ?? this.createdAt,
  );
}

final class SessionReviewTable extends DwTableDef<SessionReviewRow> {
  const SessionReviewTable() : super('session_review');

  DwTableColumn<int> get bookingId => const DwTableColumn(
    'booking_id',
    DwColumnType.bigint,
    unique: true,
    references: DwForeignKey('session_booking', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get rating =>
      const DwTableColumn('rating', DwColumnType.bigint);

  DwTableColumn<String?> get text =>
      const DwTableColumn('text', DwColumnType.text);

  DwTableColumn<DateTime> get createdAt =>
      const DwTableColumn('created_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    bookingId,
    rating,
    text,
    createdAt,
  ];

  @override
  SessionReviewRow fromRow(DwResultRow row) => SessionReviewRow(
    id: row.decode(id),
    bookingId: row.decode(bookingId),
    rating: row.decode(rating),
    text: row.decode(text),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(SessionReviewRow row) => {
    if (row.id != null) 'id': row.id,
    'booking_id': row.bookingId,
    'rating': row.rating,
    'text': row.text,
    'created_at': row.createdAt,
  };
}
