// GENERATED BY dartway generate. DO NOT EDIT.
part of 'club_booking.dart';

mixin _$ClubBooking on DwDataObject {
  ClubBooking get _self => this as ClubBooking;

  @override
  String get dwTypeName => 'ClubBooking';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'status': _self.status.name,
    'startsAt': DwJsonCodec.encodeDateTime(_self.startsAt),
    if (_self.note != null) 'note': _self.note,
    if (_self.tags.isNotEmpty) 'tags': _self.tags,
    if (_self.seats != 1) 'seats': _self.seats,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubBooking &&
          other.id == _self.id &&
          other.status == _self.status &&
          other.startsAt == _self.startsAt &&
          other.note == _self.note &&
          dwListEquals(other.tags, _self.tags) &&
          other.seats == _self.seats;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.status,
    _self.startsAt,
    _self.note,
    Object.hashAll(_self.tags),
    _self.seats,
  );

  @override
  String toString() =>
      'ClubBooking(id: ${_self.id}, status: ${_self.status}, startsAt: ${_self.startsAt}, note: ${_self.note}, tags: ${_self.tags}, seats: ${_self.seats})';
}

ClubBooking $ClubBookingFromJson(Map<String, Object?> json) => ClubBooking(
  id: json['id']! as int,
  status: DwJsonCodec.decodeEnum(json['status'], BookingStatus.values),
  startsAt: DwJsonCodec.decodeDateTime(json['startsAt']),
  note: json['note'] as String?,
  tags: json['tags'] == null
      ? const []
      : DwJsonCodec.decodeList(json['tags'], (e) => e! as String),
  seats: json['seats'] == null ? 1 : json['seats']! as int,
);

extension ClubBookingCopyWith on ClubBooking {
  ClubBooking copyWith({
    int? id,
    BookingStatus? status,
    DateTime? startsAt,
    DwFieldPatch<String> note = const DwFieldPatch.keep(),
    List<String>? tags,
    int? seats,
  }) => ClubBooking(
    id: id ?? this.id,
    status: status ?? this.status,
    startsAt: startsAt ?? this.startsAt,
    note: note.apply(this.note),
    tags: tags ?? this.tags,
    seats: seats ?? this.seats,
  );
}

mixin _$ListMyBookings on DwListRequest<ClubBooking> {
  ListMyBookings get _self => this as ListMyBookings;

  @override
  String get dwTypeName => 'ListMyBookings';

  @override
  Map<String, Object?> toJson() => {
    if (_self.status != null) 'status': _self.status!.name,
    if (_self.includePast) 'includePast': _self.includePast,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListMyBookings &&
          other.status == _self.status &&
          other.includePast == _self.includePast;

  @override
  int get hashCode =>
      Object.hash(ListMyBookings, _self.status, _self.includePast);

  @override
  String toString() =>
      'ListMyBookings(status: ${_self.status}, includePast: ${_self.includePast})';
}

ListMyBookings $ListMyBookingsFromJson(Map<String, Object?> json) =>
    ListMyBookings(
      status: json['status'] == null
          ? null
          : DwJsonCodec.decodeEnum(json['status'], BookingStatus.values),
      includePast: json['includePast'] == null
          ? false
          : json['includePast']! as bool,
    );

mixin _$RenameBooking on DwActionCommand<ClubBooking> {
  RenameBooking get _self => this as RenameBooking;

  @override
  String get dwTypeName => 'RenameBooking';

  @override
  Map<String, Object?> toJson() {
    final json = <String, Object?>{'bookingId': _self.bookingId};
    DwJsonCodec.writePatch(json, 'note', _self.note, (v) => v);
    return json;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenameBooking &&
          other.bookingId == _self.bookingId &&
          other.note == _self.note;

  @override
  int get hashCode => Object.hash(RenameBooking, _self.bookingId, _self.note);
}

RenameBooking $RenameBookingFromJson(Map<String, Object?> json) =>
    RenameBooking(
      bookingId: json['bookingId']! as int,
      note: DwJsonCodec.readPatch(json, 'note', (v) => v! as String),
    );
