// GENERATED BY dartway generate. DO NOT EDIT.
part of 'catalog_entry.dart';

mixin _$CatalogEntryRow on DwTableRow {
  CatalogEntryRow get _self => this as CatalogEntryRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogEntryRow &&
          other.id == _self.id &&
          other.name == _self.name &&
          other.schema == _self.schema &&
          other.columns == _self.columns &&
          other.table == _self.table &&
          other.row == _self.row &&
          other.where == _self.where &&
          other.order == _self.order;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.name,
    _self.schema,
    _self.columns,
    _self.table,
    _self.row,
    _self.where,
    _self.order,
  );

  @override
  String toString() =>
      'CatalogEntryRow(id: ${_self.id}, name: ${_self.name}, schema: ${_self.schema}, columns: ${_self.columns}, table: ${_self.table}, row: ${_self.row}, where: ${_self.where}, order: ${_self.order})';
}

extension CatalogEntryRowCopyWith on CatalogEntryRow {
  CatalogEntryRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    String? name,
    DwFieldPatch<String> schema = const DwFieldPatch.keep(),
    int? columns,
    DwFieldPatch<int> table = const DwFieldPatch.keep(),
    String? row,
    String? where,
    int? order,
  }) => CatalogEntryRow(
    id: id.apply(this.id),
    name: name ?? this.name,
    schema: schema.apply(this.schema),
    columns: columns ?? this.columns,
    table: table.apply(this.table),
    row: row ?? this.row,
    where: where ?? this.where,
    order: order ?? this.order,
  );
}

final class CatalogEntryTable extends DwTableDef<CatalogEntryRow> {
  const CatalogEntryTable() : super('catalog_entry');

  DwTableColumn<String> get name =>
      const DwTableColumn('name', DwColumnType.text);

  DwTableColumn<String?> get schema =>
      const DwTableColumn('schema', DwColumnType.text);

  DwTableColumn<int> get columns =>
      const DwTableColumn('columns', DwColumnType.bigint);

  DwTableColumn<int?> get table =>
      const DwTableColumn('table', DwColumnType.bigint);

  DwTableColumn<String> get row =>
      const DwTableColumn('row', DwColumnType.text);

  DwTableColumn<String> get where =>
      const DwTableColumn('where', DwColumnType.text);

  DwTableColumn<int> get order =>
      const DwTableColumn('order', DwColumnType.bigint);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    name,
    schema,
    columns,
    table,
    row,
    where,
    order,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('catalog_entry_name_idx', ['name']),
  ];

  @override
  CatalogEntryRow fromRow(DwResultRow row) => CatalogEntryRow(
    id: row.decode(id),
    name: row.decode(name),
    schema: row.decode(schema),
    columns: row.decode(columns),
    table: row.decode(table),
    row: row.decode(this.row),
    where: row.decode(where),
    order: row.decode(order),
  );

  @override
  Map<String, Object?> toRow(CatalogEntryRow row) => {
    if (row.id != null) 'id': row.id,
    'name': row.name,
    'schema': row.schema,
    'columns': row.columns,
    'table': row.table,
    'row': row.row,
    'where': row.where,
    'order': row.order,
  };
}
