// GENERATED BY dartway generate. DO NOT EDIT.
part of 'admin.dart';

mixin _$AdminCounters on DwDataObject {
  AdminCounters get _self => this as AdminCounters;

  @override
  String get dwTypeName => 'AdminCounters';

  @override
  Map<String, Object?> toJson() => {
    'members': _self.members,
    'upcomingSessions': _self.upcomingSessions,
    'newsPosts': _self.newsPosts,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdminCounters &&
          other.members == _self.members &&
          other.upcomingSessions == _self.upcomingSessions &&
          other.newsPosts == _self.newsPosts;

  @override
  int get hashCode =>
      Object.hash(_self.members, _self.upcomingSessions, _self.newsPosts);

  @override
  String toString() =>
      'AdminCounters(members: ${_self.members}, upcomingSessions: ${_self.upcomingSessions}, newsPosts: ${_self.newsPosts})';
}

AdminCounters $AdminCountersFromJson(Map<String, Object?> json) =>
    AdminCounters(
      members: json['members']! as int,
      upcomingSessions: json['upcomingSessions']! as int,
      newsPosts: json['newsPosts']! as int,
    );

extension AdminCountersCopyWith on AdminCounters {
  AdminCounters copyWith({
    int? members,
    int? upcomingSessions,
    int? newsPosts,
  }) => AdminCounters(
    members: members ?? this.members,
    upcomingSessions: upcomingSessions ?? this.upcomingSessions,
    newsPosts: newsPosts ?? this.newsPosts,
  );
}

mixin _$GetAdminCounters on DwSingleRequest<AdminCounters> {
  @override
  String get dwTypeName => 'GetAdminCounters';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is GetAdminCounters;

  @override
  int get hashCode => (GetAdminCounters).hashCode;

  @override
  String toString() => 'GetAdminCounters()';
}

GetAdminCounters $GetAdminCountersFromJson(Map<String, Object?> json) =>
    const GetAdminCounters();

mixin _$ListUserProfiles on DwTableRequest<UserProfile> {
  ListUserProfiles get _self => this as ListUserProfiles;

  @override
  String get dwTypeName => 'ListUserProfiles';

  @override
  Map<String, Object?> toJson() => {
    if (_self.page != 1) 'page': _self.page,
    if (_self.pageSize != 10) 'pageSize': _self.pageSize,
    if (_self.search != '') 'search': _self.search,
    if (_self.role != null) 'role': _self.role!.name,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListUserProfiles &&
          other.page == _self.page &&
          other.pageSize == _self.pageSize &&
          other.search == _self.search &&
          other.role == _self.role;

  @override
  int get hashCode => Object.hash(
    ListUserProfiles,
    _self.page,
    _self.pageSize,
    _self.search,
    _self.role,
  );

  @override
  String toString() =>
      'ListUserProfiles(page: ${_self.page}, pageSize: ${_self.pageSize}, search: ${_self.search}, role: ${_self.role})';
}

ListUserProfiles $ListUserProfilesFromJson(Map<String, Object?> json) =>
    ListUserProfiles(
      page: json['page'] == null ? 1 : json['page']! as int,
      pageSize: json['pageSize'] == null ? 10 : json['pageSize']! as int,
      search: json['search'] == null ? '' : json['search']! as String,
      role: json['role'] == null
          ? null
          : DwJsonCodec.decodeEnum(json['role'], UserRole.values),
    );

mixin _$ChangeRole on DwActionCommand<UserProfile> {
  ChangeRole get _self => this as ChangeRole;

  @override
  String get dwTypeName => 'ChangeRole';

  @override
  Map<String, Object?> toJson() => {
    'profileId': _self.profileId,
    'role': _self.role.name,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangeRole &&
          other.profileId == _self.profileId &&
          other.role == _self.role;

  @override
  int get hashCode => Object.hash(ChangeRole, _self.profileId, _self.role);
}

ChangeRole $ChangeRoleFromJson(Map<String, Object?> json) => ChangeRole(
  profileId: json['profileId']! as int,
  role: DwJsonCodec.decodeEnum(json['role'], UserRole.values),
);
