// GENERATED BY dartway generate. DO NOT EDIT.
part of 'admin.dart';

mixin _$AdminCountersView on DwDataObject {
  AdminCountersView get _self => this as AdminCountersView;

  @override
  String get dwTypeName => 'AdminCountersView';

  @override
  Map<String, Object?> toJson() => {
    'members': _self.members,
    'upcomingSessions': _self.upcomingSessions,
    'newsPosts': _self.newsPosts,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdminCountersView &&
          other.members == _self.members &&
          other.upcomingSessions == _self.upcomingSessions &&
          other.newsPosts == _self.newsPosts;

  @override
  int get hashCode =>
      Object.hash(_self.members, _self.upcomingSessions, _self.newsPosts);

  @override
  String toString() =>
      'AdminCountersView(members: ${_self.members}, upcomingSessions: ${_self.upcomingSessions}, newsPosts: ${_self.newsPosts})';
}

AdminCountersView $AdminCountersViewFromJson(Map<String, Object?> json) =>
    AdminCountersView(
      members: json['members']! as int,
      upcomingSessions: json['upcomingSessions']! as int,
      newsPosts: json['newsPosts']! as int,
    );

extension AdminCountersViewCopyWith on AdminCountersView {
  AdminCountersView copyWith({
    int? members,
    int? upcomingSessions,
    int? newsPosts,
  }) => AdminCountersView(
    members: members ?? this.members,
    upcomingSessions: upcomingSessions ?? this.upcomingSessions,
    newsPosts: newsPosts ?? this.newsPosts,
  );
}

mixin _$GetAdminCounters on DwSingleRequest<AdminCountersView> {
  @override
  String get dwTypeName => 'GetAdminCounters';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is GetAdminCounters;

  @override
  int get hashCode => (GetAdminCounters).hashCode;

  @override
  String toString() => 'GetAdminCounters()';
}

GetAdminCounters $GetAdminCountersFromJson(Map<String, Object?> json) =>
    const GetAdminCounters();

mixin _$ListProfiles on DwListRequest<ProfileView> {
  @override
  String get dwTypeName => 'ListProfiles';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is ListProfiles;

  @override
  int get hashCode => (ListProfiles).hashCode;

  @override
  String toString() => 'ListProfiles()';
}

ListProfiles $ListProfilesFromJson(Map<String, Object?> json) =>
    const ListProfiles();

mixin _$ChangeRole on DwCommand<ProfileView> {
  ChangeRole get _self => this as ChangeRole;

  @override
  String get dwTypeName => 'ChangeRole';

  @override
  Map<String, Object?> toJson() => {
    'profileId': _self.profileId,
    'role': _self.role.name,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangeRole &&
          other.profileId == _self.profileId &&
          other.role == _self.role;

  @override
  int get hashCode => Object.hash(ChangeRole, _self.profileId, _self.role);
}

ChangeRole $ChangeRoleFromJson(Map<String, Object?> json) => ChangeRole(
  profileId: json['profileId']! as int,
  role: DwJson.decodeEnum(json['role'], UserRole.values),
);
