// GENERATED BY dartway generate. DO NOT EDIT.
part of 'bookings.dart';

mixin _$SessionReview on DwDataObject {
  SessionReview get _self => this as SessionReview;

  @override
  String get dwTypeName => 'SessionReview';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'rating': _self.rating,
    if (_self.text != null) 'text': _self.text,
    'createdAt': DwJsonCodec.encodeDateTime(_self.createdAt),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionReview &&
          other.id == _self.id &&
          other.rating == _self.rating &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode =>
      Object.hash(_self.id, _self.rating, _self.text, _self.createdAt);

  @override
  String toString() =>
      'SessionReview(id: ${_self.id}, rating: ${_self.rating}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

SessionReview $SessionReviewFromJson(Map<String, Object?> json) =>
    SessionReview(
      id: json['id']! as int,
      rating: json['rating']! as int,
      text: json['text'] as String?,
      createdAt: DwJsonCodec.decodeDateTime(json['createdAt']),
    );

extension SessionReviewCopyWith on SessionReview {
  SessionReview copyWith({
    int? id,
    int? rating,
    DwFieldPatch<String> text = const DwFieldPatch.keep(),
    DateTime? createdAt,
  }) => SessionReview(
    id: id ?? this.id,
    rating: rating ?? this.rating,
    text: text.apply(this.text),
    createdAt: createdAt ?? this.createdAt,
  );
}

mixin _$SessionBooking on DwDataObject {
  SessionBooking get _self => this as SessionBooking;

  @override
  String get dwTypeName => 'SessionBooking';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'accountId': _self.accountId,
    'session': _self.session.toJson(),
    'status': _self.status.name,
    'createdAt': DwJsonCodec.encodeDateTime(_self.createdAt),
    if (_self.review != null) 'review': _self.review!.toJson(),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionBooking &&
          other.id == _self.id &&
          other.accountId == _self.accountId &&
          other.session == _self.session &&
          other.status == _self.status &&
          other.createdAt == _self.createdAt &&
          other.review == _self.review;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.accountId,
    _self.session,
    _self.status,
    _self.createdAt,
    _self.review,
  );

  @override
  String toString() =>
      'SessionBooking(id: ${_self.id}, accountId: ${_self.accountId}, session: ${_self.session}, status: ${_self.status}, createdAt: ${_self.createdAt}, review: ${_self.review})';
}

SessionBooking $SessionBookingFromJson(Map<String, Object?> json) =>
    SessionBooking(
      id: json['id']! as int,
      accountId: json['accountId']! as int,
      session: $ClubSessionFromJson(json['session']! as Map<String, Object?>),
      status: DwJsonCodec.decodeEnum(json['status'], BookingStatus.values),
      createdAt: DwJsonCodec.decodeDateTime(json['createdAt']),
      review: json['review'] == null
          ? null
          : $SessionReviewFromJson(json['review']! as Map<String, Object?>),
    );

extension SessionBookingCopyWith on SessionBooking {
  SessionBooking copyWith({
    int? id,
    int? accountId,
    ClubSession? session,
    BookingStatus? status,
    DateTime? createdAt,
    DwFieldPatch<SessionReview> review = const DwFieldPatch.keep(),
  }) => SessionBooking(
    id: id ?? this.id,
    accountId: accountId ?? this.accountId,
    session: session ?? this.session,
    status: status ?? this.status,
    createdAt: createdAt ?? this.createdAt,
    review: review.apply(this.review),
  );
}

mixin _$ListMyBookings on DwListRequest<SessionBooking> {
  @override
  String get dwTypeName => 'ListMyBookings';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is ListMyBookings;

  @override
  int get hashCode => (ListMyBookings).hashCode;

  @override
  String toString() => 'ListMyBookings()';
}

ListMyBookings $ListMyBookingsFromJson(Map<String, Object?> json) =>
    const ListMyBookings();

mixin _$BookSession on DwActionCommand<SessionBooking> {
  BookSession get _self => this as BookSession;

  @override
  String get dwTypeName => 'BookSession';

  @override
  Map<String, Object?> toJson() => {'sessionId': _self.sessionId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSession && other.sessionId == _self.sessionId;

  @override
  int get hashCode => Object.hash(BookSession, _self.sessionId);
}

BookSession $BookSessionFromJson(Map<String, Object?> json) =>
    BookSession(sessionId: json['sessionId']! as int);

mixin _$CancelBooking on DwActionCommand<SessionBooking> {
  CancelBooking get _self => this as CancelBooking;

  @override
  String get dwTypeName => 'CancelBooking';

  @override
  Map<String, Object?> toJson() => {'bookingId': _self.bookingId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CancelBooking && other.bookingId == _self.bookingId;

  @override
  int get hashCode => Object.hash(CancelBooking, _self.bookingId);
}

CancelBooking $CancelBookingFromJson(Map<String, Object?> json) =>
    CancelBooking(bookingId: json['bookingId']! as int);

mixin _$MarkAttended on DwActionCommand<SessionBooking> {
  MarkAttended get _self => this as MarkAttended;

  @override
  String get dwTypeName => 'MarkAttended';

  @override
  Map<String, Object?> toJson() => {'bookingId': _self.bookingId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarkAttended && other.bookingId == _self.bookingId;

  @override
  int get hashCode => Object.hash(MarkAttended, _self.bookingId);
}

MarkAttended $MarkAttendedFromJson(Map<String, Object?> json) =>
    MarkAttended(bookingId: json['bookingId']! as int);

mixin _$ReviewVisit on DwActionCommand<SessionBooking> {
  ReviewVisit get _self => this as ReviewVisit;

  @override
  String get dwTypeName => 'ReviewVisit';

  @override
  Map<String, Object?> toJson() => {
    'bookingId': _self.bookingId,
    'rating': _self.rating,
    if (_self.text != null) 'text': _self.text,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewVisit &&
          other.bookingId == _self.bookingId &&
          other.rating == _self.rating &&
          other.text == _self.text;

  @override
  int get hashCode =>
      Object.hash(ReviewVisit, _self.bookingId, _self.rating, _self.text);
}

ReviewVisit $ReviewVisitFromJson(Map<String, Object?> json) => ReviewVisit(
  bookingId: json['bookingId']! as int,
  rating: json['rating']! as int,
  text: json['text'] as String?,
);
