// GENERATED BY dartway generate. DO NOT EDIT.
part of 'bookings.dart';

mixin _$ReviewView on DwDataObject {
  ReviewView get _self => this as ReviewView;

  @override
  String get dwTypeName => 'ReviewView';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'rating': _self.rating,
    if (_self.text != null) 'text': _self.text,
    'createdAt': DwJson.encodeDateTime(_self.createdAt),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewView &&
          other.id == _self.id &&
          other.rating == _self.rating &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode =>
      Object.hash(_self.id, _self.rating, _self.text, _self.createdAt);

  @override
  String toString() =>
      'ReviewView(id: ${_self.id}, rating: ${_self.rating}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

ReviewView $ReviewViewFromJson(Map<String, Object?> json) => ReviewView(
  id: json['id']! as int,
  rating: json['rating']! as int,
  text: json['text'] as String?,
  createdAt: DwJson.decodeDateTime(json['createdAt']),
);

extension ReviewViewCopyWith on ReviewView {
  ReviewView copyWith({
    int? id,
    int? rating,
    DwPatch<String> text = const DwPatch.keep(),
    DateTime? createdAt,
  }) => ReviewView(
    id: id ?? this.id,
    rating: rating ?? this.rating,
    text: text.apply(this.text),
    createdAt: createdAt ?? this.createdAt,
  );
}

mixin _$BookingView on DwDataObject {
  BookingView get _self => this as BookingView;

  @override
  String get dwTypeName => 'BookingView';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'session': _self.session.toJson(),
    'status': _self.status.name,
    'createdAt': DwJson.encodeDateTime(_self.createdAt),
    if (_self.review != null) 'review': _self.review!.toJson(),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookingView &&
          other.id == _self.id &&
          other.session == _self.session &&
          other.status == _self.status &&
          other.createdAt == _self.createdAt &&
          other.review == _self.review;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.session,
    _self.status,
    _self.createdAt,
    _self.review,
  );

  @override
  String toString() =>
      'BookingView(id: ${_self.id}, session: ${_self.session}, status: ${_self.status}, createdAt: ${_self.createdAt}, review: ${_self.review})';
}

BookingView $BookingViewFromJson(Map<String, Object?> json) => BookingView(
  id: json['id']! as int,
  session: $ClubSessionViewFromJson(json['session']! as Map<String, Object?>),
  status: DwJson.decodeEnum(json['status'], BookingStatus.values),
  createdAt: DwJson.decodeDateTime(json['createdAt']),
  review: json['review'] == null
      ? null
      : $ReviewViewFromJson(json['review']! as Map<String, Object?>),
);

extension BookingViewCopyWith on BookingView {
  BookingView copyWith({
    int? id,
    ClubSessionView? session,
    BookingStatus? status,
    DateTime? createdAt,
    DwPatch<ReviewView> review = const DwPatch.keep(),
  }) => BookingView(
    id: id ?? this.id,
    session: session ?? this.session,
    status: status ?? this.status,
    createdAt: createdAt ?? this.createdAt,
    review: review.apply(this.review),
  );
}

mixin _$ListMyBookings on DwListRequest<BookingView> {
  ListMyBookings get _self => this as ListMyBookings;

  @override
  String get dwTypeName => 'ListMyBookings';

  @override
  Map<String, Object?> toJson() => {'profileId': _self.profileId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListMyBookings && other.profileId == _self.profileId;

  @override
  int get hashCode => Object.hash(ListMyBookings, _self.profileId);

  @override
  String toString() => 'ListMyBookings(profileId: ${_self.profileId})';
}

ListMyBookings $ListMyBookingsFromJson(Map<String, Object?> json) =>
    ListMyBookings(profileId: json['profileId']! as int);

mixin _$BookSession on DwCommand<BookingView> {
  BookSession get _self => this as BookSession;

  @override
  String get dwTypeName => 'BookSession';

  @override
  Map<String, Object?> toJson() => {'sessionId': _self.sessionId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSession && other.sessionId == _self.sessionId;

  @override
  int get hashCode => Object.hash(BookSession, _self.sessionId);
}

BookSession $BookSessionFromJson(Map<String, Object?> json) =>
    BookSession(sessionId: json['sessionId']! as int);

mixin _$CancelBooking on DwCommand<BookingView> {
  CancelBooking get _self => this as CancelBooking;

  @override
  String get dwTypeName => 'CancelBooking';

  @override
  Map<String, Object?> toJson() => {'bookingId': _self.bookingId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CancelBooking && other.bookingId == _self.bookingId;

  @override
  int get hashCode => Object.hash(CancelBooking, _self.bookingId);
}

CancelBooking $CancelBookingFromJson(Map<String, Object?> json) =>
    CancelBooking(bookingId: json['bookingId']! as int);

mixin _$MarkAttended on DwCommand<BookingView> {
  MarkAttended get _self => this as MarkAttended;

  @override
  String get dwTypeName => 'MarkAttended';

  @override
  Map<String, Object?> toJson() => {'bookingId': _self.bookingId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarkAttended && other.bookingId == _self.bookingId;

  @override
  int get hashCode => Object.hash(MarkAttended, _self.bookingId);
}

MarkAttended $MarkAttendedFromJson(Map<String, Object?> json) =>
    MarkAttended(bookingId: json['bookingId']! as int);

mixin _$ReviewVisit on DwCommand<BookingView> {
  ReviewVisit get _self => this as ReviewVisit;

  @override
  String get dwTypeName => 'ReviewVisit';

  @override
  Map<String, Object?> toJson() => {
    'bookingId': _self.bookingId,
    'rating': _self.rating,
    if (_self.text != null) 'text': _self.text,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewVisit &&
          other.bookingId == _self.bookingId &&
          other.rating == _self.rating &&
          other.text == _self.text;

  @override
  int get hashCode =>
      Object.hash(ReviewVisit, _self.bookingId, _self.rating, _self.text);
}

ReviewVisit $ReviewVisitFromJson(Map<String, Object?> json) => ReviewVisit(
  bookingId: json['bookingId']! as int,
  rating: json['rating']! as int,
  text: json['text'] as String?,
);
