// GENERATED BY dartway generate. DO NOT EDIT.
part of 'chat.dart';

mixin _$ChatChannelView on DwDataObject {
  ChatChannelView get _self => this as ChatChannelView;

  @override
  String get dwTypeName => 'ChatChannelView';

  @override
  Map<String, Object?> toJson() => {'id': _self.id, 'title': _self.title};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChannelView &&
          other.id == _self.id &&
          other.title == _self.title;

  @override
  int get hashCode => Object.hash(_self.id, _self.title);

  @override
  String toString() =>
      'ChatChannelView(id: ${_self.id}, title: ${_self.title})';
}

ChatChannelView $ChatChannelViewFromJson(Map<String, Object?> json) =>
    ChatChannelView(id: json['id']! as int, title: json['title']! as String);

extension ChatChannelViewCopyWith on ChatChannelView {
  ChatChannelView copyWith({int? id, String? title}) =>
      ChatChannelView(id: id ?? this.id, title: title ?? this.title);
}

mixin _$ChatMessageView on DwDataObject {
  ChatMessageView get _self => this as ChatMessageView;

  @override
  String get dwTypeName => 'ChatMessageView';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'channelId': _self.channelId,
    'text': _self.text,
    'author': _self.author.toJson(),
    'createdAt': DwJson.encodeDateTime(_self.createdAt),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageView &&
          other.id == _self.id &&
          other.channelId == _self.channelId &&
          other.text == _self.text &&
          other.author == _self.author &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.channelId,
    _self.text,
    _self.author,
    _self.createdAt,
  );

  @override
  String toString() =>
      'ChatMessageView(id: ${_self.id}, channelId: ${_self.channelId}, text: ${_self.text}, author: ${_self.author}, createdAt: ${_self.createdAt})';
}

ChatMessageView $ChatMessageViewFromJson(Map<String, Object?> json) =>
    ChatMessageView(
      id: json['id']! as int,
      channelId: json['channelId']! as int,
      text: json['text']! as String,
      author: $PersonViewFromJson(json['author']! as Map<String, Object?>),
      createdAt: DwJson.decodeDateTime(json['createdAt']),
    );

extension ChatMessageViewCopyWith on ChatMessageView {
  ChatMessageView copyWith({
    int? id,
    int? channelId,
    String? text,
    PersonView? author,
    DateTime? createdAt,
  }) => ChatMessageView(
    id: id ?? this.id,
    channelId: channelId ?? this.channelId,
    text: text ?? this.text,
    author: author ?? this.author,
    createdAt: createdAt ?? this.createdAt,
  );
}

mixin _$ListChatChannels on DwListRequest<ChatChannelView> {
  @override
  String get dwTypeName => 'ListChatChannels';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is ListChatChannels;

  @override
  int get hashCode => (ListChatChannels).hashCode;

  @override
  String toString() => 'ListChatChannels()';
}

ListChatChannels $ListChatChannelsFromJson(Map<String, Object?> json) =>
    const ListChatChannels();

mixin _$ListChatMessages on DwCursorRequest<ChatMessageView> {
  ListChatMessages get _self => this as ListChatMessages;

  @override
  String get dwTypeName => 'ListChatMessages';

  @override
  Map<String, Object?> toJson() => {'channelId': _self.channelId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListChatMessages && other.channelId == _self.channelId;

  @override
  int get hashCode => Object.hash(ListChatMessages, _self.channelId);

  @override
  String toString() => 'ListChatMessages(channelId: ${_self.channelId})';
}

ListChatMessages $ListChatMessagesFromJson(Map<String, Object?> json) =>
    ListChatMessages(channelId: json['channelId']! as int);

mixin _$SendChatMessage on DwCommand<ChatMessageView> {
  SendChatMessage get _self => this as SendChatMessage;

  @override
  String get dwTypeName => 'SendChatMessage';

  @override
  Map<String, Object?> toJson() => {
    'channelId': _self.channelId,
    'text': _self.text,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendChatMessage &&
          other.channelId == _self.channelId &&
          other.text == _self.text;

  @override
  int get hashCode => Object.hash(SendChatMessage, _self.channelId, _self.text);
}

SendChatMessage $SendChatMessageFromJson(Map<String, Object?> json) =>
    SendChatMessage(
      channelId: json['channelId']! as int,
      text: json['text']! as String,
    );
