// GENERATED BY dartway generate. DO NOT EDIT.
part of 'chat.dart';

mixin _$ChatChannel on DwDataObject {
  ChatChannel get _self => this as ChatChannel;

  @override
  String get dwTypeName => 'ChatChannel';

  @override
  Map<String, Object?> toJson() => {'id': _self.id, 'title': _self.title};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChannel &&
          other.id == _self.id &&
          other.title == _self.title;

  @override
  int get hashCode => Object.hash(_self.id, _self.title);

  @override
  String toString() => 'ChatChannel(id: ${_self.id}, title: ${_self.title})';
}

ChatChannel $ChatChannelFromJson(Map<String, Object?> json) =>
    ChatChannel(id: json['id']! as int, title: json['title']! as String);

extension ChatChannelCopyWith on ChatChannel {
  ChatChannel copyWith({int? id, String? title}) =>
      ChatChannel(id: id ?? this.id, title: title ?? this.title);
}

mixin _$ChatMessage on DwDataObject {
  ChatMessage get _self => this as ChatMessage;

  @override
  String get dwTypeName => 'ChatMessage';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'channelId': _self.channelId,
    'text': _self.text,
    'author': _self.author.toJson(),
    'createdAt': DwJsonCodec.encodeDateTime(_self.createdAt),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          other.id == _self.id &&
          other.channelId == _self.channelId &&
          other.text == _self.text &&
          other.author == _self.author &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.channelId,
    _self.text,
    _self.author,
    _self.createdAt,
  );

  @override
  String toString() =>
      'ChatMessage(id: ${_self.id}, channelId: ${_self.channelId}, text: ${_self.text}, author: ${_self.author}, createdAt: ${_self.createdAt})';
}

ChatMessage $ChatMessageFromJson(Map<String, Object?> json) => ChatMessage(
  id: json['id']! as int,
  channelId: json['channelId']! as int,
  text: json['text']! as String,
  author: $PersonCardFromJson(json['author']! as Map<String, Object?>),
  createdAt: DwJsonCodec.decodeDateTime(json['createdAt']),
);

extension ChatMessageCopyWith on ChatMessage {
  ChatMessage copyWith({
    int? id,
    int? channelId,
    String? text,
    PersonCard? author,
    DateTime? createdAt,
  }) => ChatMessage(
    id: id ?? this.id,
    channelId: channelId ?? this.channelId,
    text: text ?? this.text,
    author: author ?? this.author,
    createdAt: createdAt ?? this.createdAt,
  );
}

mixin _$ListChatChannels on DwListRequest<ChatChannel> {
  @override
  String get dwTypeName => 'ListChatChannels';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is ListChatChannels;

  @override
  int get hashCode => (ListChatChannels).hashCode;

  @override
  String toString() => 'ListChatChannels()';
}

ListChatChannels $ListChatChannelsFromJson(Map<String, Object?> json) =>
    const ListChatChannels();

mixin _$ListChatMessages on DwWindowRequest<ChatMessage, DateTime, int> {
  ListChatMessages get _self => this as ListChatMessages;

  @override
  String get dwTypeName => 'ListChatMessages';

  @override
  Map<String, Object?> toJson() => {'channelId': _self.channelId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListChatMessages && other.channelId == _self.channelId;

  @override
  int get hashCode => Object.hash(ListChatMessages, _self.channelId);

  @override
  String toString() => 'ListChatMessages(channelId: ${_self.channelId})';
}

ListChatMessages $ListChatMessagesFromJson(Map<String, Object?> json) =>
    ListChatMessages(channelId: json['channelId']! as int);

mixin _$SendChatMessage on DwActionCommand<ChatMessage> {
  SendChatMessage get _self => this as SendChatMessage;

  @override
  String get dwTypeName => 'SendChatMessage';

  @override
  Map<String, Object?> toJson() => {
    'channelId': _self.channelId,
    'text': _self.text,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendChatMessage &&
          other.channelId == _self.channelId &&
          other.text == _self.text;

  @override
  int get hashCode => Object.hash(SendChatMessage, _self.channelId, _self.text);
}

SendChatMessage $SendChatMessageFromJson(Map<String, Object?> json) =>
    SendChatMessage(
      channelId: json['channelId']! as int,
      text: json['text']! as String,
    );
