// GENERATED BY dartway generate. DO NOT EDIT.
part of 'news.dart';

mixin _$NewsPost on DwDataObject {
  NewsPost get _self => this as NewsPost;

  @override
  String get dwTypeName => 'NewsPost';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'title': _self.title,
    'text': _self.text,
    'author': _self.author.toJson(),
    'createdAt': DwJsonCodec.encodeDateTime(_self.createdAt),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewsPost &&
          other.id == _self.id &&
          other.title == _self.title &&
          other.text == _self.text &&
          other.author == _self.author &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.title,
    _self.text,
    _self.author,
    _self.createdAt,
  );

  @override
  String toString() =>
      'NewsPost(id: ${_self.id}, title: ${_self.title}, text: ${_self.text}, author: ${_self.author}, createdAt: ${_self.createdAt})';
}

NewsPost $NewsPostFromJson(Map<String, Object?> json) => NewsPost(
  id: json['id']! as int,
  title: json['title']! as String,
  text: json['text']! as String,
  author: $PersonCardFromJson(json['author']! as Map<String, Object?>),
  createdAt: DwJsonCodec.decodeDateTime(json['createdAt']),
);

extension NewsPostCopyWith on NewsPost {
  NewsPost copyWith({
    int? id,
    String? title,
    String? text,
    PersonCard? author,
    DateTime? createdAt,
  }) => NewsPost(
    id: id ?? this.id,
    title: title ?? this.title,
    text: text ?? this.text,
    author: author ?? this.author,
    createdAt: createdAt ?? this.createdAt,
  );
}

mixin _$ListNews on DwListRequest<NewsPost> {
  @override
  String get dwTypeName => 'ListNews';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) => identical(this, other) || other is ListNews;

  @override
  int get hashCode => (ListNews).hashCode;

  @override
  String toString() => 'ListNews()';
}

ListNews $ListNewsFromJson(Map<String, Object?> json) => const ListNews();

mixin _$PublishNews on DwActionCommand<NewsPost> {
  PublishNews get _self => this as PublishNews;

  @override
  String get dwTypeName => 'PublishNews';

  @override
  Map<String, Object?> toJson() => {'title': _self.title, 'text': _self.text};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublishNews &&
          other.title == _self.title &&
          other.text == _self.text;

  @override
  int get hashCode => Object.hash(PublishNews, _self.title, _self.text);
}

PublishNews $PublishNewsFromJson(Map<String, Object?> json) =>
    PublishNews(title: json['title']! as String, text: json['text']! as String);

mixin _$NewsAlert on DwDataObject {
  NewsAlert get _self => this as NewsAlert;

  @override
  String get dwTypeName => 'NewsAlert';

  @override
  Map<String, Object?> toJson() => {'id': _self.id};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is NewsAlert && other.id == _self.id;

  @override
  int get hashCode => _self.id.hashCode;

  @override
  String toString() => 'NewsAlert(id: ${_self.id})';
}

NewsAlert $NewsAlertFromJson(Map<String, Object?> json) =>
    NewsAlert(id: json['id']! as int);

extension NewsAlertCopyWith on NewsAlert {
  NewsAlert copyWith({int? id}) => NewsAlert(id: id ?? this.id);
}

mixin _$RemoveNews on DwActionCommand<void> {
  RemoveNews get _self => this as RemoveNews;

  @override
  String get dwTypeName => 'RemoveNews';

  @override
  Map<String, Object?> toJson() => {'postId': _self.postId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoveNews && other.postId == _self.postId;

  @override
  int get hashCode => Object.hash(RemoveNews, _self.postId);
}

RemoveNews $RemoveNewsFromJson(Map<String, Object?> json) =>
    RemoveNews(postId: json['postId']! as int);
