// GENERATED BY dartway generate. DO NOT EDIT.
part of 'people.dart';

mixin _$PersonCard on DwDataObject {
  PersonCard get _self => this as PersonCard;

  @override
  String get dwTypeName => 'PersonCard';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'firstName': _self.firstName,
    if (_self.lastName != null) 'lastName': _self.lastName,
    if (_self.imageUrl != null) 'imageUrl': _self.imageUrl,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonCard &&
          other.id == _self.id &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode =>
      Object.hash(_self.id, _self.firstName, _self.lastName, _self.imageUrl);

  @override
  String toString() =>
      'PersonCard(id: ${_self.id}, firstName: ${_self.firstName}, lastName: ${_self.lastName}, imageUrl: ${_self.imageUrl})';
}

PersonCard $PersonCardFromJson(Map<String, Object?> json) => PersonCard(
  id: json['id']! as int,
  firstName: json['firstName']! as String,
  lastName: json['lastName'] as String?,
  imageUrl: json['imageUrl'] as String?,
);

extension PersonCardCopyWith on PersonCard {
  PersonCard copyWith({
    int? id,
    String? firstName,
    DwFieldPatch<String> lastName = const DwFieldPatch.keep(),
    DwFieldPatch<String> imageUrl = const DwFieldPatch.keep(),
  }) => PersonCard(
    id: id ?? this.id,
    firstName: firstName ?? this.firstName,
    lastName: lastName.apply(this.lastName),
    imageUrl: imageUrl.apply(this.imageUrl),
  );
}

mixin _$UserProfile on DwDataObject {
  UserProfile get _self => this as UserProfile;

  @override
  String get dwTypeName => 'UserProfile';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'accountId': _self.accountId,
    'phone': _self.phone,
    'firstName': _self.firstName,
    if (_self.lastName != null) 'lastName': _self.lastName,
    if (_self.imageUrl != null) 'imageUrl': _self.imageUrl,
    if (_self.gender != null) 'gender': _self.gender!.name,
    'role': _self.role.name,
    'agreedForMarketing': _self.agreedForMarketing,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          other.id == _self.id &&
          other.accountId == _self.accountId &&
          other.phone == _self.phone &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.imageUrl == _self.imageUrl &&
          other.gender == _self.gender &&
          other.role == _self.role &&
          other.agreedForMarketing == _self.agreedForMarketing;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.accountId,
    _self.phone,
    _self.firstName,
    _self.lastName,
    _self.imageUrl,
    _self.gender,
    _self.role,
    _self.agreedForMarketing,
  );

  @override
  String toString() =>
      'UserProfile(id: ${_self.id}, accountId: ${_self.accountId}, phone: ${_self.phone}, firstName: ${_self.firstName}, lastName: ${_self.lastName}, imageUrl: ${_self.imageUrl}, gender: ${_self.gender}, role: ${_self.role}, agreedForMarketing: ${_self.agreedForMarketing})';
}

UserProfile $UserProfileFromJson(Map<String, Object?> json) => UserProfile(
  id: json['id']! as int,
  accountId: json['accountId']! as int,
  phone: json['phone']! as String,
  firstName: json['firstName']! as String,
  lastName: json['lastName'] as String?,
  imageUrl: json['imageUrl'] as String?,
  gender: json['gender'] == null
      ? null
      : DwJsonCodec.decodeEnum(json['gender'], UserGender.values),
  role: DwJsonCodec.decodeEnum(json['role'], UserRole.values),
  agreedForMarketing: json['agreedForMarketing']! as bool,
);

extension UserProfileCopyWith on UserProfile {
  UserProfile copyWith({
    int? id,
    int? accountId,
    String? phone,
    String? firstName,
    DwFieldPatch<String> lastName = const DwFieldPatch.keep(),
    DwFieldPatch<String> imageUrl = const DwFieldPatch.keep(),
    DwFieldPatch<UserGender> gender = const DwFieldPatch.keep(),
    UserRole? role,
    bool? agreedForMarketing,
  }) => UserProfile(
    id: id ?? this.id,
    accountId: accountId ?? this.accountId,
    phone: phone ?? this.phone,
    firstName: firstName ?? this.firstName,
    lastName: lastName.apply(this.lastName),
    imageUrl: imageUrl.apply(this.imageUrl),
    gender: gender.apply(this.gender),
    role: role ?? this.role,
    agreedForMarketing: agreedForMarketing ?? this.agreedForMarketing,
  );
}

mixin _$GetMyProfile on DwSingleRequest<UserProfile> {
  @override
  String get dwTypeName => 'GetMyProfile';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is GetMyProfile;

  @override
  int get hashCode => (GetMyProfile).hashCode;

  @override
  String toString() => 'GetMyProfile()';
}

GetMyProfile $GetMyProfileFromJson(Map<String, Object?> json) =>
    const GetMyProfile();

mixin _$UpdateMyProfile on DwActionCommand<UserProfile> {
  UpdateMyProfile get _self => this as UpdateMyProfile;

  @override
  String get dwTypeName => 'UpdateMyProfile';

  @override
  Map<String, Object?> toJson() {
    final json = <String, Object?>{
      if (_self.firstName != null) 'firstName': _self.firstName,
    };
    DwJsonCodec.writePatch(json, 'lastName', _self.lastName, (v) => v);
    DwJsonCodec.writePatch(json, 'gender', _self.gender, (v) => v.name);
    DwJsonCodec.writePatch(json, 'imageUrl', _self.imageUrl, (v) => v);
    return json;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateMyProfile &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.gender == _self.gender &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode => Object.hash(
    UpdateMyProfile,
    _self.firstName,
    _self.lastName,
    _self.gender,
    _self.imageUrl,
  );
}

UpdateMyProfile $UpdateMyProfileFromJson(Map<String, Object?> json) =>
    UpdateMyProfile(
      firstName: json['firstName'] as String?,
      lastName: DwJsonCodec.readPatch(json, 'lastName', (v) => v! as String),
      gender: DwJsonCodec.readPatch(
        json,
        'gender',
        (v) => DwJsonCodec.decodeEnum(v, UserGender.values),
      ),
      imageUrl: DwJsonCodec.readPatch(json, 'imageUrl', (v) => v! as String),
    );
