// GENERATED BY dartway generate. DO NOT EDIT.
part of 'people.dart';

mixin _$PersonView on DwDataObject {
  PersonView get _self => this as PersonView;

  @override
  String get dwTypeName => 'PersonView';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'firstName': _self.firstName,
    if (_self.lastName != null) 'lastName': _self.lastName,
    if (_self.imageUrl != null) 'imageUrl': _self.imageUrl,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonView &&
          other.id == _self.id &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode =>
      Object.hash(_self.id, _self.firstName, _self.lastName, _self.imageUrl);

  @override
  String toString() =>
      'PersonView(id: ${_self.id}, firstName: ${_self.firstName}, lastName: ${_self.lastName}, imageUrl: ${_self.imageUrl})';
}

PersonView $PersonViewFromJson(Map<String, Object?> json) => PersonView(
  id: json['id']! as int,
  firstName: json['firstName']! as String,
  lastName: json['lastName'] as String?,
  imageUrl: json['imageUrl'] as String?,
);

extension PersonViewCopyWith on PersonView {
  PersonView copyWith({
    int? id,
    String? firstName,
    DwPatch<String> lastName = const DwPatch.keep(),
    DwPatch<String> imageUrl = const DwPatch.keep(),
  }) => PersonView(
    id: id ?? this.id,
    firstName: firstName ?? this.firstName,
    lastName: lastName.apply(this.lastName),
    imageUrl: imageUrl.apply(this.imageUrl),
  );
}

mixin _$ProfileView on DwDataObject {
  ProfileView get _self => this as ProfileView;

  @override
  String get dwTypeName => 'ProfileView';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'phone': _self.phone,
    'firstName': _self.firstName,
    if (_self.lastName != null) 'lastName': _self.lastName,
    if (_self.imageUrl != null) 'imageUrl': _self.imageUrl,
    if (_self.gender != null) 'gender': _self.gender!.name,
    'role': _self.role.name,
    'agreedForMarketing': _self.agreedForMarketing,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileView &&
          other.id == _self.id &&
          other.phone == _self.phone &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.imageUrl == _self.imageUrl &&
          other.gender == _self.gender &&
          other.role == _self.role &&
          other.agreedForMarketing == _self.agreedForMarketing;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.phone,
    _self.firstName,
    _self.lastName,
    _self.imageUrl,
    _self.gender,
    _self.role,
    _self.agreedForMarketing,
  );

  @override
  String toString() =>
      'ProfileView(id: ${_self.id}, phone: ${_self.phone}, firstName: ${_self.firstName}, lastName: ${_self.lastName}, imageUrl: ${_self.imageUrl}, gender: ${_self.gender}, role: ${_self.role}, agreedForMarketing: ${_self.agreedForMarketing})';
}

ProfileView $ProfileViewFromJson(Map<String, Object?> json) => ProfileView(
  id: json['id']! as int,
  phone: json['phone']! as String,
  firstName: json['firstName']! as String,
  lastName: json['lastName'] as String?,
  imageUrl: json['imageUrl'] as String?,
  gender: json['gender'] == null
      ? null
      : DwJson.decodeEnum(json['gender'], UserGender.values),
  role: DwJson.decodeEnum(json['role'], UserRole.values),
  agreedForMarketing: json['agreedForMarketing']! as bool,
);

extension ProfileViewCopyWith on ProfileView {
  ProfileView copyWith({
    int? id,
    String? phone,
    String? firstName,
    DwPatch<String> lastName = const DwPatch.keep(),
    DwPatch<String> imageUrl = const DwPatch.keep(),
    DwPatch<UserGender> gender = const DwPatch.keep(),
    UserRole? role,
    bool? agreedForMarketing,
  }) => ProfileView(
    id: id ?? this.id,
    phone: phone ?? this.phone,
    firstName: firstName ?? this.firstName,
    lastName: lastName.apply(this.lastName),
    imageUrl: imageUrl.apply(this.imageUrl),
    gender: gender.apply(this.gender),
    role: role ?? this.role,
    agreedForMarketing: agreedForMarketing ?? this.agreedForMarketing,
  );
}

mixin _$GetMyProfile on DwMaybeRequest<ProfileView> {
  GetMyProfile get _self => this as GetMyProfile;

  @override
  String get dwTypeName => 'GetMyProfile';

  @override
  Map<String, Object?> toJson() => {'accountId': _self.accountId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GetMyProfile && other.accountId == _self.accountId;

  @override
  int get hashCode => Object.hash(GetMyProfile, _self.accountId);

  @override
  String toString() => 'GetMyProfile(accountId: ${_self.accountId})';
}

GetMyProfile $GetMyProfileFromJson(Map<String, Object?> json) =>
    GetMyProfile(accountId: json['accountId']! as int);

mixin _$UpdateMyProfile on DwCommand<ProfileView> {
  UpdateMyProfile get _self => this as UpdateMyProfile;

  @override
  String get dwTypeName => 'UpdateMyProfile';

  @override
  Map<String, Object?> toJson() {
    final json = <String, Object?>{
      if (_self.firstName != null) 'firstName': _self.firstName,
    };
    DwJson.writePatch(json, 'lastName', _self.lastName, (v) => v);
    DwJson.writePatch(json, 'gender', _self.gender, (v) => v.name);
    DwJson.writePatch(json, 'imageUrl', _self.imageUrl, (v) => v);
    return json;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateMyProfile &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.gender == _self.gender &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode => Object.hash(
    UpdateMyProfile,
    _self.firstName,
    _self.lastName,
    _self.gender,
    _self.imageUrl,
  );
}

UpdateMyProfile $UpdateMyProfileFromJson(Map<String, Object?> json) =>
    UpdateMyProfile(
      firstName: json['firstName'] as String?,
      lastName: DwJson.readPatch(json, 'lastName', (v) => v! as String),
      gender: DwJson.readPatch(
        json,
        'gender',
        (v) => DwJson.decodeEnum(v, UserGender.values),
      ),
      imageUrl: DwJson.readPatch(json, 'imageUrl', (v) => v! as String),
    );
