// GENERATED BY dartway generate. DO NOT EDIT.
part of 'schedule.dart';

mixin _$ClubService on DwDataObject {
  ClubService get _self => this as ClubService;

  @override
  String get dwTypeName => 'ClubService';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'title': _self.title,
    'description': _self.description,
    'durationMinutes': _self.durationMinutes,
    'price': _self.price,
    if (_self.imageUrl != null) 'imageUrl': _self.imageUrl,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubService &&
          other.id == _self.id &&
          other.title == _self.title &&
          other.description == _self.description &&
          other.durationMinutes == _self.durationMinutes &&
          other.price == _self.price &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.title,
    _self.description,
    _self.durationMinutes,
    _self.price,
    _self.imageUrl,
  );

  @override
  String toString() =>
      'ClubService(id: ${_self.id}, title: ${_self.title}, description: ${_self.description}, durationMinutes: ${_self.durationMinutes}, price: ${_self.price}, imageUrl: ${_self.imageUrl})';
}

ClubService $ClubServiceFromJson(Map<String, Object?> json) => ClubService(
  id: json['id']! as int,
  title: json['title']! as String,
  description: json['description']! as String,
  durationMinutes: json['durationMinutes']! as int,
  price: json['price']! as int,
  imageUrl: json['imageUrl'] as String?,
);

extension ClubServiceCopyWith on ClubService {
  ClubService copyWith({
    int? id,
    String? title,
    String? description,
    int? durationMinutes,
    int? price,
    DwFieldPatch<String> imageUrl = const DwFieldPatch.keep(),
  }) => ClubService(
    id: id ?? this.id,
    title: title ?? this.title,
    description: description ?? this.description,
    durationMinutes: durationMinutes ?? this.durationMinutes,
    price: price ?? this.price,
    imageUrl: imageUrl.apply(this.imageUrl),
  );
}

mixin _$ClubSession on DwDataObject {
  ClubSession get _self => this as ClubSession;

  @override
  String get dwTypeName => 'ClubSession';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'service': _self.service.toJson(),
    if (_self.coach != null) 'coach': _self.coach!.toJson(),
    'startsAt': DwJsonCodec.encodeDateTime(_self.startsAt),
    'capacity': _self.capacity,
    'bookedCount': _self.bookedCount,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubSession &&
          other.id == _self.id &&
          other.service == _self.service &&
          other.coach == _self.coach &&
          other.startsAt == _self.startsAt &&
          other.capacity == _self.capacity &&
          other.bookedCount == _self.bookedCount;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.service,
    _self.coach,
    _self.startsAt,
    _self.capacity,
    _self.bookedCount,
  );

  @override
  String toString() =>
      'ClubSession(id: ${_self.id}, service: ${_self.service}, coach: ${_self.coach}, startsAt: ${_self.startsAt}, capacity: ${_self.capacity}, bookedCount: ${_self.bookedCount})';
}

ClubSession $ClubSessionFromJson(Map<String, Object?> json) => ClubSession(
  id: json['id']! as int,
  service: $ClubServiceFromJson(json['service']! as Map<String, Object?>),
  coach: json['coach'] == null
      ? null
      : $PersonCardFromJson(json['coach']! as Map<String, Object?>),
  startsAt: DwJsonCodec.decodeDateTime(json['startsAt']),
  capacity: json['capacity']! as int,
  bookedCount: json['bookedCount']! as int,
);

extension ClubSessionCopyWith on ClubSession {
  ClubSession copyWith({
    int? id,
    ClubService? service,
    DwFieldPatch<PersonCard> coach = const DwFieldPatch.keep(),
    DateTime? startsAt,
    int? capacity,
    int? bookedCount,
  }) => ClubSession(
    id: id ?? this.id,
    service: service ?? this.service,
    coach: coach.apply(this.coach),
    startsAt: startsAt ?? this.startsAt,
    capacity: capacity ?? this.capacity,
    bookedCount: bookedCount ?? this.bookedCount,
  );
}

mixin _$ListClubServices on DwListRequest<ClubService> {
  @override
  String get dwTypeName => 'ListClubServices';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is ListClubServices;

  @override
  int get hashCode => (ListClubServices).hashCode;

  @override
  String toString() => 'ListClubServices()';
}

ListClubServices $ListClubServicesFromJson(Map<String, Object?> json) =>
    const ListClubServices();

mixin _$ListUpcomingSessions on DwListRequest<ClubSession> {
  ListUpcomingSessions get _self => this as ListUpcomingSessions;

  @override
  String get dwTypeName => 'ListUpcomingSessions';

  @override
  Map<String, Object?> toJson() => {
    'from': DwJsonCodec.encodeDateTime(_self.from),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListUpcomingSessions && other.from == _self.from;

  @override
  int get hashCode => Object.hash(ListUpcomingSessions, _self.from);

  @override
  String toString() => 'ListUpcomingSessions(from: ${_self.from})';
}

ListUpcomingSessions $ListUpcomingSessionsFromJson(Map<String, Object?> json) =>
    ListUpcomingSessions(from: DwJsonCodec.decodeDateTime(json['from']));

mixin _$SaveClubService on DwActionCommand<ClubService> {
  SaveClubService get _self => this as SaveClubService;

  @override
  String get dwTypeName => 'SaveClubService';

  @override
  Map<String, Object?> toJson() => {
    if (_self.id != null) 'id': _self.id,
    'title': _self.title,
    'description': _self.description,
    'durationMinutes': _self.durationMinutes,
    'price': _self.price,
    if (_self.imageUrl != null) 'imageUrl': _self.imageUrl,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveClubService &&
          other.id == _self.id &&
          other.title == _self.title &&
          other.description == _self.description &&
          other.durationMinutes == _self.durationMinutes &&
          other.price == _self.price &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode => Object.hash(
    SaveClubService,
    _self.id,
    _self.title,
    _self.description,
    _self.durationMinutes,
    _self.price,
    _self.imageUrl,
  );
}

SaveClubService $SaveClubServiceFromJson(Map<String, Object?> json) =>
    SaveClubService(
      id: json['id'] as int?,
      title: json['title']! as String,
      description: json['description']! as String,
      durationMinutes: json['durationMinutes']! as int,
      price: json['price']! as int,
      imageUrl: json['imageUrl'] as String?,
    );

mixin _$ScheduleSession on DwActionCommand<ClubSession> {
  ScheduleSession get _self => this as ScheduleSession;

  @override
  String get dwTypeName => 'ScheduleSession';

  @override
  Map<String, Object?> toJson() => {
    'serviceId': _self.serviceId,
    if (_self.coachProfileId != null) 'coachProfileId': _self.coachProfileId,
    'startsAt': DwJsonCodec.encodeDateTime(_self.startsAt),
    'capacity': _self.capacity,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScheduleSession &&
          other.serviceId == _self.serviceId &&
          other.coachProfileId == _self.coachProfileId &&
          other.startsAt == _self.startsAt &&
          other.capacity == _self.capacity;

  @override
  int get hashCode => Object.hash(
    ScheduleSession,
    _self.serviceId,
    _self.coachProfileId,
    _self.startsAt,
    _self.capacity,
  );
}

ScheduleSession $ScheduleSessionFromJson(Map<String, Object?> json) =>
    ScheduleSession(
      serviceId: json['serviceId']! as int,
      coachProfileId: json['coachProfileId'] as int?,
      startsAt: DwJsonCodec.decodeDateTime(json['startsAt']),
      capacity: json['capacity']! as int,
    );

mixin _$CancelSession on DwActionCommand<void> {
  CancelSession get _self => this as CancelSession;

  @override
  String get dwTypeName => 'CancelSession';

  @override
  Map<String, Object?> toJson() => {'sessionId': _self.sessionId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CancelSession && other.sessionId == _self.sessionId;

  @override
  int get hashCode => Object.hash(CancelSession, _self.sessionId);
}

CancelSession $CancelSessionFromJson(Map<String, Object?> json) =>
    CancelSession(sessionId: json['sessionId']! as int);
