// GENERATED BY dartway generate. DO NOT EDIT.
part of 'schedule.dart';

mixin _$ClubServiceView on DwDataObject {
  ClubServiceView get _self => this as ClubServiceView;

  @override
  String get dwTypeName => 'ClubServiceView';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'title': _self.title,
    'description': _self.description,
    'durationMinutes': _self.durationMinutes,
    'price': _self.price,
    if (_self.imageUrl != null) 'imageUrl': _self.imageUrl,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubServiceView &&
          other.id == _self.id &&
          other.title == _self.title &&
          other.description == _self.description &&
          other.durationMinutes == _self.durationMinutes &&
          other.price == _self.price &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.title,
    _self.description,
    _self.durationMinutes,
    _self.price,
    _self.imageUrl,
  );

  @override
  String toString() =>
      'ClubServiceView(id: ${_self.id}, title: ${_self.title}, description: ${_self.description}, durationMinutes: ${_self.durationMinutes}, price: ${_self.price}, imageUrl: ${_self.imageUrl})';
}

ClubServiceView $ClubServiceViewFromJson(Map<String, Object?> json) =>
    ClubServiceView(
      id: json['id']! as int,
      title: json['title']! as String,
      description: json['description']! as String,
      durationMinutes: json['durationMinutes']! as int,
      price: json['price']! as int,
      imageUrl: json['imageUrl'] as String?,
    );

extension ClubServiceViewCopyWith on ClubServiceView {
  ClubServiceView copyWith({
    int? id,
    String? title,
    String? description,
    int? durationMinutes,
    int? price,
    DwPatch<String> imageUrl = const DwPatch.keep(),
  }) => ClubServiceView(
    id: id ?? this.id,
    title: title ?? this.title,
    description: description ?? this.description,
    durationMinutes: durationMinutes ?? this.durationMinutes,
    price: price ?? this.price,
    imageUrl: imageUrl.apply(this.imageUrl),
  );
}

mixin _$ClubSessionView on DwDataObject {
  ClubSessionView get _self => this as ClubSessionView;

  @override
  String get dwTypeName => 'ClubSessionView';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'service': _self.service.toJson(),
    if (_self.coach != null) 'coach': _self.coach!.toJson(),
    'startsAt': DwJson.encodeDateTime(_self.startsAt),
    'capacity': _self.capacity,
    'bookedCount': _self.bookedCount,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubSessionView &&
          other.id == _self.id &&
          other.service == _self.service &&
          other.coach == _self.coach &&
          other.startsAt == _self.startsAt &&
          other.capacity == _self.capacity &&
          other.bookedCount == _self.bookedCount;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.service,
    _self.coach,
    _self.startsAt,
    _self.capacity,
    _self.bookedCount,
  );

  @override
  String toString() =>
      'ClubSessionView(id: ${_self.id}, service: ${_self.service}, coach: ${_self.coach}, startsAt: ${_self.startsAt}, capacity: ${_self.capacity}, bookedCount: ${_self.bookedCount})';
}

ClubSessionView $ClubSessionViewFromJson(Map<String, Object?> json) =>
    ClubSessionView(
      id: json['id']! as int,
      service: $ClubServiceViewFromJson(
        json['service']! as Map<String, Object?>,
      ),
      coach: json['coach'] == null
          ? null
          : $PersonViewFromJson(json['coach']! as Map<String, Object?>),
      startsAt: DwJson.decodeDateTime(json['startsAt']),
      capacity: json['capacity']! as int,
      bookedCount: json['bookedCount']! as int,
    );

extension ClubSessionViewCopyWith on ClubSessionView {
  ClubSessionView copyWith({
    int? id,
    ClubServiceView? service,
    DwPatch<PersonView> coach = const DwPatch.keep(),
    DateTime? startsAt,
    int? capacity,
    int? bookedCount,
  }) => ClubSessionView(
    id: id ?? this.id,
    service: service ?? this.service,
    coach: coach.apply(this.coach),
    startsAt: startsAt ?? this.startsAt,
    capacity: capacity ?? this.capacity,
    bookedCount: bookedCount ?? this.bookedCount,
  );
}

mixin _$ListClubServices on DwListRequest<ClubServiceView> {
  @override
  String get dwTypeName => 'ListClubServices';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is ListClubServices;

  @override
  int get hashCode => (ListClubServices).hashCode;

  @override
  String toString() => 'ListClubServices()';
}

ListClubServices $ListClubServicesFromJson(Map<String, Object?> json) =>
    const ListClubServices();

mixin _$ListUpcomingSessions on DwListRequest<ClubSessionView> {
  ListUpcomingSessions get _self => this as ListUpcomingSessions;

  @override
  String get dwTypeName => 'ListUpcomingSessions';

  @override
  Map<String, Object?> toJson() => {'from': DwJson.encodeDateTime(_self.from)};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListUpcomingSessions && other.from == _self.from;

  @override
  int get hashCode => Object.hash(ListUpcomingSessions, _self.from);

  @override
  String toString() => 'ListUpcomingSessions(from: ${_self.from})';
}

ListUpcomingSessions $ListUpcomingSessionsFromJson(Map<String, Object?> json) =>
    ListUpcomingSessions(from: DwJson.decodeDateTime(json['from']));

mixin _$SaveClubService on DwCommand<ClubServiceView> {
  SaveClubService get _self => this as SaveClubService;

  @override
  String get dwTypeName => 'SaveClubService';

  @override
  Map<String, Object?> toJson() => {
    if (_self.id != null) 'id': _self.id,
    'title': _self.title,
    'description': _self.description,
    'durationMinutes': _self.durationMinutes,
    'price': _self.price,
    if (_self.imageUrl != null) 'imageUrl': _self.imageUrl,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveClubService &&
          other.id == _self.id &&
          other.title == _self.title &&
          other.description == _self.description &&
          other.durationMinutes == _self.durationMinutes &&
          other.price == _self.price &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode => Object.hash(
    SaveClubService,
    _self.id,
    _self.title,
    _self.description,
    _self.durationMinutes,
    _self.price,
    _self.imageUrl,
  );
}

SaveClubService $SaveClubServiceFromJson(Map<String, Object?> json) =>
    SaveClubService(
      id: json['id'] as int?,
      title: json['title']! as String,
      description: json['description']! as String,
      durationMinutes: json['durationMinutes']! as int,
      price: json['price']! as int,
      imageUrl: json['imageUrl'] as String?,
    );

mixin _$ScheduleSession on DwCommand<ClubSessionView> {
  ScheduleSession get _self => this as ScheduleSession;

  @override
  String get dwTypeName => 'ScheduleSession';

  @override
  Map<String, Object?> toJson() => {
    'serviceId': _self.serviceId,
    if (_self.coachProfileId != null) 'coachProfileId': _self.coachProfileId,
    'startsAt': DwJson.encodeDateTime(_self.startsAt),
    'capacity': _self.capacity,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScheduleSession &&
          other.serviceId == _self.serviceId &&
          other.coachProfileId == _self.coachProfileId &&
          other.startsAt == _self.startsAt &&
          other.capacity == _self.capacity;

  @override
  int get hashCode => Object.hash(
    ScheduleSession,
    _self.serviceId,
    _self.coachProfileId,
    _self.startsAt,
    _self.capacity,
  );
}

ScheduleSession $ScheduleSessionFromJson(Map<String, Object?> json) =>
    ScheduleSession(
      serviceId: json['serviceId']! as int,
      coachProfileId: json['coachProfileId'] as int?,
      startsAt: DwJson.decodeDateTime(json['startsAt']),
      capacity: json['capacity']! as int,
    );

mixin _$CancelSession on DwCommand<void> {
  CancelSession get _self => this as CancelSession;

  @override
  String get dwTypeName => 'CancelSession';

  @override
  Map<String, Object?> toJson() => {'sessionId': _self.sessionId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CancelSession && other.sessionId == _self.sessionId;

  @override
  int get hashCode => Object.hash(CancelSession, _self.sessionId);
}

CancelSession $CancelSessionFromJson(Map<String, Object?> json) =>
    CancelSession(sessionId: json['sessionId']! as int);
