// GENERATED BY dartway generate. DO NOT EDIT.
part of 'settings.dart';

mixin _$AppSettingView on DwDataObject {
  AppSettingView get _self => this as AppSettingView;

  @override
  String get dwTypeName => 'AppSettingView';

  @override
  Map<String, Object?> toJson() => {'id': _self.id, 'value': _self.value};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettingView &&
          other.id == _self.id &&
          other.value == _self.value;

  @override
  int get hashCode => Object.hash(_self.id, _self.value);

  @override
  String toString() => 'AppSettingView(id: ${_self.id}, value: ${_self.value})';
}

AppSettingView $AppSettingViewFromJson(Map<String, Object?> json) =>
    AppSettingView(id: json['id']! as String, value: json['value']! as String);

extension AppSettingViewCopyWith on AppSettingView {
  AppSettingView copyWith({String? id, String? value}) =>
      AppSettingView(id: id ?? this.id, value: value ?? this.value);
}

mixin _$ListAppSettings on DwListRequest<AppSettingView> {
  @override
  String get dwTypeName => 'ListAppSettings';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is ListAppSettings;

  @override
  int get hashCode => (ListAppSettings).hashCode;

  @override
  String toString() => 'ListAppSettings()';
}

ListAppSettings $ListAppSettingsFromJson(Map<String, Object?> json) =>
    const ListAppSettings();

mixin _$SaveAppSetting on DwCommand<AppSettingView> {
  SaveAppSetting get _self => this as SaveAppSetting;

  @override
  String get dwTypeName => 'SaveAppSetting';

  @override
  Map<String, Object?> toJson() => {'key': _self.key, 'value': _self.value};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveAppSetting &&
          other.key == _self.key &&
          other.value == _self.value;

  @override
  int get hashCode => Object.hash(SaveAppSetting, _self.key, _self.value);
}

SaveAppSetting $SaveAppSettingFromJson(Map<String, Object?> json) =>
    SaveAppSetting(
      key: json['key']! as String,
      value: json['value']! as String,
    );
