// GENERATED BY dartway generate. DO NOT EDIT.
part of 'settings.dart';

mixin _$ClubSettings on DwDataObject {
  ClubSettings get _self => this as ClubSettings;

  @override
  String get dwTypeName => 'ClubSettings';

  @override
  Map<String, Object?> toJson() => {
    if (_self.clubName != 'DartWay Fitness') 'clubName': _self.clubName,
    if (!_self.bookingEnabled) 'bookingEnabled': _self.bookingEnabled,
    if (_self.supportPhone != '') 'supportPhone': _self.supportPhone,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubSettings &&
          other.clubName == _self.clubName &&
          other.bookingEnabled == _self.bookingEnabled &&
          other.supportPhone == _self.supportPhone;

  @override
  int get hashCode =>
      Object.hash(_self.clubName, _self.bookingEnabled, _self.supportPhone);

  @override
  String toString() =>
      'ClubSettings(clubName: ${_self.clubName}, bookingEnabled: ${_self.bookingEnabled}, supportPhone: ${_self.supportPhone})';
}

ClubSettings $ClubSettingsFromJson(Map<String, Object?> json) => ClubSettings(
  clubName: json['clubName'] == null
      ? 'DartWay Fitness'
      : json['clubName']! as String,
  bookingEnabled: json['bookingEnabled'] == null
      ? true
      : json['bookingEnabled']! as bool,
  supportPhone: json['supportPhone'] == null
      ? ''
      : json['supportPhone']! as String,
);

extension ClubSettingsCopyWith on ClubSettings {
  ClubSettings copyWith({
    String? clubName,
    bool? bookingEnabled,
    String? supportPhone,
  }) => ClubSettings(
    clubName: clubName ?? this.clubName,
    bookingEnabled: bookingEnabled ?? this.bookingEnabled,
    supportPhone: supportPhone ?? this.supportPhone,
  );
}

mixin _$GetClubSettings on DwSingleRequest<ClubSettings> {
  @override
  String get dwTypeName => 'GetClubSettings';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is GetClubSettings;

  @override
  int get hashCode => (GetClubSettings).hashCode;

  @override
  String toString() => 'GetClubSettings()';
}

GetClubSettings $GetClubSettingsFromJson(Map<String, Object?> json) =>
    const GetClubSettings();

mixin _$SaveClubSettings on DwActionCommand<ClubSettings> {
  SaveClubSettings get _self => this as SaveClubSettings;

  @override
  String get dwTypeName => 'SaveClubSettings';

  @override
  Map<String, Object?> toJson() => {
    if (_self.clubName != null) 'clubName': _self.clubName,
    if (_self.bookingEnabled != null) 'bookingEnabled': _self.bookingEnabled,
    if (_self.supportPhone != null) 'supportPhone': _self.supportPhone,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveClubSettings &&
          other.clubName == _self.clubName &&
          other.bookingEnabled == _self.bookingEnabled &&
          other.supportPhone == _self.supportPhone;

  @override
  int get hashCode => Object.hash(
    SaveClubSettings,
    _self.clubName,
    _self.bookingEnabled,
    _self.supportPhone,
  );
}

SaveClubSettings $SaveClubSettingsFromJson(Map<String, Object?> json) =>
    SaveClubSettings(
      clubName: json['clubName'] as String?,
      bookingEnabled: json['bookingEnabled'] as bool?,
      supportPhone: json['supportPhone'] as String?,
    );
