// GENERATED BY dartway generate. DO NOT EDIT.
part of 'schedule_rows.dart';

mixin _$ClubServiceRow on DwTableRow {
  ClubServiceRow get _self => this as ClubServiceRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubServiceRow &&
          other.id == _self.id &&
          other.title == _self.title &&
          other.description == _self.description &&
          other.durationMinutes == _self.durationMinutes &&
          other.price == _self.price &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.title,
    _self.description,
    _self.durationMinutes,
    _self.price,
    _self.imageUrl,
  );

  @override
  String toString() =>
      'ClubServiceRow(id: ${_self.id}, title: ${_self.title}, description: ${_self.description}, durationMinutes: ${_self.durationMinutes}, price: ${_self.price}, imageUrl: ${_self.imageUrl})';
}

extension ClubServiceRowCopyWith on ClubServiceRow {
  ClubServiceRow copyWith({
    String? title,
    String? description,
    int? durationMinutes,
    int? price,
    DwFieldPatch<String> imageUrl = const DwFieldPatch.keep(),
  }) => ClubServiceRow(
    id: id,
    title: title ?? this.title,
    description: description ?? this.description,
    durationMinutes: durationMinutes ?? this.durationMinutes,
    price: price ?? this.price,
    imageUrl: imageUrl.apply(this.imageUrl),
  );
}

mixin _$NewClubServiceRow on DwRowDraft<ClubServiceRow> {
  NewClubServiceRow get _self => this as NewClubServiceRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewClubServiceRow &&
          other.title == _self.title &&
          other.description == _self.description &&
          other.durationMinutes == _self.durationMinutes &&
          other.price == _self.price &&
          other.imageUrl == _self.imageUrl;

  @override
  int get hashCode => Object.hash(
    _self.title,
    _self.description,
    _self.durationMinutes,
    _self.price,
    _self.imageUrl,
  );

  @override
  String toString() =>
      'NewClubServiceRow(title: ${_self.title}, description: ${_self.description}, durationMinutes: ${_self.durationMinutes}, price: ${_self.price}, imageUrl: ${_self.imageUrl})';
}

/// A [ClubServiceRow] before insert: every column but the id.
final class NewClubServiceRow extends DwRowDraft<ClubServiceRow>
    with _$NewClubServiceRow {
  const NewClubServiceRow({
    required this.title,
    required this.description,
    required this.durationMinutes,
    required this.price,
    this.imageUrl,
  });

  final String title;
  final String description;
  final int durationMinutes;
  final int price;
  final String? imageUrl;
}

extension NewClubServiceRowCopyWith on NewClubServiceRow {
  NewClubServiceRow copyWith({
    String? title,
    String? description,
    int? durationMinutes,
    int? price,
    DwFieldPatch<String> imageUrl = const DwFieldPatch.keep(),
  }) => NewClubServiceRow(
    title: title ?? this.title,
    description: description ?? this.description,
    durationMinutes: durationMinutes ?? this.durationMinutes,
    price: price ?? this.price,
    imageUrl: imageUrl.apply(this.imageUrl),
  );
}

extension NewClubServiceRowWithId on NewClubServiceRow {
  /// The row stored under [id], for `update`.
  ClubServiceRow withId(int id) => ClubServiceRow(
    id: id,
    title: title,
    description: description,
    durationMinutes: durationMinutes,
    price: price,
    imageUrl: imageUrl,
  );
}

final class ClubServiceTable extends DwTableDef<ClubServiceRow> {
  const ClubServiceTable() : super('club_service');

  DwTableColumn<String> get title =>
      const DwTableColumn('title', DwColumnType.text);

  DwTableColumn<String> get description =>
      const DwTableColumn('description', DwColumnType.text);

  DwTableColumn<int> get durationMinutes =>
      const DwTableColumn('duration_minutes', DwColumnType.bigint);

  DwTableColumn<int> get price =>
      const DwTableColumn('price', DwColumnType.bigint);

  DwTableColumn<String?> get imageUrl =>
      const DwTableColumn('image_url', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    title,
    description,
    durationMinutes,
    price,
    imageUrl,
  ];

  @override
  ClubServiceRow fromRow(DwResultRow row) => ClubServiceRow(
    id: row.decode(id),
    title: row.decode(title),
    description: row.decode(description),
    durationMinutes: row.decode(durationMinutes),
    price: row.decode(price),
    imageUrl: row.decode(imageUrl),
  );

  @override
  Map<String, Object?> toRow(ClubServiceRow row) => {
    'title': row.title,
    'description': row.description,
    'duration_minutes': row.durationMinutes,
    'price': row.price,
    'image_url': row.imageUrl,
  };

  @override
  Map<String, Object?> toDraftRow(NewClubServiceRow draft) => {
    'title': draft.title,
    'description': draft.description,
    'duration_minutes': draft.durationMinutes,
    'price': draft.price,
    'image_url': draft.imageUrl,
  };
}

mixin _$ClubSessionRow on DwTableRow {
  ClubSessionRow get _self => this as ClubSessionRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubSessionRow &&
          other.id == _self.id &&
          other.serviceId == _self.serviceId &&
          other.coachProfileId == _self.coachProfileId &&
          other.startsAt == _self.startsAt &&
          other.capacity == _self.capacity &&
          other.bookedCount == _self.bookedCount;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.serviceId,
    _self.coachProfileId,
    _self.startsAt,
    _self.capacity,
    _self.bookedCount,
  );

  @override
  String toString() =>
      'ClubSessionRow(id: ${_self.id}, serviceId: ${_self.serviceId}, coachProfileId: ${_self.coachProfileId}, startsAt: ${_self.startsAt}, capacity: ${_self.capacity}, bookedCount: ${_self.bookedCount})';
}

extension ClubSessionRowCopyWith on ClubSessionRow {
  ClubSessionRow copyWith({
    int? serviceId,
    DwFieldPatch<int> coachProfileId = const DwFieldPatch.keep(),
    DateTime? startsAt,
    int? capacity,
    int? bookedCount,
  }) => ClubSessionRow(
    id: id,
    serviceId: serviceId ?? this.serviceId,
    coachProfileId: coachProfileId.apply(this.coachProfileId),
    startsAt: startsAt ?? this.startsAt,
    capacity: capacity ?? this.capacity,
    bookedCount: bookedCount ?? this.bookedCount,
  );
}

mixin _$NewClubSessionRow on DwRowDraft<ClubSessionRow> {
  NewClubSessionRow get _self => this as NewClubSessionRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewClubSessionRow &&
          other.serviceId == _self.serviceId &&
          other.coachProfileId == _self.coachProfileId &&
          other.startsAt == _self.startsAt &&
          other.capacity == _self.capacity &&
          other.bookedCount == _self.bookedCount;

  @override
  int get hashCode => Object.hash(
    _self.serviceId,
    _self.coachProfileId,
    _self.startsAt,
    _self.capacity,
    _self.bookedCount,
  );

  @override
  String toString() =>
      'NewClubSessionRow(serviceId: ${_self.serviceId}, coachProfileId: ${_self.coachProfileId}, startsAt: ${_self.startsAt}, capacity: ${_self.capacity}, bookedCount: ${_self.bookedCount})';
}

/// A [ClubSessionRow] before insert: every column but the id.
final class NewClubSessionRow extends DwRowDraft<ClubSessionRow>
    with _$NewClubSessionRow {
  const NewClubSessionRow({
    required this.serviceId,
    this.coachProfileId,
    required this.startsAt,
    required this.capacity,
    this.bookedCount = 0,
  });

  final int serviceId;
  final int? coachProfileId;
  final DateTime startsAt;
  final int capacity;
  final int bookedCount;
}

extension NewClubSessionRowCopyWith on NewClubSessionRow {
  NewClubSessionRow copyWith({
    int? serviceId,
    DwFieldPatch<int> coachProfileId = const DwFieldPatch.keep(),
    DateTime? startsAt,
    int? capacity,
    int? bookedCount,
  }) => NewClubSessionRow(
    serviceId: serviceId ?? this.serviceId,
    coachProfileId: coachProfileId.apply(this.coachProfileId),
    startsAt: startsAt ?? this.startsAt,
    capacity: capacity ?? this.capacity,
    bookedCount: bookedCount ?? this.bookedCount,
  );
}

extension NewClubSessionRowWithId on NewClubSessionRow {
  /// The row stored under [id], for `update`.
  ClubSessionRow withId(int id) => ClubSessionRow(
    id: id,
    serviceId: serviceId,
    coachProfileId: coachProfileId,
    startsAt: startsAt,
    capacity: capacity,
    bookedCount: bookedCount,
  );
}

final class ClubSessionTable extends DwTableDef<ClubSessionRow> {
  const ClubSessionTable() : super('club_session');

  DwTableColumn<int> get serviceId => const DwTableColumn(
    'service_id',
    DwColumnType.bigint,
    references: DwForeignKey('club_service', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int?> get coachProfileId => const DwTableColumn(
    'coach_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.setNull),
  );

  DwTableColumn<DateTime> get startsAt =>
      const DwTableColumn('starts_at', DwColumnType.timestamptz);

  DwTableColumn<int> get capacity =>
      const DwTableColumn('capacity', DwColumnType.bigint);

  DwTableColumn<int> get bookedCount =>
      const DwTableColumn('booked_count', DwColumnType.bigint);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    serviceId,
    coachProfileId,
    startsAt,
    capacity,
    bookedCount,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('club_session_starts_at_idx', ['starts_at']),
  ];

  @override
  ClubSessionRow fromRow(DwResultRow row) => ClubSessionRow(
    id: row.decode(id),
    serviceId: row.decode(serviceId),
    coachProfileId: row.decode(coachProfileId),
    startsAt: row.decode(startsAt),
    capacity: row.decode(capacity),
    bookedCount: row.decode(bookedCount),
  );

  @override
  Map<String, Object?> toRow(ClubSessionRow row) => {
    'service_id': row.serviceId,
    'coach_profile_id': row.coachProfileId,
    'starts_at': row.startsAt,
    'capacity': row.capacity,
    'booked_count': row.bookedCount,
  };

  @override
  Map<String, Object?> toDraftRow(NewClubSessionRow draft) => {
    'service_id': draft.serviceId,
    'coach_profile_id': draft.coachProfileId,
    'starts_at': draft.startsAt,
    'capacity': draft.capacity,
    'booked_count': draft.bookedCount,
  };
}
