// GENERATED BY dartway generate. DO NOT EDIT.
part of 'bookings_rows.dart';

mixin _$SessionBookingRow on DwTableRow {
  SessionBookingRow get _self => this as SessionBookingRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionBookingRow &&
          other.id == _self.id &&
          other.sessionId == _self.sessionId &&
          other.clientProfileId == _self.clientProfileId &&
          other.status == _self.status &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.sessionId,
    _self.clientProfileId,
    _self.status,
    _self.createdAt,
  );

  @override
  String toString() =>
      'SessionBookingRow(id: ${_self.id}, sessionId: ${_self.sessionId}, clientProfileId: ${_self.clientProfileId}, status: ${_self.status}, createdAt: ${_self.createdAt})';
}

extension SessionBookingRowCopyWith on SessionBookingRow {
  SessionBookingRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? sessionId,
    int? clientProfileId,
    BookingStatus? status,
    DateTime? createdAt,
  }) => SessionBookingRow(
    id: id.apply(this.id),
    sessionId: sessionId ?? this.sessionId,
    clientProfileId: clientProfileId ?? this.clientProfileId,
    status: status ?? this.status,
    createdAt: createdAt ?? this.createdAt,
  );
}

final class SessionBookingTable extends DwTableDef<SessionBookingRow> {
  const SessionBookingTable() : super('session_booking');

  DwTableColumn<int> get sessionId => const DwTableColumn(
    'session_id',
    DwColumnType.bigint,
    references: DwForeignKey('club_session', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get clientProfileId => const DwTableColumn(
    'client_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<BookingStatus> get status =>
      const DwTableColumn('status', DwEnumType(BookingStatus.values));

  DwTableColumn<DateTime> get createdAt =>
      const DwTableColumn('created_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    sessionId,
    clientProfileId,
    status,
    createdAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('session_booking_client_profile_id_created_at_idx', [
      'client_profile_id',
      'created_at',
    ]),
    DwIndexSchema('session_booking_session_id_status_idx', [
      'session_id',
      'status',
    ]),
  ];

  @override
  SessionBookingRow fromRow(DwResultRow row) => SessionBookingRow(
    id: row.decode(id),
    sessionId: row.decode(sessionId),
    clientProfileId: row.decode(clientProfileId),
    status: row.decode(status),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(SessionBookingRow row) => {
    if (row.id != null) 'id': row.id,
    'session_id': row.sessionId,
    'client_profile_id': row.clientProfileId,
    'status': row.status,
    'created_at': row.createdAt,
  };
}

mixin _$SessionReviewRow on DwTableRow {
  SessionReviewRow get _self => this as SessionReviewRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionReviewRow &&
          other.id == _self.id &&
          other.bookingId == _self.bookingId &&
          other.rating == _self.rating &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.bookingId,
    _self.rating,
    _self.text,
    _self.createdAt,
  );

  @override
  String toString() =>
      'SessionReviewRow(id: ${_self.id}, bookingId: ${_self.bookingId}, rating: ${_self.rating}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

extension SessionReviewRowCopyWith on SessionReviewRow {
  SessionReviewRow copyWith({
    DwFieldPatch<int> id = const DwFieldPatch.keep(),
    int? bookingId,
    int? rating,
    DwFieldPatch<String> text = const DwFieldPatch.keep(),
    DateTime? createdAt,
  }) => SessionReviewRow(
    id: id.apply(this.id),
    bookingId: bookingId ?? this.bookingId,
    rating: rating ?? this.rating,
    text: text.apply(this.text),
    createdAt: createdAt ?? this.createdAt,
  );
}

final class SessionReviewTable extends DwTableDef<SessionReviewRow> {
  const SessionReviewTable() : super('session_review');

  DwTableColumn<int> get bookingId => const DwTableColumn(
    'booking_id',
    DwColumnType.bigint,
    unique: true,
    references: DwForeignKey('session_booking', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get rating =>
      const DwTableColumn('rating', DwColumnType.bigint);

  DwTableColumn<String?> get text =>
      const DwTableColumn('text', DwColumnType.text);

  DwTableColumn<DateTime> get createdAt =>
      const DwTableColumn('created_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    bookingId,
    rating,
    text,
    createdAt,
  ];

  @override
  SessionReviewRow fromRow(DwResultRow row) => SessionReviewRow(
    id: row.decode(id),
    bookingId: row.decode(bookingId),
    rating: row.decode(rating),
    text: row.decode(text),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(SessionReviewRow row) => {
    if (row.id != null) 'id': row.id,
    'booking_id': row.bookingId,
    'rating': row.rating,
    'text': row.text,
    'created_at': row.createdAt,
  };
}
