// GENERATED BY dartway generate. DO NOT EDIT.
part of 'chat.dart';

mixin _$ChatChannel on DwDataObject {
  ChatChannel get _self => this as ChatChannel;

  @override
  String get dwTypeName => 'ChatChannel';

  @override
  Map<String, Object?> toJson() => {'id': _self.id, 'title': _self.title};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChannel &&
          other.id == _self.id &&
          other.title == _self.title;

  @override
  int get hashCode => Object.hash(_self.id, _self.title);

  @override
  String toString() => 'ChatChannel(id: ${_self.id}, title: ${_self.title})';
}

ChatChannel $ChatChannelFromJson(Map<String, Object?> json) =>
    ChatChannel(id: json['id']! as int, title: json['title']! as String);

extension ChatChannelCopyWith on ChatChannel {
  ChatChannel copyWith({int? id, String? title}) =>
      ChatChannel(id: id ?? this.id, title: title ?? this.title);
}

mixin _$ChatReadState on DwDataObject {
  ChatReadState get _self => this as ChatReadState;

  @override
  String get dwTypeName => 'ChatReadState';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'unreadCount': _self.unreadCount,
    if (_self.lastReadMessageId != null)
      'lastReadMessageId': _self.lastReadMessageId,
    if (_self.lastReadSentAt != null)
      'lastReadSentAt': DwJsonCodec.encodeDateTime(_self.lastReadSentAt!),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatReadState &&
          other.id == _self.id &&
          other.unreadCount == _self.unreadCount &&
          other.lastReadMessageId == _self.lastReadMessageId &&
          other.lastReadSentAt == _self.lastReadSentAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.unreadCount,
    _self.lastReadMessageId,
    _self.lastReadSentAt,
  );

  @override
  String toString() =>
      'ChatReadState(id: ${_self.id}, unreadCount: ${_self.unreadCount}, lastReadMessageId: ${_self.lastReadMessageId}, lastReadSentAt: ${_self.lastReadSentAt})';
}

ChatReadState $ChatReadStateFromJson(Map<String, Object?> json) =>
    ChatReadState(
      id: json['id']! as int,
      unreadCount: json['unreadCount']! as int,
      lastReadMessageId: json['lastReadMessageId'] as int?,
      lastReadSentAt: json['lastReadSentAt'] == null
          ? null
          : DwJsonCodec.decodeDateTime(json['lastReadSentAt']),
    );

extension ChatReadStateCopyWith on ChatReadState {
  ChatReadState copyWith({
    int? id,
    int? unreadCount,
    DwFieldPatch<int> lastReadMessageId = const DwFieldPatch.keep(),
    DwFieldPatch<DateTime> lastReadSentAt = const DwFieldPatch.keep(),
  }) => ChatReadState(
    id: id ?? this.id,
    unreadCount: unreadCount ?? this.unreadCount,
    lastReadMessageId: lastReadMessageId.apply(this.lastReadMessageId),
    lastReadSentAt: lastReadSentAt.apply(this.lastReadSentAt),
  );
}

mixin _$ListChatChannels on DwListRequest<ChatChannel> {
  @override
  String get dwTypeName => 'ListChatChannels';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is ListChatChannels;

  @override
  int get hashCode => (ListChatChannels).hashCode;

  @override
  String toString() => 'ListChatChannels()';
}

ListChatChannels $ListChatChannelsFromJson(Map<String, Object?> json) =>
    const ListChatChannels();

mixin _$ListMyChatReadStates on DwListRequest<ChatReadState> {
  @override
  String get dwTypeName => 'ListMyChatReadStates';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is ListMyChatReadStates;

  @override
  int get hashCode => (ListMyChatReadStates).hashCode;

  @override
  String toString() => 'ListMyChatReadStates()';
}

ListMyChatReadStates $ListMyChatReadStatesFromJson(Map<String, Object?> json) =>
    const ListMyChatReadStates();

mixin _$MarkChatRead on DwActionCommand<ChatReadState> {
  MarkChatRead get _self => this as MarkChatRead;

  @override
  String get dwTypeName => 'MarkChatRead';

  @override
  Map<String, Object?> toJson() => {
    'channelId': _self.channelId,
    'messageId': _self.messageId,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarkChatRead &&
          other.channelId == _self.channelId &&
          other.messageId == _self.messageId;

  @override
  int get hashCode =>
      Object.hash(MarkChatRead, _self.channelId, _self.messageId);
}

MarkChatRead $MarkChatReadFromJson(Map<String, Object?> json) => MarkChatRead(
  channelId: json['channelId']! as int,
  messageId: json['messageId']! as int,
);
