// GENERATED BY dartway generate. DO NOT EDIT.
part of 'catalog.dart';

mixin _$Item on Named {
  Item get _self => this as Item;

  @override
  String get dwTypeName => 'Item';

  @override
  Map<String, Object?> toJson() => {
    'title': _self.title,
    'id': _self.id,
    'price': _self.price,
    if (_self.discount != null) 'discount': _self.discount,
    'duration': DwJson.encodeDuration(_self.duration),
    if (_self.timeout != null) 'timeout': DwJson.encodeDuration(_self.timeout!),
    'image': DwJson.encodeBytes(_self.image),
    if (_self.thumbnail != null)
      'thumbnail': DwJson.encodeBytes(_self.thumbnail!),
    'color': _self.color.name,
    if (_self.colors.isNotEmpty)
      'colors': [for (final e in _self.colors) e.name],
    if (_self.labels.isNotEmpty) 'labels': _self.labels,
    'createdAt': DwJson.encodeDateTime(_self.createdAt),
    if (_self.updatedAt != null)
      'updatedAt': DwJson.encodeDateTime(_self.updatedAt!),
    'weight': _self.weight,
    'unit': _self.unit.name,
    if (_self.parent != null) 'parent': _self.parent!.toJson(),
    if (_self.children.isNotEmpty)
      'children': [for (final e in _self.children) e.toJson()],
    'ratings': _self.ratings,
    if (_self.scores != null) 'scores': _self.scores,
    if (_self.history.isNotEmpty)
      'history': _self.history.map(
        (k, v) => MapEntry(k, v == null ? null : DwJson.encodeDateTime(v)),
      ),
    if (_self.maybeColors.isNotEmpty)
      'maybeColors': [for (final e in _self.maybeColors) e?.name],
    'dimensions': _self.dimensions.toJson(),
    if (_self.allDimensions.isNotEmpty)
      'allDimensions': [for (final e in _self.allDimensions) e?.toJson()],
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Item &&
          other.title == _self.title &&
          other.id == _self.id &&
          other.price == _self.price &&
          other.discount == _self.discount &&
          other.duration == _self.duration &&
          other.timeout == _self.timeout &&
          dwListEquals(other.image, _self.image) &&
          dwListEquals(other.thumbnail, _self.thumbnail) &&
          other.color == _self.color &&
          dwListEquals(other.colors, _self.colors) &&
          dwMapEquals(other.labels, _self.labels) &&
          other.createdAt == _self.createdAt &&
          other.updatedAt == _self.updatedAt &&
          other.weight == _self.weight &&
          other.unit == _self.unit &&
          other.parent == _self.parent &&
          dwListEquals(other.children, _self.children) &&
          dwListEquals(other.ratings, _self.ratings) &&
          dwMapEquals(other.scores, _self.scores) &&
          dwMapEquals(other.history, _self.history) &&
          dwListEquals(other.maybeColors, _self.maybeColors) &&
          other.dimensions == _self.dimensions &&
          dwListEquals(other.allDimensions, _self.allDimensions);

  @override
  int get hashCode => Object.hashAll([
    _self.title,
    _self.id,
    _self.price,
    _self.discount,
    _self.duration,
    _self.timeout,
    Object.hashAll(_self.image),
    _self.thumbnail == null ? null : Object.hashAll(_self.thumbnail!),
    _self.color,
    Object.hashAll(_self.colors),
    Object.hashAllUnordered(
      _self.labels.entries.map((e) => Object.hash(e.key, e.value)),
    ),
    _self.createdAt,
    _self.updatedAt,
    _self.weight,
    _self.unit,
    _self.parent,
    Object.hashAll(_self.children),
    Object.hashAll(_self.ratings),
    _self.scores == null
        ? null
        : Object.hashAllUnordered(
            _self.scores!.entries.map((e) => Object.hash(e.key, e.value)),
          ),
    Object.hashAllUnordered(
      _self.history.entries.map((e) => Object.hash(e.key, e.value)),
    ),
    Object.hashAll(_self.maybeColors),
    _self.dimensions,
    Object.hashAll(_self.allDimensions),
  ]);

  @override
  String toString() =>
      'Item(title: ${_self.title}, id: ${_self.id}, price: ${_self.price}, discount: ${_self.discount}, duration: ${_self.duration}, timeout: ${_self.timeout}, image: ${_self.image}, thumbnail: ${_self.thumbnail}, color: ${_self.color}, colors: ${_self.colors}, labels: ${_self.labels}, createdAt: ${_self.createdAt}, updatedAt: ${_self.updatedAt}, weight: ${_self.weight}, unit: ${_self.unit}, parent: ${_self.parent}, children: ${_self.children}, ratings: ${_self.ratings}, scores: ${_self.scores}, history: ${_self.history}, maybeColors: ${_self.maybeColors}, dimensions: ${_self.dimensions}, allDimensions: ${_self.allDimensions})';
}

Item $ItemFromJson(Map<String, Object?> json) => Item(
  title: json['title']! as String,
  id: json['id']! as int,
  price: json['price']! as int,
  discount: json['discount'] == null
      ? null
      : DwJson.decodeDouble(json['discount']),
  duration: DwJson.decodeDuration(json['duration']),
  timeout: json['timeout'] == null
      ? null
      : DwJson.decodeDuration(json['timeout']),
  image: DwJson.decodeBytes(json['image']),
  thumbnail: json['thumbnail'] == null
      ? null
      : DwJson.decodeBytes(json['thumbnail']),
  color: DwJson.decodeEnum(json['color'], Color.values),
  colors: json['colors'] == null
      ? const []
      : DwJson.decodeList(
          json['colors'],
          (e) => DwJson.decodeEnum(e, Color.values),
        ),
  labels: json['labels'] == null
      ? const {}
      : DwJson.decodeMap(json['labels'], (v) => v! as String),
  createdAt: DwJson.decodeDateTime(json['createdAt']),
  updatedAt: json['updatedAt'] == null
      ? null
      : DwJson.decodeDateTime(json['updatedAt']),
  weight: json['weight']! as int,
  unit: DwJson.decodeEnum(json['unit'], units.Unit.values),
  parent: json['parent'] == null
      ? null
      : $ItemFromJson(json['parent']! as Map<String, Object?>),
  children: json['children'] == null
      ? const []
      : DwJson.decodeList(
          json['children'],
          (e) => $ItemFromJson(e! as Map<String, Object?>),
        ),
  ratings: DwJson.decodeList(json['ratings'], (e) => DwJson.decodeDouble(e)),
  scores: json['scores'] == null
      ? null
      : DwJson.decodeMap(json['scores'], (v) => v! as int),
  history: json['history'] == null
      ? const {}
      : DwJson.decodeMap(
          json['history'],
          (v) => v == null ? null : DwJson.decodeDateTime(v),
        ),
  maybeColors: json['maybeColors'] == null
      ? const []
      : DwJson.decodeList(
          json['maybeColors'],
          (e) => e == null ? null : DwJson.decodeEnum(e, Color.values),
        ),
  dimensions: units.$DimensionsFromJson(
    json['dimensions']! as Map<String, Object?>,
  ),
  allDimensions: json['allDimensions'] == null
      ? const []
      : DwJson.decodeList(
          json['allDimensions'],
          (e) => e == null
              ? null
              : units.$DimensionsFromJson(e as Map<String, Object?>),
        ),
);

extension ItemCopyWith on Item {
  Item copyWith({
    String? title,
    int? id,
    int? price,
    DwPatch<double> discount = const DwPatch.keep(),
    Duration? duration,
    DwPatch<Duration> timeout = const DwPatch.keep(),
    Uint8List? image,
    DwPatch<Uint8List> thumbnail = const DwPatch.keep(),
    Color? color,
    List<Color>? colors,
    Map<String, String>? labels,
    DateTime? createdAt,
    DwPatch<DateTime> updatedAt = const DwPatch.keep(),
    int? weight,
    units.Unit? unit,
    DwPatch<Item> parent = const DwPatch.keep(),
    List<Item>? children,
    List<double>? ratings,
    DwPatch<Map<String, int>> scores = const DwPatch.keep(),
    Map<String, DateTime?>? history,
    List<Color?>? maybeColors,
    units.Dimensions? dimensions,
    List<units.Dimensions?>? allDimensions,
  }) => Item(
    title: title ?? this.title,
    id: id ?? this.id,
    price: price ?? this.price,
    discount: discount.apply(this.discount),
    duration: duration ?? this.duration,
    timeout: timeout.apply(this.timeout),
    image: image ?? this.image,
    thumbnail: thumbnail.apply(this.thumbnail),
    color: color ?? this.color,
    colors: colors ?? this.colors,
    labels: labels ?? this.labels,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt.apply(this.updatedAt),
    weight: weight ?? this.weight,
    unit: unit ?? this.unit,
    parent: parent.apply(this.parent),
    children: children ?? this.children,
    ratings: ratings ?? this.ratings,
    scores: scores.apply(this.scores),
    history: history ?? this.history,
    maybeColors: maybeColors ?? this.maybeColors,
    dimensions: dimensions ?? this.dimensions,
    allDimensions: allDimensions ?? this.allDimensions,
  );
}

mixin _$Stats on DwDataObject {
  Stats get _self => this as Stats;

  @override
  String get dwTypeName => 'Stats';

  @override
  Map<String, Object?> toJson() => {'count': _self.count};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Stats && other.count == _self.count;

  @override
  int get hashCode => _self.count.hashCode;

  @override
  String toString() => 'Stats(count: ${_self.count})';
}

Stats $StatsFromJson(Map<String, Object?> json) =>
    Stats(count: json['count']! as int);

extension StatsCopyWith on Stats {
  Stats copyWith({int? count}) => Stats(count: count ?? this.count);
}

mixin _$Ref on DwDataObject {
  Ref get _self => this as Ref;

  @override
  String get dwTypeName => 'Ref';

  @override
  Map<String, Object?> toJson() => {'id': _self.id};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Ref && other.id == _self.id;

  @override
  int get hashCode => _self.id.hashCode;

  @override
  String toString() => 'Ref(id: ${_self.id})';
}

Ref $RefFromJson(Map<String, Object?> json) => Ref(id: json['id']! as String);

extension RefCopyWith on Ref {
  Ref copyWith({String? id}) => Ref(id: id ?? this.id);
}

mixin _$SessionHolder on DwDataObject {
  SessionHolder get _self => this as SessionHolder;

  @override
  String get dwTypeName => 'SessionHolder';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'session': _self.session.toJson(),
    if (_self.previous != null) 'previous': _self.previous!.toJson(),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionHolder &&
          other.id == _self.id &&
          other.session == _self.session &&
          other.previous == _self.previous;

  @override
  int get hashCode => Object.hash(_self.id, _self.session, _self.previous);

  @override
  String toString() =>
      'SessionHolder(id: ${_self.id}, session: ${_self.session}, previous: ${_self.previous})';
}

SessionHolder $SessionHolderFromJson(Map<String, Object?> json) =>
    SessionHolder(
      id: json['id']! as int,
      session: DwSession.fromJson(json['session']! as Map<String, Object?>),
      previous: json['previous'] == null
          ? null
          : DwSession.fromJson(json['previous']! as Map<String, Object?>),
    );

extension SessionHolderCopyWith on SessionHolder {
  SessionHolder copyWith({
    int? id,
    DwSession? session,
    DwPatch<DwSession> previous = const DwPatch.keep(),
  }) => SessionHolder(
    id: id ?? this.id,
    session: session ?? this.session,
    previous: previous.apply(this.previous),
  );
}

mixin _$GetItem on DwSingleRequest<Item> {
  GetItem get _self => this as GetItem;

  @override
  String get dwTypeName => 'GetItem';

  @override
  Map<String, Object?> toJson() => {'id': _self.id};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is GetItem && other.id == _self.id;

  @override
  int get hashCode => Object.hash(GetItem, _self.id);

  @override
  String toString() => 'GetItem(id: ${_self.id})';
}

GetItem $GetItemFromJson(Map<String, Object?> json) =>
    GetItem(id: json['id']! as int);

mixin _$FindItem on DwMaybeRequest<Item> {
  FindItem get _self => this as FindItem;

  @override
  String get dwTypeName => 'FindItem';

  @override
  Map<String, Object?> toJson() => {
    if (_self.title != null) 'title': _self.title,
    if (_self.colors.isNotEmpty)
      'colors': [for (final e in _self.colors) e.name],
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FindItem &&
          other.title == _self.title &&
          dwListEquals(other.colors, _self.colors);

  @override
  int get hashCode =>
      Object.hash(FindItem, _self.title, Object.hashAll(_self.colors));

  @override
  String toString() =>
      'FindItem(title: ${_self.title}, colors: ${_self.colors})';
}

FindItem $FindItemFromJson(Map<String, Object?> json) => FindItem(
  title: json['title'] as String?,
  colors: json['colors'] == null
      ? const []
      : DwJson.decodeList(
          json['colors'],
          (e) => DwJson.decodeEnum(e, Color.values),
        ),
);

mixin _$ListItems on DwPageRequest<Item> {
  ListItems get _self => this as ListItems;

  @override
  String get dwTypeName => 'ListItems';

  @override
  Map<String, Object?> toJson() => {
    if (_self.color != null) 'color': _self.color!.name,
    if (_self.since != null) 'since': DwJson.encodeDateTime(_self.since!),
    if (_self.labels != null) 'labels': _self.labels,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListItems &&
          other.color == _self.color &&
          other.since == _self.since &&
          dwMapEquals(other.labels, _self.labels);

  @override
  int get hashCode => Object.hash(
    ListItems,
    _self.color,
    _self.since,
    _self.labels == null
        ? null
        : Object.hashAllUnordered(
            _self.labels!.entries.map((e) => Object.hash(e.key, e.value)),
          ),
  );

  @override
  String toString() =>
      'ListItems(color: ${_self.color}, since: ${_self.since}, labels: ${_self.labels})';
}

ListItems $ListItemsFromJson(Map<String, Object?> json) => ListItems(
  color: json['color'] == null
      ? null
      : DwJson.decodeEnum(json['color'], Color.values),
  since: json['since'] == null ? null : DwJson.decodeDateTime(json['since']),
  labels: json['labels'] == null
      ? null
      : DwJson.decodeMap(json['labels'], (v) => v! as String),
);

mixin _$FeedItems on DwCursorRequest<Item> {
  @override
  String get dwTypeName => 'FeedItems';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is FeedItems;

  @override
  int get hashCode => (FeedItems).hashCode;

  @override
  String toString() => 'FeedItems()';
}

FeedItems $FeedItemsFromJson(Map<String, Object?> json) => const FeedItems();

mixin _$EditItem on DwCommand<Item> {
  EditItem get _self => this as EditItem;

  @override
  String get dwTypeName => 'EditItem';

  @override
  Map<String, Object?> toJson() {
    final json = <String, Object?>{
      'itemId': _self.itemId,
      if (_self.tags.isNotEmpty) 'tags': _self.tags,
    };
    DwJson.writePatch(json, 'title', _self.title, (v) => v);
    DwJson.writePatch(
      json,
      'updatedAt',
      _self.updatedAt,
      (v) => DwJson.encodeDateTime(v),
    );
    DwJson.writePatch(json, 'color', _self.color, (v) => v.name);
    DwJson.writePatch(json, 'dimensions', _self.dimensions, (v) => v.toJson());
    DwJson.writePatch(json, 'discount', _self.discount, (v) => v);
    DwJson.writePatch(
      json,
      'timeout',
      _self.timeout,
      (v) => DwJson.encodeDuration(v),
    );
    return json;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditItem &&
          other.itemId == _self.itemId &&
          other.title == _self.title &&
          other.updatedAt == _self.updatedAt &&
          other.color == _self.color &&
          other.dimensions == _self.dimensions &&
          other.discount == _self.discount &&
          other.timeout == _self.timeout &&
          dwListEquals(other.tags, _self.tags);

  @override
  int get hashCode => Object.hash(
    EditItem,
    _self.itemId,
    _self.title,
    _self.updatedAt,
    _self.color,
    _self.dimensions,
    _self.discount,
    _self.timeout,
    Object.hashAll(_self.tags),
  );
}

EditItem $EditItemFromJson(Map<String, Object?> json) => EditItem(
  itemId: json['itemId']! as int,
  title: DwJson.readPatch(json, 'title', (v) => v! as String),
  updatedAt: DwJson.readPatch(
    json,
    'updatedAt',
    (v) => DwJson.decodeDateTime(v),
  ),
  color: DwJson.readPatch(
    json,
    'color',
    (v) => DwJson.decodeEnum(v, Color.values),
  ),
  dimensions: DwJson.readPatch(
    json,
    'dimensions',
    (v) => units.$DimensionsFromJson(v! as Map<String, Object?>),
  ),
  discount: DwJson.readPatch(json, 'discount', (v) => DwJson.decodeDouble(v)),
  timeout: DwJson.readPatch(json, 'timeout', (v) => DwJson.decodeDuration(v)),
  tags: json['tags'] == null
      ? const []
      : DwJson.decodeList(json['tags'], (e) => e! as String),
);

mixin _$OnlyPatches on DwCommand<void> {
  OnlyPatches get _self => this as OnlyPatches;

  @override
  String get dwTypeName => 'OnlyPatches';

  @override
  Map<String, Object?> toJson() {
    final json = <String, Object?>{};
    DwJson.writePatch(json, 'note', _self.note, (v) => v);
    return json;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnlyPatches && other.note == _self.note;

  @override
  int get hashCode => Object.hash(OnlyPatches, _self.note);
}

OnlyPatches $OnlyPatchesFromJson(Map<String, Object?> json) =>
    OnlyPatches(note: DwJson.readPatch(json, 'note', (v) => v! as String));

mixin _$RemoveItem on DwCommand<void> {
  @override
  String get dwTypeName => 'RemoveItem';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is RemoveItem;

  @override
  int get hashCode => (RemoveItem).hashCode;
}

RemoveItem $RemoveItemFromJson(Map<String, Object?> json) => const RemoveItem();

mixin _$WideRequest on DwListRequest<Item> {
  WideRequest get _self => this as WideRequest;

  @override
  String get dwTypeName => 'WideRequest';

  @override
  Map<String, Object?> toJson() => {
    'a1': _self.a1,
    'a2': _self.a2,
    'a3': _self.a3,
    'a4': _self.a4,
    'a5': _self.a5,
    'a6': _self.a6,
    'a7': _self.a7,
    'a8': _self.a8,
    'a9': _self.a9,
    'a10': _self.a10,
    'a11': _self.a11,
    'a12': _self.a12,
    'a13': _self.a13,
    'a14': _self.a14,
    'a15': _self.a15,
    'a16': _self.a16,
    'a17': _self.a17,
    'a18': _self.a18,
    'a19': _self.a19,
    'a20': _self.a20,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WideRequest &&
          other.a1 == _self.a1 &&
          other.a2 == _self.a2 &&
          other.a3 == _self.a3 &&
          other.a4 == _self.a4 &&
          other.a5 == _self.a5 &&
          other.a6 == _self.a6 &&
          other.a7 == _self.a7 &&
          other.a8 == _self.a8 &&
          other.a9 == _self.a9 &&
          other.a10 == _self.a10 &&
          other.a11 == _self.a11 &&
          other.a12 == _self.a12 &&
          other.a13 == _self.a13 &&
          other.a14 == _self.a14 &&
          other.a15 == _self.a15 &&
          other.a16 == _self.a16 &&
          other.a17 == _self.a17 &&
          other.a18 == _self.a18 &&
          other.a19 == _self.a19 &&
          other.a20 == _self.a20;

  @override
  int get hashCode => Object.hashAll([
    WideRequest,
    _self.a1,
    _self.a2,
    _self.a3,
    _self.a4,
    _self.a5,
    _self.a6,
    _self.a7,
    _self.a8,
    _self.a9,
    _self.a10,
    _self.a11,
    _self.a12,
    _self.a13,
    _self.a14,
    _self.a15,
    _self.a16,
    _self.a17,
    _self.a18,
    _self.a19,
    _self.a20,
  ]);

  @override
  String toString() =>
      'WideRequest(a1: ${_self.a1}, a2: ${_self.a2}, a3: ${_self.a3}, a4: ${_self.a4}, a5: ${_self.a5}, a6: ${_self.a6}, a7: ${_self.a7}, a8: ${_self.a8}, a9: ${_self.a9}, a10: ${_self.a10}, a11: ${_self.a11}, a12: ${_self.a12}, a13: ${_self.a13}, a14: ${_self.a14}, a15: ${_self.a15}, a16: ${_self.a16}, a17: ${_self.a17}, a18: ${_self.a18}, a19: ${_self.a19}, a20: ${_self.a20})';
}

WideRequest $WideRequestFromJson(Map<String, Object?> json) => WideRequest(
  a1: json['a1']! as int,
  a2: json['a2']! as int,
  a3: json['a3']! as int,
  a4: json['a4']! as int,
  a5: json['a5']! as int,
  a6: json['a6']! as int,
  a7: json['a7']! as int,
  a8: json['a8']! as int,
  a9: json['a9']! as int,
  a10: json['a10']! as int,
  a11: json['a11']! as int,
  a12: json['a12']! as int,
  a13: json['a13']! as int,
  a14: json['a14']! as int,
  a15: json['a15']! as int,
  a16: json['a16']! as int,
  a17: json['a17']! as int,
  a18: json['a18']! as int,
  a19: json['a19']! as int,
  a20: json['a20']! as int,
);
