// GENERATED BY dartway generate. DO NOT EDIT.
part of 'defaults.dart';

mixin _$Settings on DwDataObject {
  Settings get _self => this as Settings;

  @override
  String get dwTypeName => 'Settings';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    if (_self.count != 3) 'count': _self.count,
    if (_self.offset != -1) 'offset': _self.offset,
    if (!_self.enabled) 'enabled': _self.enabled,
    if (_self.title != 'Untitled') 'title': _self.title,
    if (_self.escaped != 'it\'s \$5\n\\') 'escaped': _self.escaped,
    if (_self.ratio != 1.0) 'ratio': _self.ratio,
    if (_self.color != Color.green) 'color': _self.color.name,
    if (_self.unit != units.Unit.kg) 'unit': _self.unit.name,
    if (_self.timeout != const Duration(microseconds: 30000000))
      'timeout': DwJsonCodec.encodeDuration(_self.timeout),
    if (_self.label != 'none') 'label': _self.label,
    if (_self.maybeColor != Color.red) 'maybeColor': _self.maybeColor?.name,
    if (_self.note != null) 'note': _self.note,
    'createdAt': DwJsonCodec.encodeDateTime(_self.createdAt),
    if (_self.startsAt != null)
      'startsAt': DwJsonCodec.encodeDateTime(_self.startsAt!),
    if (!dwListEquals(_self.tags, const <String>['a', 'b'])) 'tags': _self.tags,
    if (_self.empty.isNotEmpty) 'empty': _self.empty,
    if (!dwMapEquals(_self.limits, const <String, int>{'max': 10, 'min': 1}))
      'limits': _self.limits,
    if (_self.noLimits.isNotEmpty) 'noLimits': _self.noLimits,
    if (!dwListEquals(_self.maybeTags, const <String>['x']))
      'maybeTags': _self.maybeTags,
    if (_self.dimensions != const units.Dimensions(id: 'default', width: 1.0))
      'dimensions': _self.dimensions.toJson(),
    if (!dwListEquals(_self.shelf, const <units.Dimensions>[
      units.Dimensions(id: 'shelf', width: 2.0, height: 0.5),
    ]))
      'shelf': [for (final e in _self.shelf) e.toJson()],
    if (_self.ref != const Ref(id: 'fallback')) 'ref': _self.ref.toJson(),
    if (_self.loose != Loose(id: 'fixed')) 'loose': _self.loose.toJson(),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          other.id == _self.id &&
          other.count == _self.count &&
          other.offset == _self.offset &&
          other.enabled == _self.enabled &&
          other.title == _self.title &&
          other.escaped == _self.escaped &&
          other.ratio == _self.ratio &&
          other.color == _self.color &&
          other.unit == _self.unit &&
          other.timeout == _self.timeout &&
          other.label == _self.label &&
          other.maybeColor == _self.maybeColor &&
          other.note == _self.note &&
          other.createdAt == _self.createdAt &&
          other.startsAt == _self.startsAt &&
          dwListEquals(other.tags, _self.tags) &&
          dwListEquals(other.empty, _self.empty) &&
          dwMapEquals(other.limits, _self.limits) &&
          dwMapEquals(other.noLimits, _self.noLimits) &&
          dwListEquals(other.maybeTags, _self.maybeTags) &&
          other.dimensions == _self.dimensions &&
          dwListEquals(other.shelf, _self.shelf) &&
          other.ref == _self.ref &&
          other.loose == _self.loose;

  @override
  int get hashCode => Object.hashAll([
    _self.id,
    _self.count,
    _self.offset,
    _self.enabled,
    _self.title,
    _self.escaped,
    _self.ratio,
    _self.color,
    _self.unit,
    _self.timeout,
    _self.label,
    _self.maybeColor,
    _self.note,
    _self.createdAt,
    _self.startsAt,
    Object.hashAll(_self.tags),
    Object.hashAll(_self.empty),
    Object.hashAllUnordered(
      _self.limits.entries.map((e) => Object.hash(e.key, e.value)),
    ),
    Object.hashAllUnordered(
      _self.noLimits.entries.map((e) => Object.hash(e.key, e.value)),
    ),
    _self.maybeTags == null ? null : Object.hashAll(_self.maybeTags!),
    _self.dimensions,
    Object.hashAll(_self.shelf),
    _self.ref,
    _self.loose,
  ]);

  @override
  String toString() =>
      'Settings(id: ${_self.id}, count: ${_self.count}, offset: ${_self.offset}, enabled: ${_self.enabled}, title: ${_self.title}, escaped: ${_self.escaped}, ratio: ${_self.ratio}, color: ${_self.color}, unit: ${_self.unit}, timeout: ${_self.timeout}, label: ${_self.label}, maybeColor: ${_self.maybeColor}, note: ${_self.note}, createdAt: ${_self.createdAt}, startsAt: ${_self.startsAt}, tags: ${_self.tags}, empty: ${_self.empty}, limits: ${_self.limits}, noLimits: ${_self.noLimits}, maybeTags: ${_self.maybeTags}, dimensions: ${_self.dimensions}, shelf: ${_self.shelf}, ref: ${_self.ref}, loose: ${_self.loose})';
}

Settings $SettingsFromJson(Map<String, Object?> json) => Settings(
  id: json['id']! as int,
  count: json['count'] == null ? 3 : json['count']! as int,
  offset: json['offset'] == null ? -1 : json['offset']! as int,
  enabled: json['enabled'] == null ? true : json['enabled']! as bool,
  title: json['title'] == null ? 'Untitled' : json['title']! as String,
  escaped: json['escaped'] == null
      ? 'it\'s \$5\n\\'
      : json['escaped']! as String,
  ratio: json['ratio'] == null ? 1.0 : DwJsonCodec.decodeDouble(json['ratio']),
  color: json['color'] == null
      ? Color.green
      : DwJsonCodec.decodeEnum(json['color'], Color.values),
  unit: json['unit'] == null
      ? units.Unit.kg
      : DwJsonCodec.decodeEnum(json['unit'], units.Unit.values),
  timeout: json['timeout'] == null
      ? const Duration(microseconds: 30000000)
      : DwJsonCodec.decodeDuration(json['timeout']),
  label: json.containsKey('label') ? (json['label'] as String?) : 'none',
  maybeColor: json.containsKey('maybeColor')
      ? (json['maybeColor'] == null
            ? null
            : DwJsonCodec.decodeEnum(json['maybeColor'], Color.values))
      : Color.red,
  note: json['note'] as String?,
  createdAt: DwJsonCodec.decodeDateTime(json['createdAt']),
  startsAt: json['startsAt'] == null
      ? null
      : DwJsonCodec.decodeDateTime(json['startsAt']),
  tags: json['tags'] == null
      ? const <String>['a', 'b']
      : DwJsonCodec.decodeList(json['tags'], (e) => e! as String),
  empty: json['empty'] == null
      ? const []
      : DwJsonCodec.decodeList(json['empty'], (e) => e! as int),
  limits: json['limits'] == null
      ? const <String, int>{'max': 10, 'min': 1}
      : DwJsonCodec.decodeMap(json['limits'], (v) => v! as int),
  noLimits: json['noLimits'] == null
      ? const {}
      : DwJsonCodec.decodeMap(json['noLimits'], (v) => v! as bool),
  maybeTags: json.containsKey('maybeTags')
      ? (json['maybeTags'] == null
            ? null
            : DwJsonCodec.decodeList(json['maybeTags'], (e) => e! as String))
      : const <String>['x'],
  dimensions: json['dimensions'] == null
      ? const units.Dimensions(id: 'default', width: 1.0)
      : units.$DimensionsFromJson(json['dimensions']! as Map<String, Object?>),
  shelf: json['shelf'] == null
      ? const <units.Dimensions>[
          units.Dimensions(id: 'shelf', width: 2.0, height: 0.5),
        ]
      : DwJsonCodec.decodeList(
          json['shelf'],
          (e) => units.$DimensionsFromJson(e! as Map<String, Object?>),
        ),
  ref: json['ref'] == null
      ? const Ref(id: 'fallback')
      : $RefFromJson(json['ref']! as Map<String, Object?>),
  loose: json['loose'] == null
      ? Loose(id: 'fixed')
      : $LooseFromJson(json['loose']! as Map<String, Object?>),
);

extension SettingsCopyWith on Settings {
  Settings copyWith({
    int? id,
    int? count,
    int? offset,
    bool? enabled,
    String? title,
    String? escaped,
    double? ratio,
    Color? color,
    units.Unit? unit,
    Duration? timeout,
    DwFieldPatch<String> label = const DwFieldPatch.keep(),
    DwFieldPatch<Color> maybeColor = const DwFieldPatch.keep(),
    DwFieldPatch<String> note = const DwFieldPatch.keep(),
    DateTime? createdAt,
    DwFieldPatch<DateTime> startsAt = const DwFieldPatch.keep(),
    List<String>? tags,
    List<int>? empty,
    Map<String, int>? limits,
    Map<String, bool>? noLimits,
    DwFieldPatch<List<String>> maybeTags = const DwFieldPatch.keep(),
    units.Dimensions? dimensions,
    List<units.Dimensions>? shelf,
    Ref? ref,
    Loose? loose,
  }) => Settings(
    id: id ?? this.id,
    count: count ?? this.count,
    offset: offset ?? this.offset,
    enabled: enabled ?? this.enabled,
    title: title ?? this.title,
    escaped: escaped ?? this.escaped,
    ratio: ratio ?? this.ratio,
    color: color ?? this.color,
    unit: unit ?? this.unit,
    timeout: timeout ?? this.timeout,
    label: label.apply(this.label),
    maybeColor: maybeColor.apply(this.maybeColor),
    note: note.apply(this.note),
    createdAt: createdAt ?? this.createdAt,
    startsAt: startsAt.apply(this.startsAt),
    tags: tags ?? this.tags,
    empty: empty ?? this.empty,
    limits: limits ?? this.limits,
    noLimits: noLimits ?? this.noLimits,
    maybeTags: maybeTags.apply(this.maybeTags),
    dimensions: dimensions ?? this.dimensions,
    shelf: shelf ?? this.shelf,
    ref: ref ?? this.ref,
    loose: loose ?? this.loose,
  );
}

mixin _$Loose on DwDataObject {
  Loose get _self => this as Loose;

  @override
  String get dwTypeName => 'Loose';

  @override
  Map<String, Object?> toJson() => {'id': _self.id};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Loose && other.id == _self.id;

  @override
  int get hashCode => _self.id.hashCode;

  @override
  String toString() => 'Loose(id: ${_self.id})';
}

Loose $LooseFromJson(Map<String, Object?> json) =>
    Loose(id: json['id']! as String);

extension LooseCopyWith on Loose {
  Loose copyWith({String? id}) => Loose(id: id ?? this.id);
}

mixin _$SearchItems on DwListRequest<Item> {
  SearchItems get _self => this as SearchItems;

  @override
  String get dwTypeName => 'SearchItems';

  @override
  Map<String, Object?> toJson() => {
    if (_self.query != '') 'query': _self.query,
    if (_self.limit != 20) 'limit': _self.limit,
    if (!dwListEquals(_self.colors, const <Color>[Color.red, Color.blue]))
      'colors': [for (final e in _self.colors) e.name],
    if (_self.since != null) 'since': DwJsonCodec.encodeDateTime(_self.since!),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchItems &&
          other.query == _self.query &&
          other.limit == _self.limit &&
          dwListEquals(other.colors, _self.colors) &&
          other.since == _self.since;

  @override
  int get hashCode => Object.hash(
    SearchItems,
    _self.query,
    _self.limit,
    Object.hashAll(_self.colors),
    _self.since,
  );

  @override
  String toString() =>
      'SearchItems(query: ${_self.query}, limit: ${_self.limit}, colors: ${_self.colors}, since: ${_self.since})';
}

SearchItems $SearchItemsFromJson(Map<String, Object?> json) => SearchItems(
  query: json['query'] == null ? '' : json['query']! as String,
  limit: json['limit'] == null ? 20 : json['limit']! as int,
  colors: json['colors'] == null
      ? const <Color>[Color.red, Color.blue]
      : DwJsonCodec.decodeList(
          json['colors'],
          (e) => DwJsonCodec.decodeEnum(e, Color.values),
        ),
  since: json['since'] == null
      ? null
      : DwJsonCodec.decodeDateTime(json['since']),
);

mixin _$UpdateSettings on DwActionCommand<void> {
  UpdateSettings get _self => this as UpdateSettings;

  @override
  String get dwTypeName => 'UpdateSettings';

  @override
  Map<String, Object?> toJson() {
    final json = <String, Object?>{
      'settingsId': _self.settingsId,
      if (!_self.notify) 'notify': _self.notify,
    };
    DwJsonCodec.writePatch(json, 'title', _self.title, (v) => v);
    return json;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateSettings &&
          other.settingsId == _self.settingsId &&
          other.title == _self.title &&
          other.notify == _self.notify;

  @override
  int get hashCode =>
      Object.hash(UpdateSettings, _self.settingsId, _self.title, _self.notify);
}

UpdateSettings $UpdateSettingsFromJson(Map<String, Object?> json) =>
    UpdateSettings(
      settingsId: json['settingsId']! as int,
      title: DwJsonCodec.readPatch(json, 'title', (v) => v! as String),
      notify: json['notify'] == null ? true : json['notify']! as bool,
    );
