// GENERATED BY dartway generate. DO NOT EDIT.
import 'package:dartway_core_shared/dartway_core_shared.dart';

import '../src/catalog.dart';
import '../src/defaults.dart';
import '../src/units.dart';

final DwWireProtocol appProtocol = DwWireProtocol(
  [
    DwProtocolEntry<Dimensions>('Dimensions', $DimensionsFromJson),
    DwProtocolEntry<EditItem>('EditItem', $EditItemFromJson),
    DwProtocolEntry<FeedItems>('FeedItems', $FeedItemsFromJson),
    DwProtocolEntry<FindItem>('FindItem', $FindItemFromJson),
    DwProtocolEntry<GetItem>('GetItem', $GetItemFromJson),
    DwProtocolEntry<Item>('Item', $ItemFromJson),
    DwProtocolEntry<ItemHistory>('ItemHistory', $ItemHistoryFromJson),
    DwProtocolEntry<ItemTable>('ItemTable', $ItemTableFromJson),
    DwProtocolEntry<ListItems>('ListItems', $ListItemsFromJson),
    DwProtocolEntry<ListPinnedItems>(
      'ListPinnedItems',
      $ListPinnedItemsFromJson,
    ),
    DwProtocolEntry<Loose>('Loose', $LooseFromJson),
    DwProtocolEntry<OnlyPatches>('OnlyPatches', $OnlyPatchesFromJson),
    DwProtocolEntry<Ref>('Ref', $RefFromJson),
    DwProtocolEntry<RemoveItem>('RemoveItem', $RemoveItemFromJson),
    DwProtocolEntry<SearchItems>('SearchItems', $SearchItemsFromJson),
    DwProtocolEntry<SessionHolder>('SessionHolder', $SessionHolderFromJson),
    DwProtocolEntry<Settings>('Settings', $SettingsFromJson),
    DwProtocolEntry<Stats>('Stats', $StatsFromJson),
    DwProtocolEntry<UpdateSettings>('UpdateSettings', $UpdateSettingsFromJson),
    DwProtocolEntry<WideRequest>('WideRequest', $WideRequestFromJson),
  ],
  include: DwWireProtocol.core,
  contractVersion: '0.1.0',
);
