// GENERATED BY dartway generate. DO NOT EDIT.
import 'package:dartway_core/dartway_core.dart';

import '../src/catalog.dart';
import '../src/units.dart';

final DwProtocol appProtocol = DwProtocol([
  DwDtoEntry<Dimensions>('Dimensions', $DimensionsFromJson),
  DwDtoEntry<EditItem>('EditItem', $EditItemFromJson),
  DwDtoEntry<FeedItems>('FeedItems', $FeedItemsFromJson),
  DwDtoEntry<FindItem>('FindItem', $FindItemFromJson),
  DwDtoEntry<GetItem>('GetItem', $GetItemFromJson),
  DwDtoEntry<Item>('Item', $ItemFromJson),
  DwDtoEntry<ItemHistory>('ItemHistory', $ItemHistoryFromJson),
  DwDtoEntry<ItemTable>('ItemTable', $ItemTableFromJson),
  DwDtoEntry<ListItems>('ListItems', $ListItemsFromJson),
  DwDtoEntry<ListPinnedItems>('ListPinnedItems', $ListPinnedItemsFromJson),
  DwDtoEntry<OnlyPatches>('OnlyPatches', $OnlyPatchesFromJson),
  DwDtoEntry<Ref>('Ref', $RefFromJson),
  DwDtoEntry<RemoveItem>('RemoveItem', $RemoveItemFromJson),
  DwDtoEntry<SessionHolder>('SessionHolder', $SessionHolderFromJson),
  DwDtoEntry<Stats>('Stats', $StatsFromJson),
  DwDtoEntry<WideRequest>('WideRequest', $WideRequestFromJson),
], include: DwProtocol.core);
