// GENERATED BY dartway generate. DO NOT EDIT.
part of 'units.dart';

mixin _$Dimensions on DwDataObject {
  Dimensions get _self => this as Dimensions;

  @override
  String get dwTypeName => 'Dimensions';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'width': _self.width,
    if (_self.height != null) 'height': _self.height,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Dimensions &&
          other.id == _self.id &&
          other.width == _self.width &&
          other.height == _self.height;

  @override
  int get hashCode => Object.hash(_self.id, _self.width, _self.height);

  @override
  String toString() =>
      'Dimensions(id: ${_self.id}, width: ${_self.width}, height: ${_self.height})';
}

Dimensions $DimensionsFromJson(Map<String, Object?> json) => Dimensions(
  id: json['id']! as String,
  width: DwJson.decodeDouble(json['width']),
  height: json['height'] == null ? null : DwJson.decodeDouble(json['height']),
);

extension DimensionsCopyWith on Dimensions {
  Dimensions copyWith({
    String? id,
    double? width,
    DwPatch<double> height = const DwPatch.keep(),
  }) => Dimensions(
    id: id ?? this.id,
    width: width ?? this.width,
    height: height.apply(this.height),
  );
}
