// GENERATED BY dartway generate. DO NOT EDIT.
part of 'chat_rows.dart';

mixin _$ChatChannelRow on DwTableRow {
  ChatChannelRow get _self => this as ChatChannelRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChannelRow &&
          other.id == _self.id &&
          other.slug == _self.slug &&
          other.title == _self.title;

  @override
  int get hashCode => Object.hash(_self.id, _self.slug, _self.title);

  @override
  String toString() =>
      'ChatChannelRow(id: ${_self.id}, slug: ${_self.slug}, title: ${_self.title})';
}

extension ChatChannelRowCopyWith on ChatChannelRow {
  ChatChannelRow copyWith({String? slug, String? title}) => ChatChannelRow(
    id: id,
    slug: slug ?? this.slug,
    title: title ?? this.title,
  );
}

mixin _$NewChatChannelRow on DwRowDraft<ChatChannelRow> {
  NewChatChannelRow get _self => this as NewChatChannelRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewChatChannelRow &&
          other.slug == _self.slug &&
          other.title == _self.title;

  @override
  int get hashCode => Object.hash(_self.slug, _self.title);

  @override
  String toString() =>
      'NewChatChannelRow(slug: ${_self.slug}, title: ${_self.title})';
}

/// A [ChatChannelRow] before insert: every column but the id.
final class NewChatChannelRow extends DwRowDraft<ChatChannelRow>
    with _$NewChatChannelRow {
  const NewChatChannelRow({required this.slug, required this.title});

  final String slug;
  final String title;
}

extension NewChatChannelRowCopyWith on NewChatChannelRow {
  NewChatChannelRow copyWith({String? slug, String? title}) =>
      NewChatChannelRow(slug: slug ?? this.slug, title: title ?? this.title);
}

extension NewChatChannelRowWithId on NewChatChannelRow {
  /// The row stored under [id], for `update`.
  ChatChannelRow withId(int id) =>
      ChatChannelRow(id: id, slug: slug, title: title);
}

final class ChatChannelTable extends DwTableDef<ChatChannelRow> {
  const ChatChannelTable() : super('chat_channel');

  DwTableColumn<String> get slug =>
      const DwTableColumn('slug', DwColumnType.text, unique: true);

  DwTableColumn<String> get title =>
      const DwTableColumn('title', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [id, slug, title];

  @override
  ChatChannelRow fromRow(DwResultRow row) => ChatChannelRow(
    id: row.decode(id),
    slug: row.decode(slug),
    title: row.decode(title),
  );

  @override
  Map<String, Object?> toRow(ChatChannelRow row) => {
    'slug': row.slug,
    'title': row.title,
  };

  @override
  Map<String, Object?> toDraftRow(NewChatChannelRow draft) => {
    'slug': draft.slug,
    'title': draft.title,
  };
}

mixin _$ChatMessageRow on DwTableRow {
  ChatMessageRow get _self => this as ChatMessageRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageRow &&
          other.id == _self.id &&
          other.channelId == _self.channelId &&
          other.authorProfileId == _self.authorProfileId &&
          other.text == _self.text &&
          other.sentAt == _self.sentAt &&
          other.editedAt == _self.editedAt &&
          other.pinnedAt == _self.pinnedAt &&
          other.pinnedByProfileId == _self.pinnedByProfileId &&
          other.replyToMessageId == _self.replyToMessageId &&
          other.deletedAt == _self.deletedAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.channelId,
    _self.authorProfileId,
    _self.text,
    _self.sentAt,
    _self.editedAt,
    _self.pinnedAt,
    _self.pinnedByProfileId,
    _self.replyToMessageId,
    _self.deletedAt,
  );

  @override
  String toString() =>
      'ChatMessageRow(id: ${_self.id}, channelId: ${_self.channelId}, authorProfileId: ${_self.authorProfileId}, text: ${_self.text}, sentAt: ${_self.sentAt}, editedAt: ${_self.editedAt}, pinnedAt: ${_self.pinnedAt}, pinnedByProfileId: ${_self.pinnedByProfileId}, replyToMessageId: ${_self.replyToMessageId}, deletedAt: ${_self.deletedAt})';
}

extension ChatMessageRowCopyWith on ChatMessageRow {
  ChatMessageRow copyWith({
    int? channelId,
    int? authorProfileId,
    String? text,
    DateTime? sentAt,
    DwFieldPatch<DateTime> editedAt = const DwFieldPatch.keep(),
    DwFieldPatch<DateTime> pinnedAt = const DwFieldPatch.keep(),
    DwFieldPatch<int> pinnedByProfileId = const DwFieldPatch.keep(),
    DwFieldPatch<int> replyToMessageId = const DwFieldPatch.keep(),
    DwFieldPatch<DateTime> deletedAt = const DwFieldPatch.keep(),
  }) => ChatMessageRow(
    id: id,
    channelId: channelId ?? this.channelId,
    authorProfileId: authorProfileId ?? this.authorProfileId,
    text: text ?? this.text,
    sentAt: sentAt ?? this.sentAt,
    editedAt: editedAt.apply(this.editedAt),
    pinnedAt: pinnedAt.apply(this.pinnedAt),
    pinnedByProfileId: pinnedByProfileId.apply(this.pinnedByProfileId),
    replyToMessageId: replyToMessageId.apply(this.replyToMessageId),
    deletedAt: deletedAt.apply(this.deletedAt),
  );
}

mixin _$NewChatMessageRow on DwRowDraft<ChatMessageRow> {
  NewChatMessageRow get _self => this as NewChatMessageRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewChatMessageRow &&
          other.channelId == _self.channelId &&
          other.authorProfileId == _self.authorProfileId &&
          other.text == _self.text &&
          other.sentAt == _self.sentAt &&
          other.editedAt == _self.editedAt &&
          other.pinnedAt == _self.pinnedAt &&
          other.pinnedByProfileId == _self.pinnedByProfileId &&
          other.replyToMessageId == _self.replyToMessageId &&
          other.deletedAt == _self.deletedAt;

  @override
  int get hashCode => Object.hash(
    _self.channelId,
    _self.authorProfileId,
    _self.text,
    _self.sentAt,
    _self.editedAt,
    _self.pinnedAt,
    _self.pinnedByProfileId,
    _self.replyToMessageId,
    _self.deletedAt,
  );

  @override
  String toString() =>
      'NewChatMessageRow(channelId: ${_self.channelId}, authorProfileId: ${_self.authorProfileId}, text: ${_self.text}, sentAt: ${_self.sentAt}, editedAt: ${_self.editedAt}, pinnedAt: ${_self.pinnedAt}, pinnedByProfileId: ${_self.pinnedByProfileId}, replyToMessageId: ${_self.replyToMessageId}, deletedAt: ${_self.deletedAt})';
}

/// A [ChatMessageRow] before insert: every column but the id.
final class NewChatMessageRow extends DwRowDraft<ChatMessageRow>
    with _$NewChatMessageRow {
  const NewChatMessageRow({
    required this.channelId,
    required this.authorProfileId,
    required this.text,
    required this.sentAt,
    this.editedAt,
    this.pinnedAt,
    this.pinnedByProfileId,
    this.replyToMessageId,
    this.deletedAt,
  });

  final int channelId;
  final int authorProfileId;
  final String text;
  final DateTime sentAt;
  final DateTime? editedAt;
  final DateTime? pinnedAt;
  final int? pinnedByProfileId;
  final int? replyToMessageId;
  final DateTime? deletedAt;
}

extension NewChatMessageRowCopyWith on NewChatMessageRow {
  NewChatMessageRow copyWith({
    int? channelId,
    int? authorProfileId,
    String? text,
    DateTime? sentAt,
    DwFieldPatch<DateTime> editedAt = const DwFieldPatch.keep(),
    DwFieldPatch<DateTime> pinnedAt = const DwFieldPatch.keep(),
    DwFieldPatch<int> pinnedByProfileId = const DwFieldPatch.keep(),
    DwFieldPatch<int> replyToMessageId = const DwFieldPatch.keep(),
    DwFieldPatch<DateTime> deletedAt = const DwFieldPatch.keep(),
  }) => NewChatMessageRow(
    channelId: channelId ?? this.channelId,
    authorProfileId: authorProfileId ?? this.authorProfileId,
    text: text ?? this.text,
    sentAt: sentAt ?? this.sentAt,
    editedAt: editedAt.apply(this.editedAt),
    pinnedAt: pinnedAt.apply(this.pinnedAt),
    pinnedByProfileId: pinnedByProfileId.apply(this.pinnedByProfileId),
    replyToMessageId: replyToMessageId.apply(this.replyToMessageId),
    deletedAt: deletedAt.apply(this.deletedAt),
  );
}

extension NewChatMessageRowWithId on NewChatMessageRow {
  /// The row stored under [id], for `update`.
  ChatMessageRow withId(int id) => ChatMessageRow(
    id: id,
    channelId: channelId,
    authorProfileId: authorProfileId,
    text: text,
    sentAt: sentAt,
    editedAt: editedAt,
    pinnedAt: pinnedAt,
    pinnedByProfileId: pinnedByProfileId,
    replyToMessageId: replyToMessageId,
    deletedAt: deletedAt,
  );
}

final class ChatMessageTable extends DwTableDef<ChatMessageRow> {
  const ChatMessageTable() : super('chat_message');

  DwTableColumn<int> get channelId => const DwTableColumn(
    'channel_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_channel', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get authorProfileId => const DwTableColumn(
    'author_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<String> get text =>
      const DwTableColumn('text', DwColumnType.text);

  DwTableColumn<DateTime> get sentAt =>
      const DwTableColumn('sent_at', DwColumnType.timestamptz);

  DwTableColumn<DateTime?> get editedAt =>
      const DwTableColumn('edited_at', DwColumnType.timestamptz);

  DwTableColumn<DateTime?> get pinnedAt =>
      const DwTableColumn('pinned_at', DwColumnType.timestamptz);

  DwTableColumn<int?> get pinnedByProfileId => const DwTableColumn(
    'pinned_by_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.setNull),
  );

  DwTableColumn<int?> get replyToMessageId => const DwTableColumn(
    'reply_to_message_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_message', onDelete: DwOnDelete.setNull),
  );

  DwTableColumn<DateTime?> get deletedAt =>
      const DwTableColumn('deleted_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    channelId,
    authorProfileId,
    text,
    sentAt,
    editedAt,
    pinnedAt,
    pinnedByProfileId,
    replyToMessageId,
    deletedAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('chat_message_channel_id_sent_at_id_idx', [
      'channel_id',
      'sent_at',
      'id',
    ]),
  ];

  @override
  ChatMessageRow fromRow(DwResultRow row) => ChatMessageRow(
    id: row.decode(id),
    channelId: row.decode(channelId),
    authorProfileId: row.decode(authorProfileId),
    text: row.decode(text),
    sentAt: row.decode(sentAt),
    editedAt: row.decode(editedAt),
    pinnedAt: row.decode(pinnedAt),
    pinnedByProfileId: row.decode(pinnedByProfileId),
    replyToMessageId: row.decode(replyToMessageId),
    deletedAt: row.decode(deletedAt),
  );

  @override
  Map<String, Object?> toRow(ChatMessageRow row) => {
    'channel_id': row.channelId,
    'author_profile_id': row.authorProfileId,
    'text': row.text,
    'sent_at': row.sentAt,
    'edited_at': row.editedAt,
    'pinned_at': row.pinnedAt,
    'pinned_by_profile_id': row.pinnedByProfileId,
    'reply_to_message_id': row.replyToMessageId,
    'deleted_at': row.deletedAt,
  };

  @override
  Map<String, Object?> toDraftRow(NewChatMessageRow draft) => {
    'channel_id': draft.channelId,
    'author_profile_id': draft.authorProfileId,
    'text': draft.text,
    'sent_at': draft.sentAt,
    'edited_at': draft.editedAt,
    'pinned_at': draft.pinnedAt,
    'pinned_by_profile_id': draft.pinnedByProfileId,
    'reply_to_message_id': draft.replyToMessageId,
    'deleted_at': draft.deletedAt,
  };
}

mixin _$ChatMessageAttachmentRow on DwTableRow {
  ChatMessageAttachmentRow get _self => this as ChatMessageAttachmentRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageAttachmentRow &&
          other.id == _self.id &&
          other.messageId == _self.messageId &&
          other.fileId == _self.fileId &&
          other.position == _self.position &&
          other.width == _self.width &&
          other.height == _self.height;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.messageId,
    _self.fileId,
    _self.position,
    _self.width,
    _self.height,
  );

  @override
  String toString() =>
      'ChatMessageAttachmentRow(id: ${_self.id}, messageId: ${_self.messageId}, fileId: ${_self.fileId}, position: ${_self.position}, width: ${_self.width}, height: ${_self.height})';
}

extension ChatMessageAttachmentRowCopyWith on ChatMessageAttachmentRow {
  ChatMessageAttachmentRow copyWith({
    int? messageId,
    int? fileId,
    int? position,
    DwFieldPatch<int> width = const DwFieldPatch.keep(),
    DwFieldPatch<int> height = const DwFieldPatch.keep(),
  }) => ChatMessageAttachmentRow(
    id: id,
    messageId: messageId ?? this.messageId,
    fileId: fileId ?? this.fileId,
    position: position ?? this.position,
    width: width.apply(this.width),
    height: height.apply(this.height),
  );
}

mixin _$NewChatMessageAttachmentRow on DwRowDraft<ChatMessageAttachmentRow> {
  NewChatMessageAttachmentRow get _self => this as NewChatMessageAttachmentRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewChatMessageAttachmentRow &&
          other.messageId == _self.messageId &&
          other.fileId == _self.fileId &&
          other.position == _self.position &&
          other.width == _self.width &&
          other.height == _self.height;

  @override
  int get hashCode => Object.hash(
    _self.messageId,
    _self.fileId,
    _self.position,
    _self.width,
    _self.height,
  );

  @override
  String toString() =>
      'NewChatMessageAttachmentRow(messageId: ${_self.messageId}, fileId: ${_self.fileId}, position: ${_self.position}, width: ${_self.width}, height: ${_self.height})';
}

/// A [ChatMessageAttachmentRow] before insert: every column but the id.
final class NewChatMessageAttachmentRow
    extends DwRowDraft<ChatMessageAttachmentRow>
    with _$NewChatMessageAttachmentRow {
  const NewChatMessageAttachmentRow({
    required this.messageId,
    required this.fileId,
    required this.position,
    this.width,
    this.height,
  });

  final int messageId;
  final int fileId;
  final int position;
  final int? width;
  final int? height;
}

extension NewChatMessageAttachmentRowCopyWith on NewChatMessageAttachmentRow {
  NewChatMessageAttachmentRow copyWith({
    int? messageId,
    int? fileId,
    int? position,
    DwFieldPatch<int> width = const DwFieldPatch.keep(),
    DwFieldPatch<int> height = const DwFieldPatch.keep(),
  }) => NewChatMessageAttachmentRow(
    messageId: messageId ?? this.messageId,
    fileId: fileId ?? this.fileId,
    position: position ?? this.position,
    width: width.apply(this.width),
    height: height.apply(this.height),
  );
}

extension NewChatMessageAttachmentRowWithId on NewChatMessageAttachmentRow {
  /// The row stored under [id], for `update`.
  ChatMessageAttachmentRow withId(int id) => ChatMessageAttachmentRow(
    id: id,
    messageId: messageId,
    fileId: fileId,
    position: position,
    width: width,
    height: height,
  );
}

final class ChatMessageAttachmentTable
    extends DwTableDef<ChatMessageAttachmentRow> {
  const ChatMessageAttachmentTable() : super('chat_message_attachment');

  DwTableColumn<int> get messageId => const DwTableColumn(
    'message_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_message', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get fileId => const DwTableColumn(
    'file_id',
    DwColumnType.bigint,
    unique: true,
    references: DwForeignKey('dw_stored_file', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get position =>
      const DwTableColumn('position', DwColumnType.bigint);

  DwTableColumn<int?> get width =>
      const DwTableColumn('width', DwColumnType.bigint);

  DwTableColumn<int?> get height =>
      const DwTableColumn('height', DwColumnType.bigint);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    messageId,
    fileId,
    position,
    width,
    height,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('chat_message_attachment_message_id_position_idx', [
      'message_id',
      'position',
    ]),
  ];

  @override
  ChatMessageAttachmentRow fromRow(DwResultRow row) => ChatMessageAttachmentRow(
    id: row.decode(id),
    messageId: row.decode(messageId),
    fileId: row.decode(fileId),
    position: row.decode(position),
    width: row.decode(width),
    height: row.decode(height),
  );

  @override
  Map<String, Object?> toRow(ChatMessageAttachmentRow row) => {
    'message_id': row.messageId,
    'file_id': row.fileId,
    'position': row.position,
    'width': row.width,
    'height': row.height,
  };

  @override
  Map<String, Object?> toDraftRow(NewChatMessageAttachmentRow draft) => {
    'message_id': draft.messageId,
    'file_id': draft.fileId,
    'position': draft.position,
    'width': draft.width,
    'height': draft.height,
  };
}

mixin _$ChatMessageReactionRow on DwTableRow {
  ChatMessageReactionRow get _self => this as ChatMessageReactionRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageReactionRow &&
          other.id == _self.id &&
          other.messageId == _self.messageId &&
          other.profileId == _self.profileId &&
          other.reaction == _self.reaction;

  @override
  int get hashCode =>
      Object.hash(_self.id, _self.messageId, _self.profileId, _self.reaction);

  @override
  String toString() =>
      'ChatMessageReactionRow(id: ${_self.id}, messageId: ${_self.messageId}, profileId: ${_self.profileId}, reaction: ${_self.reaction})';
}

extension ChatMessageReactionRowCopyWith on ChatMessageReactionRow {
  ChatMessageReactionRow copyWith({
    int? messageId,
    int? profileId,
    ChatReaction? reaction,
  }) => ChatMessageReactionRow(
    id: id,
    messageId: messageId ?? this.messageId,
    profileId: profileId ?? this.profileId,
    reaction: reaction ?? this.reaction,
  );
}

mixin _$NewChatMessageReactionRow on DwRowDraft<ChatMessageReactionRow> {
  NewChatMessageReactionRow get _self => this as NewChatMessageReactionRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewChatMessageReactionRow &&
          other.messageId == _self.messageId &&
          other.profileId == _self.profileId &&
          other.reaction == _self.reaction;

  @override
  int get hashCode =>
      Object.hash(_self.messageId, _self.profileId, _self.reaction);

  @override
  String toString() =>
      'NewChatMessageReactionRow(messageId: ${_self.messageId}, profileId: ${_self.profileId}, reaction: ${_self.reaction})';
}

/// A [ChatMessageReactionRow] before insert: every column but the id.
final class NewChatMessageReactionRow extends DwRowDraft<ChatMessageReactionRow>
    with _$NewChatMessageReactionRow {
  const NewChatMessageReactionRow({
    required this.messageId,
    required this.profileId,
    required this.reaction,
  });

  final int messageId;
  final int profileId;
  final ChatReaction reaction;
}

extension NewChatMessageReactionRowCopyWith on NewChatMessageReactionRow {
  NewChatMessageReactionRow copyWith({
    int? messageId,
    int? profileId,
    ChatReaction? reaction,
  }) => NewChatMessageReactionRow(
    messageId: messageId ?? this.messageId,
    profileId: profileId ?? this.profileId,
    reaction: reaction ?? this.reaction,
  );
}

extension NewChatMessageReactionRowWithId on NewChatMessageReactionRow {
  /// The row stored under [id], for `update`.
  ChatMessageReactionRow withId(int id) => ChatMessageReactionRow(
    id: id,
    messageId: messageId,
    profileId: profileId,
    reaction: reaction,
  );
}

final class ChatMessageReactionTable
    extends DwTableDef<ChatMessageReactionRow> {
  const ChatMessageReactionTable() : super('chat_message_reaction');

  DwTableColumn<int> get messageId => const DwTableColumn(
    'message_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_message', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get profileId => const DwTableColumn(
    'profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<ChatReaction> get reaction =>
      const DwTableColumn('reaction', DwEnumType(ChatReaction.values));

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    messageId,
    profileId,
    reaction,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('chat_message_reaction_message_id_profile_id_key', [
      'message_id',
      'profile_id',
    ], unique: true),
  ];

  @override
  ChatMessageReactionRow fromRow(DwResultRow row) => ChatMessageReactionRow(
    id: row.decode(id),
    messageId: row.decode(messageId),
    profileId: row.decode(profileId),
    reaction: row.decode(reaction),
  );

  @override
  Map<String, Object?> toRow(ChatMessageReactionRow row) => {
    'message_id': row.messageId,
    'profile_id': row.profileId,
    'reaction': row.reaction,
  };

  @override
  Map<String, Object?> toDraftRow(NewChatMessageReactionRow draft) => {
    'message_id': draft.messageId,
    'profile_id': draft.profileId,
    'reaction': draft.reaction,
  };
}

mixin _$ChatReadPositionRow on DwTableRow {
  ChatReadPositionRow get _self => this as ChatReadPositionRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatReadPositionRow &&
          other.id == _self.id &&
          other.profileId == _self.profileId &&
          other.channelId == _self.channelId &&
          other.messageId == _self.messageId &&
          other.sentAt == _self.sentAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.profileId,
    _self.channelId,
    _self.messageId,
    _self.sentAt,
  );

  @override
  String toString() =>
      'ChatReadPositionRow(id: ${_self.id}, profileId: ${_self.profileId}, channelId: ${_self.channelId}, messageId: ${_self.messageId}, sentAt: ${_self.sentAt})';
}

extension ChatReadPositionRowCopyWith on ChatReadPositionRow {
  ChatReadPositionRow copyWith({
    int? profileId,
    int? channelId,
    int? messageId,
    DateTime? sentAt,
  }) => ChatReadPositionRow(
    id: id,
    profileId: profileId ?? this.profileId,
    channelId: channelId ?? this.channelId,
    messageId: messageId ?? this.messageId,
    sentAt: sentAt ?? this.sentAt,
  );
}

mixin _$NewChatReadPositionRow on DwRowDraft<ChatReadPositionRow> {
  NewChatReadPositionRow get _self => this as NewChatReadPositionRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewChatReadPositionRow &&
          other.profileId == _self.profileId &&
          other.channelId == _self.channelId &&
          other.messageId == _self.messageId &&
          other.sentAt == _self.sentAt;

  @override
  int get hashCode => Object.hash(
    _self.profileId,
    _self.channelId,
    _self.messageId,
    _self.sentAt,
  );

  @override
  String toString() =>
      'NewChatReadPositionRow(profileId: ${_self.profileId}, channelId: ${_self.channelId}, messageId: ${_self.messageId}, sentAt: ${_self.sentAt})';
}

/// A [ChatReadPositionRow] before insert: every column but the id.
final class NewChatReadPositionRow extends DwRowDraft<ChatReadPositionRow>
    with _$NewChatReadPositionRow {
  const NewChatReadPositionRow({
    required this.profileId,
    required this.channelId,
    required this.messageId,
    required this.sentAt,
  });

  final int profileId;
  final int channelId;
  final int messageId;
  final DateTime sentAt;
}

extension NewChatReadPositionRowCopyWith on NewChatReadPositionRow {
  NewChatReadPositionRow copyWith({
    int? profileId,
    int? channelId,
    int? messageId,
    DateTime? sentAt,
  }) => NewChatReadPositionRow(
    profileId: profileId ?? this.profileId,
    channelId: channelId ?? this.channelId,
    messageId: messageId ?? this.messageId,
    sentAt: sentAt ?? this.sentAt,
  );
}

extension NewChatReadPositionRowWithId on NewChatReadPositionRow {
  /// The row stored under [id], for `update`.
  ChatReadPositionRow withId(int id) => ChatReadPositionRow(
    id: id,
    profileId: profileId,
    channelId: channelId,
    messageId: messageId,
    sentAt: sentAt,
  );
}

final class ChatReadPositionTable extends DwTableDef<ChatReadPositionRow> {
  const ChatReadPositionTable() : super('chat_read_position');

  DwTableColumn<int> get profileId => const DwTableColumn(
    'profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get channelId => const DwTableColumn(
    'channel_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_channel', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<int> get messageId => const DwTableColumn(
    'message_id',
    DwColumnType.bigint,
    references: DwForeignKey('chat_message', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<DateTime> get sentAt =>
      const DwTableColumn('sent_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    profileId,
    channelId,
    messageId,
    sentAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('chat_read_position_profile_id_channel_id_key', [
      'profile_id',
      'channel_id',
    ], unique: true),
  ];

  @override
  ChatReadPositionRow fromRow(DwResultRow row) => ChatReadPositionRow(
    id: row.decode(id),
    profileId: row.decode(profileId),
    channelId: row.decode(channelId),
    messageId: row.decode(messageId),
    sentAt: row.decode(sentAt),
  );

  @override
  Map<String, Object?> toRow(ChatReadPositionRow row) => {
    'profile_id': row.profileId,
    'channel_id': row.channelId,
    'message_id': row.messageId,
    'sent_at': row.sentAt,
  };

  @override
  Map<String, Object?> toDraftRow(NewChatReadPositionRow draft) => {
    'profile_id': draft.profileId,
    'channel_id': draft.channelId,
    'message_id': draft.messageId,
    'sent_at': draft.sentAt,
  };
}
