// GENERATED BY dartway generate. DO NOT EDIT.
part of 'club_booking.dart';

mixin _$ClubBooking on DwDataObject {
  ClubBooking get _self => this as ClubBooking;

  @override
  String get dwTypeName => 'ClubBooking';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'status': _self.status.name,
    'startsAt': DwJson.encodeDateTime(_self.startsAt),
    if (_self.note != null) 'note': _self.note,
    if (_self.tags.isNotEmpty) 'tags': _self.tags,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClubBooking &&
          other.id == _self.id &&
          other.status == _self.status &&
          other.startsAt == _self.startsAt &&
          other.note == _self.note &&
          dwListEquals(other.tags, _self.tags);

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.status,
    _self.startsAt,
    _self.note,
    Object.hashAll(_self.tags),
  );

  @override
  String toString() =>
      'ClubBooking(id: ${_self.id}, status: ${_self.status}, startsAt: ${_self.startsAt}, note: ${_self.note}, tags: ${_self.tags})';
}

ClubBooking $ClubBookingFromJson(Map<String, Object?> json) => ClubBooking(
  id: json['id']! as int,
  status: DwJson.decodeEnum(json['status'], BookingStatus.values),
  startsAt: DwJson.decodeDateTime(json['startsAt']),
  note: json['note'] as String?,
  tags: json['tags'] == null
      ? const []
      : DwJson.decodeList(json['tags'], (e) => e! as String),
);

extension ClubBookingCopyWith on ClubBooking {
  ClubBooking copyWith({
    int? id,
    BookingStatus? status,
    DateTime? startsAt,
    DwPatch<String> note = const DwPatch.keep(),
    List<String>? tags,
  }) => ClubBooking(
    id: id ?? this.id,
    status: status ?? this.status,
    startsAt: startsAt ?? this.startsAt,
    note: note.apply(this.note),
    tags: tags ?? this.tags,
  );
}

mixin _$ListMyBookings on DwListRequest<ClubBooking> {
  ListMyBookings get _self => this as ListMyBookings;

  @override
  String get dwTypeName => 'ListMyBookings';

  @override
  Map<String, Object?> toJson() => {
    if (_self.status != null) 'status': _self.status!.name,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListMyBookings && other.status == _self.status;

  @override
  int get hashCode => Object.hash(ListMyBookings, _self.status);

  @override
  String toString() => 'ListMyBookings(status: ${_self.status})';
}

ListMyBookings $ListMyBookingsFromJson(Map<String, Object?> json) =>
    ListMyBookings(
      status: json['status'] == null
          ? null
          : DwJson.decodeEnum(json['status'], BookingStatus.values),
    );

mixin _$RenameBooking on DwCommand<ClubBooking> {
  RenameBooking get _self => this as RenameBooking;

  @override
  String get dwTypeName => 'RenameBooking';

  @override
  Map<String, Object?> toJson() {
    final json = <String, Object?>{'bookingId': _self.bookingId};
    DwJson.writePatch(json, 'note', _self.note, (v) => v);
    return json;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenameBooking &&
          other.bookingId == _self.bookingId &&
          other.note == _self.note;

  @override
  int get hashCode => Object.hash(RenameBooking, _self.bookingId, _self.note);
}

RenameBooking $RenameBookingFromJson(Map<String, Object?> json) =>
    RenameBooking(
      bookingId: json['bookingId']! as int,
      note: DwJson.readPatch(json, 'note', (v) => v! as String),
    );
