// GENERATED BY wire_golden_test.dart. DO NOT EDIT.
//
// The canonical wire encodings of dartway_core_shared and the
// protocol version they were recorded at (D-052). Refresh after
// bumping dwProtocolVersion:
//   DW_UPDATE_GOLDENS=1 dart test test/wire_golden_test.dart

const String wireGolden = r'''
{
  "protocolVersion": 2,
  "shapes": {
    "http.contract": {
      "callPath": "/dw/RenameBooking",
      "livePath": "/dw/live",
      "healthPath": "/health",
      "callMethod": "POST",
      "contentType": "application/json; charset=utf-8",
      "headers": [
        "Authorization",
        "Bearer ",
        "Dw-Idempotency-Key",
        "Dw-Protocol",
        "Dw-App-Version",
        "Dw-Contract-Version",
        "Dw-Live-Connection",
        "Retry-After",
        "Content-Type"
      ],
      "query": [
        "offset",
        "pageSize",
        "anchor",
        "before",
        "after",
        "protocol",
        "app",
        "contract"
      ]
    },
    "http.contractVersion": "0.7.2",
    "http.appVersion": "1.4.2+87",
    "http.closeCodes": {
      "serverStopping": 1001,
      "unsupportedData": 1003,
      "messageTooBig": 1009,
      "internalError": 1011,
      "protocolError": 4000,
      "incompatible": 4026,
      "slowConsumer": 4008
    },
    "call.request.defaults": {},
    "call.request.fields": {
      "status": "cancelled",
      "includePast": true
    },
    "call.command.patchKept": {
      "bookingId": 7
    },
    "call.command.patchSet": {
      "bookingId": 7,
      "note": "Window seat"
    },
    "call.command.patchCleared": {
      "bookingId": 7,
      "note": null
    },
    "call.query.offset": {
      "offset": "40",
      "pageSize": "60"
    },
    "call.query.windowNewest": {},
    "call.query.windowAround": {
      "anchor": "WyJ0IiwxNzg5NDY4MjAwMDAwMDAwLDdd",
      "pageSize": "10"
    },
    "call.query.windowOlder": {
      "before": "WyJ0IiwxNzg5NDY4MjAwMDAwMDAwLDdd"
    },
    "call.query.windowNewer": {
      "after": "WyJ0IiwxNzg5NDY4ODAwMDAwMDAwLDhd"
    },
    "object.defaults": {
      "id": 7,
      "status": "booked",
      "startsAt": 1789468200000000
    },
    "object.fields": {
      "id": 8,
      "status": "cancelled",
      "startsAt": 1789468800000000,
      "note": "Window seat",
      "tags": [
        "yoga",
        "morning"
      ],
      "seats": 2
    },
    "object.deleted": {
      "type": "ClubBooking",
      "id": 8
    },
    "result.list": [
      {
        "id": 7,
        "status": "booked",
        "startsAt": 1789468200000000
      },
      {
        "id": 8,
        "status": "cancelled",
        "startsAt": 1789468800000000,
        "note": "Window seat",
        "tags": [
          "yoga",
          "morning"
        ],
        "seats": 2
      }
    ],
    "result.page": {
      "items": [
        {
          "id": 7,
          "status": "booked",
          "startsAt": 1789468200000000
        }
      ],
      "hasMore": true
    },
    "result.table": {
      "items": [
        {
          "id": 7,
          "status": "booked",
          "startsAt": 1789468200000000
        }
      ],
      "total": 41,
      "page": 3,
      "pageSize": 20
    },
    "result.window": {
      "items": [
        {
          "id": 8,
          "status": "cancelled",
          "startsAt": 1789468800000000,
          "note": "Window seat",
          "tags": [
            "yoga",
            "morning"
          ],
          "seats": 2
        },
        {
          "id": 7,
          "status": "booked",
          "startsAt": 1789468200000000
        }
      ],
      "olderCursor": "WyJ0IiwxNzg5NDY4MjAwMDAwMDAwLDdd",
      "newerCursor": "WyJ0IiwxNzg5NDY4ODAwMDAwMDAwLDhd"
    },
    "result.cursors": [
      "WyJ0IiwxNzg5NDY4MjAwMDAwMDAwLDdd",
      "WyJpIiw0MiwiYi03Il0",
      "WyJzIiwiWm_DqyIsN10"
    ],
    "refusal.full": {
      "code": "seatsNotEnough",
      "params": {
        "left": "2"
      },
      "field": "seats"
    },
    "refusal.codes": [
      "dw.forbidden",
      "dw.notFound",
      "dw.conflict",
      "dw.invalid",
      "dw.unknownChannel",
      "dw.tooManyRequests",
      "dw.codeExpired",
      "dw.updateRequired",
      "dw.protocolUnsupported",
      "dw.identifierTaken",
      "dw.uploadPurposeUnknown",
      "dw.uploadTooLarge",
      "dw.uploadTypeRejected",
      "dw.uploadMissing",
      "dw.uploadMismatch",
      "dw.uploadExpired",
      "dw.fileNotOwned"
    ],
    "response.ok": {
      "status": 200,
      "headers": {},
      "body": {
        "status": "ok",
        "result": {
          "id": 7,
          "status": "booked",
          "startsAt": 1789468200000000
        }
      }
    },
    "response.okVoid": {
      "status": 200,
      "headers": {},
      "body": {
        "status": "ok"
      }
    },
    "response.okUpdates": {
      "status": 200,
      "headers": {},
      "body": {
        "status": "ok",
        "result": {
          "id": 8,
          "status": "cancelled",
          "startsAt": 1789468800000000,
          "note": "Window seat",
          "tags": [
            "yoga",
            "morning"
          ],
          "seats": 2
        },
        "updates": {
          "bookings:7": {
            "ClubBooking": [
              {
                "id": 7,
                "status": "booked",
                "startsAt": 1789468200000000
              }
            ],
            "DwDeletedObject": [
              {
                "type": "ClubBooking",
                "id": 8
              }
            ]
          },
          "schedule": {
            "ClubBooking": [
              {
                "id": 8,
                "status": "cancelled",
                "startsAt": 1789468800000000,
                "note": "Window seat",
                "tags": [
                  "yoga",
                  "morning"
                ],
                "seats": 2
              }
            ]
          }
        }
      }
    },
    "response.okReplayed": {
      "status": 200,
      "headers": {},
      "body": {
        "status": "ok",
        "result": {
          "id": 7,
          "status": "booked",
          "startsAt": 1789468200000000
        },
        "replayed": true
      }
    },
    "response.refused": {
      "status": 422,
      "headers": {},
      "body": {
        "status": "refused",
        "refusal": {
          "code": "seatsNotEnough",
          "params": {
            "left": "2"
          },
          "field": "seats"
        }
      }
    },
    "response.refusedForbidden": {
      "status": 403,
      "headers": {},
      "body": {
        "status": "refused",
        "refusal": {
          "code": "dw.forbidden"
        }
      }
    },
    "response.refusedNotFound": {
      "status": 404,
      "headers": {},
      "body": {
        "status": "refused",
        "refusal": {
          "code": "dw.notFound"
        }
      }
    },
    "response.refusedConflict": {
      "status": 409,
      "headers": {},
      "body": {
        "status": "refused",
        "refusal": {
          "code": "dw.conflict"
        }
      }
    },
    "response.refusedTooManyRequests": {
      "status": 429,
      "headers": {
        "Retry-After": "30"
      },
      "body": {
        "status": "refused",
        "refusal": {
          "code": "dw.tooManyRequests",
          "params": {
            "retryAfter": "30"
          }
        }
      }
    },
    "response.unauthenticated": {
      "status": 401,
      "headers": {},
      "body": {
        "status": "unauthenticated"
      }
    },
    "response.failed": {
      "status": 500,
      "headers": {},
      "body": {
        "status": "failed",
        "incidentId": "incident-1"
      }
    },
    "response.failedMalformedCall": {
      "status": 400,
      "headers": {},
      "body": {
        "status": "failed",
        "incidentId": "incident-2",
        "failure": "malformedCall"
      }
    },
    "response.failedUnknownCall": {
      "status": 404,
      "headers": {},
      "body": {
        "status": "failed",
        "incidentId": "incident-3",
        "failure": "unknownCall"
      }
    },
    "response.incompatibleUpdateRequired": {
      "status": 426,
      "headers": {},
      "body": {
        "status": "incompatible",
        "refusal": {
          "code": "dw.updateRequired"
        }
      }
    },
    "response.incompatibleProtocolUnsupported": {
      "status": 426,
      "headers": {},
      "body": {
        "status": "incompatible",
        "refusal": {
          "code": "dw.protocolUnsupported"
        }
      }
    },
    "transport": {
      "bookings:7": {
        "ClubBooking": [
          {
            "id": 7,
            "status": "booked",
            "startsAt": 1789468200000000
          }
        ],
        "DwDeletedObject": [
          {
            "type": "ClubBooking",
            "id": 8
          }
        ]
      },
      "schedule": {
        "ClubBooking": [
          {
            "id": 8,
            "status": "cancelled",
            "startsAt": 1789468800000000,
            "note": "Window seat",
            "tags": [
              "yoga",
              "morning"
            ],
            "seats": 2
          }
        ]
      }
    },
    "channel.wireNames": [
      "schedule",
      "chat:7",
      "chat:general",
      "bookings:7"
    ],
    "live.auth": {
      "k": "auth",
      "token": "token-1"
    },
    "live.authAnonymous": {
      "k": "auth"
    },
    "live.sub": {
      "k": "sub",
      "ch": "bookings:7"
    },
    "live.unsub": {
      "k": "unsub",
      "ch": "bookings:7"
    },
    "live.hello": {
      "k": "hello",
      "connection": "connection-1"
    },
    "live.authed": {
      "k": "authed",
      "account": 7
    },
    "live.authedAnonymous": {
      "k": "authed"
    },
    "live.authedRejected": {
      "k": "authed",
      "rejected": true
    },
    "live.subok": {
      "k": "subok",
      "ch": "bookings:7"
    },
    "live.subnoRefused": {
      "k": "subno",
      "ch": "bookings:8",
      "r": {
        "code": "dw.forbidden"
      }
    },
    "live.subnoUnauthenticated": {
      "k": "subno",
      "ch": "bookings:7"
    },
    "live.subnoFailed": {
      "k": "subno",
      "ch": "bookings:7",
      "x": "incident-4"
    },
    "live.upd": {
      "k": "upd",
      "ch": "bookings:7",
      "updates": {
        "ClubBooking": [
          {
            "id": 7,
            "status": "booked",
            "startsAt": 1789468200000000
          }
        ],
        "DwDeletedObject": [
          {
            "type": "ClubBooking",
            "id": 8
          }
        ]
      }
    },
    "live.closed": {
      "k": "closed",
      "ch": "bookings:7"
    },
    "dto.requestCode": {
      "kind": "phone",
      "identifier": "79990000001"
    },
    "dto.codeTicket": {
      "id": "t-1",
      "expiresAt": 1789468800000000,
      "resendAfter": 1789468200000000
    },
    "dto.verifyCode": {
      "ticketId": "t-1",
      "code": "123456",
      "registration": {
        "firstName": "Ada"
      }
    },
    "dto.verifyCodeDefaults": {
      "ticketId": "t-1",
      "code": "123456"
    },
    "dto.authSession": {
      "id": 7,
      "token": "token-1",
      "isNewAccount": true
    },
    "dto.authSessionDefaults": {
      "id": 7,
      "token": "token-1"
    },
    "dto.signOut": {},
    "dto.deleteMyAccount": {},
    "dto.requestIdentifierCode": {
      "kind": "email",
      "identifier": "ada@example.com"
    },
    "dto.confirmIdentifier": {
      "ticketId": "t-2",
      "code": "654321",
      "replace": true
    },
    "dto.confirmIdentifierDefaults": {
      "ticketId": "t-2",
      "code": "654321"
    },
    "dto.identityInfo": {
      "id": 3,
      "accountId": 7,
      "kind": "email",
      "value": "ada@example.com",
      "createdAt": 1789468200000000,
      "verifiedAt": 1789468800000000
    },
    "dto.sessionKeyInfo": {
      "id": 4,
      "accountId": 7,
      "kind": "personal",
      "label": "CI deploy",
      "createdAt": 1789468200000000,
      "lastUsedAt": 1789468800000000,
      "revokedAt": 1789468800000000
    },
    "dto.startUpload": {
      "purpose": "avatar",
      "fileName": "me.png",
      "contentType": "image/png",
      "byteSize": 2048
    },
    "dto.uploadTicket": {
      "id": 11,
      "uploadUrl": "https://storage.invalid/private/avatar/7/x.png",
      "headers": {
        "content-type": "image/png",
        "if-none-match": "*"
      },
      "expiresAt": 1789468800000000
    },
    "dto.finishUpload": {
      "ticketId": 11
    },
    "dto.storedFile": {
      "id": 11,
      "purpose": "avatar",
      "fileName": "me.png",
      "contentType": "image/png",
      "byteSize": 2048,
      "url": "https://storage.invalid/public/avatar/7/x.png"
    },
    "dto.getFileLink": {
      "fileId": 11
    },
    "dto.fileLink": {
      "id": 11,
      "url": "https://storage.invalid/private/avatar/7/x.png?sig",
      "expiresAt": 1789468800000000
    }
  }
}
''';
