// GENERATED BY dartway generate. DO NOT EDIT.
part of 'defaults.dart';

mixin _$Compose on DwActionCommand<String> {
  Compose get _self => this as Compose;

  @override
  String get dwTypeName => 'Compose';

  @override
  Map<String, Object?> toJson() => {
    'text': _self.text,
    if (_self.times != 2) 'times': _self.times,
    if (_self.separator != ' ') 'separator': _self.separator,
    if (_self.loud) 'loud': _self.loud,
    if (_self.tone != Tone.plain) 'tone': _self.tone.name,
    if (!dwListEquals(_self.tags, const <String>['draft'])) 'tags': _self.tags,
    if (_self.limits.isNotEmpty) 'limits': _self.limits,
    if (_self.signature != 'team') 'signature': _self.signature,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Compose &&
          other.text == _self.text &&
          other.times == _self.times &&
          other.separator == _self.separator &&
          other.loud == _self.loud &&
          other.tone == _self.tone &&
          dwListEquals(other.tags, _self.tags) &&
          dwMapEquals(other.limits, _self.limits) &&
          other.signature == _self.signature;

  @override
  int get hashCode => Object.hash(
    Compose,
    _self.text,
    _self.times,
    _self.separator,
    _self.loud,
    _self.tone,
    Object.hashAll(_self.tags),
    Object.hashAllUnordered(
      _self.limits.entries.map((e) => Object.hash(e.key, e.value)),
    ),
    _self.signature,
  );
}

Compose $ComposeFromJson(Map<String, Object?> json) => Compose(
  text: json['text']! as String,
  times: json['times'] == null ? 2 : json['times']! as int,
  separator: json['separator'] == null ? ' ' : json['separator']! as String,
  loud: json['loud'] == null ? false : json['loud']! as bool,
  tone: json['tone'] == null
      ? Tone.plain
      : DwJsonCodec.decodeEnum(json['tone'], Tone.values),
  tags: json['tags'] == null
      ? const <String>['draft']
      : DwJsonCodec.decodeList(json['tags'], (e) => e! as String),
  limits: json['limits'] == null
      ? const {}
      : DwJsonCodec.decodeMap(json['limits'], (v) => v! as int),
  signature: json.containsKey('signature')
      ? (json['signature'] as String?)
      : 'team',
);

mixin _$Echoes on DwListRequest<Echo> {
  Echoes get _self => this as Echoes;

  @override
  String get dwTypeName => 'Echoes';

  @override
  Map<String, Object?> toJson() => {
    if (_self.count != 3) 'count': _self.count,
    if (_self.prefix != 'echo') 'prefix': _self.prefix,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Echoes &&
          other.count == _self.count &&
          other.prefix == _self.prefix;

  @override
  int get hashCode => Object.hash(Echoes, _self.count, _self.prefix);

  @override
  String toString() => 'Echoes(count: ${_self.count}, prefix: ${_self.prefix})';
}

Echoes $EchoesFromJson(Map<String, Object?> json) => Echoes(
  count: json['count'] == null ? 3 : json['count']! as int,
  prefix: json['prefix'] == null ? 'echo' : json['prefix']! as String,
);

mixin _$Echo on DwDataObject {
  Echo get _self => this as Echo;

  @override
  String get dwTypeName => 'Echo';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    if (_self.label != '') 'label': _self.label,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Echo && other.id == _self.id && other.label == _self.label;

  @override
  int get hashCode => Object.hash(_self.id, _self.label);

  @override
  String toString() => 'Echo(id: ${_self.id}, label: ${_self.label})';
}

Echo $EchoFromJson(Map<String, Object?> json) => Echo(
  id: json['id']! as int,
  label: json['label'] == null ? '' : json['label']! as String,
);

extension EchoCopyWith on Echo {
  Echo copyWith({int? id, String? label}) =>
      Echo(id: id ?? this.id, label: label ?? this.label);
}
