/// The header of every file the generator writes. Stale-file removal relies on
/// it: a `.dw.dart` without this first line is not ours and is never deleted.
const generatedHeader = '// GENERATED BY dartway generate. DO NOT EDIT.';

/// [value] as a single-quoted Dart string literal.
String dartString(String value) => "'${escapeInString(value)}'";

/// Escapes [value] for the inside of a single-quoted Dart string: identifiers
/// may contain `$`, which would otherwise start an interpolation.
String escapeInString(String value) => value
    .replaceAll(r'\', r'\\')
    .replaceAll("'", r"\'")
    .replaceAll(r'$', r'\$');

/// `dartway_example` → `dartwayExample`.
String camelCase(String snake) {
  final parts = snake.split('_').where((part) => part.isNotEmpty).toList();
  if (parts.isEmpty) return snake;
  return parts.first +
      parts
          .skip(1)
          .map((part) => part[0].toUpperCase() + part.substring(1))
          .join();
}

/// `dartway_example` → `DartwayExample`.
String pascalCase(String snake) {
  final camel = camelCase(snake);
  return camel.isEmpty ? camel : camel[0].toUpperCase() + camel.substring(1);
}
