name: project_name_client
description: Starting point for a Serverpod client.

environment:
  sdk: '^3.11.0'

dependencies:
  serverpod_client: 3.4.7

  dartway_serverpod_core_client:
    git:
      url: https://github.com/dartway/dartway.git
      path: packages/dartway_serverpod_core/dartway_serverpod_core_client
