// GENERATED BY dartway generate. DO NOT EDIT.
part of 'content_rows.dart';

mixin _$NewsPostRow on DwTableRow {
  NewsPostRow get _self => this as NewsPostRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewsPostRow &&
          other.id == _self.id &&
          other.authorProfileId == _self.authorProfileId &&
          other.title == _self.title &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.authorProfileId,
    _self.title,
    _self.text,
    _self.createdAt,
  );

  @override
  String toString() =>
      'NewsPostRow(id: ${_self.id}, authorProfileId: ${_self.authorProfileId}, title: ${_self.title}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

extension NewsPostRowCopyWith on NewsPostRow {
  NewsPostRow copyWith({
    int? authorProfileId,
    String? title,
    String? text,
    DateTime? createdAt,
  }) => NewsPostRow(
    id: id,
    authorProfileId: authorProfileId ?? this.authorProfileId,
    title: title ?? this.title,
    text: text ?? this.text,
    createdAt: createdAt ?? this.createdAt,
  );
}

mixin _$NewNewsPostRow on DwRowDraft<NewsPostRow> {
  NewNewsPostRow get _self => this as NewNewsPostRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewNewsPostRow &&
          other.authorProfileId == _self.authorProfileId &&
          other.title == _self.title &&
          other.text == _self.text &&
          other.createdAt == _self.createdAt;

  @override
  int get hashCode => Object.hash(
    _self.authorProfileId,
    _self.title,
    _self.text,
    _self.createdAt,
  );

  @override
  String toString() =>
      'NewNewsPostRow(authorProfileId: ${_self.authorProfileId}, title: ${_self.title}, text: ${_self.text}, createdAt: ${_self.createdAt})';
}

/// A [NewsPostRow] before insert: every column but the id.
final class NewNewsPostRow extends DwRowDraft<NewsPostRow>
    with _$NewNewsPostRow {
  const NewNewsPostRow({
    required this.authorProfileId,
    required this.title,
    required this.text,
    required this.createdAt,
  });

  final int authorProfileId;
  final String title;
  final String text;
  final DateTime createdAt;
}

extension NewNewsPostRowCopyWith on NewNewsPostRow {
  NewNewsPostRow copyWith({
    int? authorProfileId,
    String? title,
    String? text,
    DateTime? createdAt,
  }) => NewNewsPostRow(
    authorProfileId: authorProfileId ?? this.authorProfileId,
    title: title ?? this.title,
    text: text ?? this.text,
    createdAt: createdAt ?? this.createdAt,
  );
}

extension NewNewsPostRowWithId on NewNewsPostRow {
  /// The row stored under [id], for `update`.
  NewsPostRow withId(int id) => NewsPostRow(
    id: id,
    authorProfileId: authorProfileId,
    title: title,
    text: text,
    createdAt: createdAt,
  );
}

final class NewsPostTable extends DwTableDef<NewsPostRow> {
  const NewsPostTable() : super('news_post');

  DwTableColumn<int> get authorProfileId => const DwTableColumn(
    'author_profile_id',
    DwColumnType.bigint,
    references: DwForeignKey('user_profile', onDelete: DwOnDelete.cascade),
  );

  DwTableColumn<String> get title =>
      const DwTableColumn('title', DwColumnType.text);

  DwTableColumn<String> get text =>
      const DwTableColumn('text', DwColumnType.text);

  DwTableColumn<DateTime> get createdAt =>
      const DwTableColumn('created_at', DwColumnType.timestamptz);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [
    id,
    authorProfileId,
    title,
    text,
    createdAt,
  ];

  @override
  List<DwIndexSchema> get indexSchemas => [
    DwIndexSchema('news_post_created_at_idx', ['created_at']),
  ];

  @override
  NewsPostRow fromRow(DwResultRow row) => NewsPostRow(
    id: row.decode(id),
    authorProfileId: row.decode(authorProfileId),
    title: row.decode(title),
    text: row.decode(text),
    createdAt: row.decode(createdAt),
  );

  @override
  Map<String, Object?> toRow(NewsPostRow row) => {
    'author_profile_id': row.authorProfileId,
    'title': row.title,
    'text': row.text,
    'created_at': row.createdAt,
  };

  @override
  Map<String, Object?> toDraftRow(NewNewsPostRow draft) => {
    'author_profile_id': draft.authorProfileId,
    'title': draft.title,
    'text': draft.text,
    'created_at': draft.createdAt,
  };
}

mixin _$AppSettingRow on DwTableRow {
  AppSettingRow get _self => this as AppSettingRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettingRow &&
          other.id == _self.id &&
          other.key == _self.key &&
          other.value == _self.value;

  @override
  int get hashCode => Object.hash(_self.id, _self.key, _self.value);

  @override
  String toString() =>
      'AppSettingRow(id: ${_self.id}, key: ${_self.key}, value: ${_self.value})';
}

extension AppSettingRowCopyWith on AppSettingRow {
  AppSettingRow copyWith({String? key, String? value}) =>
      AppSettingRow(id: id, key: key ?? this.key, value: value ?? this.value);
}

mixin _$NewAppSettingRow on DwRowDraft<AppSettingRow> {
  NewAppSettingRow get _self => this as NewAppSettingRow;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewAppSettingRow &&
          other.key == _self.key &&
          other.value == _self.value;

  @override
  int get hashCode => Object.hash(_self.key, _self.value);

  @override
  String toString() =>
      'NewAppSettingRow(key: ${_self.key}, value: ${_self.value})';
}

/// A [AppSettingRow] before insert: every column but the id.
final class NewAppSettingRow extends DwRowDraft<AppSettingRow>
    with _$NewAppSettingRow {
  const NewAppSettingRow({required this.key, required this.value});

  final String key;
  final String value;
}

extension NewAppSettingRowCopyWith on NewAppSettingRow {
  NewAppSettingRow copyWith({String? key, String? value}) =>
      NewAppSettingRow(key: key ?? this.key, value: value ?? this.value);
}

extension NewAppSettingRowWithId on NewAppSettingRow {
  /// The row stored under [id], for `update`.
  AppSettingRow withId(int id) => AppSettingRow(id: id, key: key, value: value);
}

final class AppSettingTable extends DwTableDef<AppSettingRow> {
  const AppSettingTable() : super('app_setting');

  DwTableColumn<String> get key =>
      const DwTableColumn('key', DwColumnType.text, unique: true);

  DwTableColumn<String> get value =>
      const DwTableColumn('value', DwColumnType.text);

  @override
  List<DwTableColumn<Object?>> get tableColumns => [id, key, value];

  @override
  AppSettingRow fromRow(DwResultRow row) => AppSettingRow(
    id: row.decode(id),
    key: row.decode(key),
    value: row.decode(value),
  );

  @override
  Map<String, Object?> toRow(AppSettingRow row) => {
    'key': row.key,
    'value': row.value,
  };

  @override
  Map<String, Object?> toDraftRow(NewAppSettingRow draft) => {
    'key': draft.key,
    'value': draft.value,
  };
}
