import 'dart:io';

import 'package:path/path.dart' as p;

import 'dw_check_tally.dart';
import 'dw_check_type.dart';
import 'dw_dart_outline.dart';
import 'dw_layout.dart';

/// The project-named files at the top of a shared package's `lib/src/`:
/// `<prefix>_<role>.dart`, the prefix the package's name without `_shared`
/// (`acme_shared` → `acme_channel.dart`). Each is the project's answer to one
/// of the framework's package-wide roles — the channels, the refusal codes,
/// the upload purposes, the protocol the two sides speak, the push
/// categories — the shared half of what the server keeps in `core/`.
const dwSharedPackageRoles = [
  'channel',
  'refusal',
  'upload',
  'protocol',
  'push_category',
];

/// The top level of a shared package's `lib/`: the library a package is named
/// for, what the generator writes, and everything else under `src/`.
const dwSharedLibFolders = {'generated', 'src'};

/// The prefix of a shared package's project-named files: its name without
/// `_shared`.
String dwSharedPrefix(String packageName) => packageName.endsWith('_shared')
    ? packageName.substring(0, packageName.length - '_shared'.length)
    : packageName;

/// The suffixes of generated Dart files: the framework's parts and
/// `build_runner`'s. A file so named is generated only when it also carries a
/// generated header ([dwHasGeneratedHeader]); without one it is hand-written
/// code under a name every check passes over.
const dwGeneratedSuffixes = ['.dw.dart', '.g.dart', '.freezed.dart'];

/// Whether [fileName] carries a generated file's suffix.
bool dwIsGeneratedName(String fileName) =>
    dwGeneratedSuffixes.any(fileName.endsWith);

/// Whether [source] opens with a generator's header — `// GENERATED BY
/// dartway generate`, `build_runner`'s `// GENERATED CODE` — within its
/// first lines (`freezed` puts two comments above it).
bool dwHasGeneratedHeader(String source) =>
    source.split('\n').take(5).any((line) => line.startsWith('// GENERATED'));

/// Whether [fileName] is `<feature>_<part>.dart`, the only name inside a
/// shared feature folder `src/<feature>/`: a feature is one file or a folder
/// of parts, never a folder with a file of the feature's own name in it,
/// which is where everything without a part would collect. A part is never
/// exactly a layer's name (`chat_models.dart`); a layer word inside a longer
/// part is a topic (`content_news_publications.dart`).
bool dwIsSharedFeatureFile(String feature, String fileName) {
  final match = RegExp(
    '^${RegExp.escape(feature)}_([a-z][a-z0-9_]*)\\.dart\$',
  ).firstMatch(fileName);
  if (match == null) return false;
  return !dwServerForbiddenFolders.contains(match.group(1));
}

/// Whether [word], the first segment of a file name, names [feature]: the
/// same word, its singular or plural (`issue`, `courses`), or a prefix of four
/// letters or more either way (`notif` → `notifications`).
bool dwNamesFeature(String word, String feature) {
  if (word.isEmpty) return false;
  if (word == feature ||
      '${word}s' == feature ||
      '${feature}s' == word ||
      '${word}es' == feature ||
      '${feature}es' == word) {
    return true;
  }
  return (feature.startsWith(word) && word.length >= 4) ||
      (word.startsWith(feature) && feature.length >= 4);
}

/// The shared package mirrors the server's features
/// ([DwCheckType.invalidSharedLayout], dartway/dartway#383).
///
/// `lib/src/` holds `<feature>.dart` or a folder `<feature>/` of
/// `<feature>_<part>.dart` files, `<feature>` the name of a feature folder of
/// the server's `lib/src/`, and the project-named files of
/// [dwSharedPackageRoles] — nothing else. What exists only in the contract
/// goes with the feature that owns it: there is no shared `core/`. `lib/`
/// itself holds the package's library — directives only — `generated/`, all
/// of it the generator's, and `src/`.
///
/// Every project had grown its own shared layout — flat area files beside
/// folders named after nothing on the server, a data object of one feature
/// kept in another's file, a 2400-line file of 76 types — so "where is the
/// contract of this feature" had as many answers as projects. With the server
/// as the list, it has one, and the checker reads both packages to hold it.
class DwSharedLayoutInspector {
  DwSharedLayoutInspector({
    required this.sharedPackageDir,
    this.serverPackageDir,
    DwCheckType? filterType,
    DwCheckSeverity? filterSeverity,
  }) : _enabled =
           (filterType == null ||
               filterType == DwCheckType.invalidSharedLayout) &&
           (filterSeverity == null ||
               filterSeverity == DwCheckType.invalidSharedLayout.severity);

  final Directory? sharedPackageDir;

  /// Where the feature names are read; without it, names are not matched.
  final Directory? serverPackageDir;

  final bool _enabled;
  final _findings = <String>[];

  /// The findings, in the order they were made.
  List<String> get findings => List.unmodifiable(_findings);

  int run({DwCheckTally? tally}) {
    final shared = sharedPackageDir;
    if (!_enabled || shared == null) return 0;
    final lib = Directory(p.join(shared.path, 'lib'));
    if (!lib.existsSync()) return 0;

    final packageName = _packageNameOf(shared);
    final label = '${p.basename(shared.path)}/lib';
    _checkLib(lib, label, packageName);

    final src = Directory(p.join(lib.path, 'src'));
    final features = _serverFeatures();
    if (src.existsSync()) {
      _checkSrc(src, '$label/src', dwSharedPrefix(packageName), features);
    }

    // Said rather than passed over: without the server, a shared file named
    // after nothing would pass, and a clean run would claim otherwise.
    if (features == null) {
      print(
        '\n  ℹ️ INFO: shared file names not matched to server features: '
        'no server package found',
      );
    }
    if (_findings.isEmpty) return 0;
    print('\n🧩 Shared package layout:\n');
    for (final finding in _findings) {
      print('  ${DwCheckType.invalidSharedLayout.reportLabel}: $finding');
    }
    tally?.add(DwCheckType.invalidSharedLayout, _findings.length);
    return _findings.length;
  }

  /// The server's feature folders, or null without a server package.
  List<String>? _serverFeatures() {
    final server = serverPackageDir;
    if (server == null) return null;
    final src = Directory(p.join(server.path, 'lib', 'src'));
    if (!src.existsSync()) return null;
    return [
      for (final entity in src.listSync())
        if (entity is Directory)
          if (p.basename(entity.path) case final name
              when !name.startsWith('.') &&
                  !dwServerSrcLayers.contains(name) &&
                  !dwServerForbiddenFolders.contains(name) &&
                  RegExp(r'^[a-z][a-z0-9_]*$').hasMatch(name))
            name,
    ]..sort();
  }

  void _checkLib(Directory lib, String label, String packageName) {
    final library = '$packageName.dart';
    var hasLibrary = false;
    for (final entity in _sorted(lib)) {
      final name = p.basename(entity.path);
      if (name.startsWith('.')) continue;
      if (entity is File && name == library) {
        hasLibrary = true;
        _checkLibraryFile(entity, '$label/$name');
        continue;
      }
      if (entity is Directory && dwSharedLibFolders.contains(name)) {
        if (name == 'generated') _checkGenerated(entity, '$label/$name');
        continue;
      }
      _findings.add(
        '$label/$name is not part of the declared layout — the package '
        'exposes $library, the generator writes generated/, and the rest '
        'lives in src/',
      );
    }
    if (!hasLibrary && packageName.isNotEmpty) {
      _findings.add('$label/$library is missing — it is a fixed name');
    }
  }

  /// The library holds directives only: a declaration there is contract code
  /// outside every feature, the file the layout exists to rule out.
  void _checkLibraryFile(File file, String label) {
    final outline = DwDartOutline(file.readAsStringSync());
    // Blanked in place, so an offset left over is still the source's line.
    final rest = outline.code.replaceAllMapped(
      RegExp(r'\b(?:library|import|export)\b[^;]*;'),
      (m) => m[0]!.replaceAll(RegExp(r'[^\n]'), ' '),
    );
    final match = RegExp(r'\S').firstMatch(rest);
    if (match == null) return;
    _findings.add(
      '$label:${outline.lineOf(match.start)} declares code — the library '
      'holds library, import and export directives only; what it declares '
      'goes to the feature that owns it in src/',
    );
  }

  /// Everything in `generated/` is the generator's.
  void _checkGenerated(Directory dir, String label) {
    final files = dir.listSync(recursive: true).whereType<File>().toList()
      ..sort((a, b) => a.path.compareTo(b.path));
    for (final file in files) {
      final rel = p.relative(file.path, from: dir.path).replaceAll(r'\', '/');
      if (rel.split('/').any((s) => s.startsWith('.'))) continue;
      if (dwHasGeneratedHeader(file.readAsStringSync())) continue;
      _findings.add(
        '$label/$rel is hand-written — generated/ holds only what '
        '`dartway generate` writes; move it to the feature that owns it in src/',
      );
    }
  }

  /// A file named as generated that carries no generated header.
  bool _handWrittenGenerated(File file, String label) {
    if (dwHasGeneratedHeader(file.readAsStringSync())) return false;
    _findings.add(
      '$label has a generated file\'s name and no generated header — '
      'hand-written code no check reads; give it the name of what it is',
    );
    return true;
  }

  void _checkSrc(
    Directory src,
    String label,
    String prefix,
    List<String>? features,
  ) {
    final roleFiles = {
      for (final role in dwSharedPackageRoles) '${prefix}_$role.dart',
    };
    final entries = _sorted(src);
    final folders = {
      for (final entity in entries)
        if (entity is Directory) p.basename(entity.path),
    };
    bool isFeature(String name) =>
        features?.contains(name) ?? RegExp(r'^[a-z][a-z0-9_]*$').hasMatch(name);
    final featureList = features == null
        ? '<feature>'
        : features.isEmpty
        ? 'the server declares none'
        : 'the server\'s: ${features.join(', ')}';

    for (final entity in entries) {
      final name = p.basename(entity.path);
      if (name.startsWith('.')) continue;
      if (entity is Directory) {
        if (isFeature(name)) {
          _checkFeatureFolder(entity, name, '$label/$name');
        } else {
          _findings.add(
            '$label/$name/ is not a feature of the server ($featureList) — '
            '${_fixFor(name, features, prefix)}',
          );
        }
        continue;
      }
      // A generated part is named after its source, and moves with it.
      if (dwIsGeneratedName(name)) {
        _handWrittenGenerated(entity as File, '$label/$name');
        continue;
      }
      if (roleFiles.contains(name)) continue;
      if (!name.endsWith('.dart')) {
        _findings.add(
          '$label/$name — src/ holds Dart files only; move it out of lib/',
        );
        continue;
      }
      final stem = name.substring(0, name.length - '.dart'.length);
      if (isFeature(stem)) {
        if (folders.contains(stem)) {
          _findings.add(
            '$label/$name beside $label/$stem/ — a feature is one file or '
            'one folder of parts: split it into $label/$stem/${stem}_<part>.dart '
            'files',
          );
        }
        continue;
      }
      _findings.add(
        '$label/$name is neither a feature of the server ($featureList) nor '
        'one of ${roleFiles.join(', ')} — ${_fixFor(stem, features, prefix)}',
      );
    }
  }

  void _checkFeatureFolder(Directory dir, String feature, String label) {
    for (final entity in _sorted(dir)) {
      final name = p.basename(entity.path);
      if (name.startsWith('.')) continue;
      if (entity is Directory) {
        _findings.add(
          '$label/$name/ — a shared feature folder is flat; its files are '
          '${feature}_<part>.dart',
        );
        continue;
      }
      if (dwIsGeneratedName(name)) {
        _handWrittenGenerated(entity as File, '$label/$name');
        continue;
      }
      if (dwIsSharedFeatureFile(feature, name)) continue;
      if (name == '$feature.dart') {
        _findings.add(
          '$label/$name — a feature folder holds parts only, '
          '${feature}_<part>.dart, each named for the DTOs it holds; a file of '
          'the feature\'s own name is where everything without a part collects',
        );
        continue;
      }
      final stem = name.endsWith('.dart')
          ? name.substring(0, name.length - '.dart'.length)
          : name;
      final topic = _topic(stem, feature);
      _findings.add(
        '$label/$name — not ${feature}_<part>.dart (a part is what the file '
        'is about, never exactly a layer: '
        '${(dwServerForbiddenFolders.toList()..sort()).join(', ')})'
        '${_usableTopic(topic) ? ': rename it to ${feature}_$topic.dart' : ''}',
      );
    }
  }

  static bool _usableTopic(String topic) =>
      topic.isNotEmpty && !dwServerForbiddenFolders.contains(topic);

  /// Where a shared file or folder named [stem] that is no feature goes.
  String _fixFor(String stem, List<String>? features, String prefix) {
    for (final role in dwSharedPackageRoles) {
      if (stem == role ||
          stem == '${role}s' ||
          stem.endsWith('_$role') ||
          stem.endsWith('_${role}s')) {
        return 'rename it to ${prefix}_$role.dart';
      }
    }
    if (stem.startsWith('${prefix}_')) {
      return 'the project-named files are '
          '${dwSharedPackageRoles.map((r) => '${prefix}_$r.dart').join(', ')}; '
          'anything else goes with the feature that owns it';
    }
    final owner = _nearestFeature(stem, features);
    if (owner != null) {
      final topic = _topic(stem, owner);
      if (topic.isEmpty) return 'rename it to src/$owner.dart';
      final part = _usableTopic(topic) ? topic : '<part>';
      return 'it belongs to $owner: merge it into src/$owner.dart, or make '
          'src/$owner/ a folder of parts with this one as '
          'src/$owner/${owner}_$part.dart';
    }
    return 'move what it declares to the feature that owns it — '
        'src/<feature>.dart, or src/<feature>/<feature>_<part>.dart';
  }

  /// The feature whose name [stem] starts with, or names by its first word
  /// ([dwNamesFeature]: `issue_process` for `issues`, `course` for `courses`).
  static String? _nearestFeature(String stem, List<String>? features) {
    if (features == null) return null;
    for (final feature in features) {
      if (stem.startsWith('${feature}_')) return feature;
    }
    final first = stem.split('_').first;
    for (final feature in features) {
      if (dwNamesFeature(first, feature)) return feature;
    }
    return null;
  }

  /// What [stem] is about without [feature]'s name or a near miss of it.
  static String _topic(String stem, String feature) {
    if (stem == feature) return '';
    if (stem.startsWith('${feature}_')) {
      return stem.substring(feature.length + 1);
    }
    final segments = stem.split('_');
    if (dwNamesFeature(segments.first, feature)) {
      return segments.sublist(1).join('_');
    }
    return stem;
  }

  static String _packageNameOf(Directory packageDir) {
    final pubspec = File(p.join(packageDir.path, 'pubspec.yaml'));
    if (pubspec.existsSync()) {
      final match = RegExp(
        r'^name:\s*(\S+)',
        multiLine: true,
      ).firstMatch(pubspec.readAsStringSync());
      if (match != null) return match.group(1)!;
    }
    return p.basename(packageDir.path);
  }

  static List<FileSystemEntity> _sorted(Directory dir) =>
      dir.listSync()..sort((a, b) => a.path.compareTo(b.path));
}
