// GENERATED BY dartway generate. DO NOT EDIT.
part of 'admin.dart';

mixin _$AdminCounters on DwDataObject {
  AdminCounters get _self => this as AdminCounters;

  @override
  String get dwTypeName => 'AdminCounters';

  @override
  Map<String, Object?> toJson() => {
    'members': _self.members,
    'admins': _self.admins,
    'marketingOptIns': _self.marketingOptIns,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdminCounters &&
          other.members == _self.members &&
          other.admins == _self.admins &&
          other.marketingOptIns == _self.marketingOptIns;

  @override
  int get hashCode =>
      Object.hash(_self.members, _self.admins, _self.marketingOptIns);

  @override
  String toString() =>
      'AdminCounters(members: ${_self.members}, admins: ${_self.admins}, marketingOptIns: ${_self.marketingOptIns})';
}

AdminCounters $AdminCountersFromJson(Map<String, Object?> json) =>
    AdminCounters(
      members: json['members']! as int,
      admins: json['admins']! as int,
      marketingOptIns: json['marketingOptIns']! as int,
    );

extension AdminCountersCopyWith on AdminCounters {
  AdminCounters copyWith({int? members, int? admins, int? marketingOptIns}) =>
      AdminCounters(
        members: members ?? this.members,
        admins: admins ?? this.admins,
        marketingOptIns: marketingOptIns ?? this.marketingOptIns,
      );
}

mixin _$GetAdminCounters on DwSingleRequest<AdminCounters> {
  @override
  String get dwTypeName => 'GetAdminCounters';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is GetAdminCounters;

  @override
  int get hashCode => (GetAdminCounters).hashCode;

  @override
  String toString() => 'GetAdminCounters()';
}

GetAdminCounters $GetAdminCountersFromJson(Map<String, Object?> json) =>
    const GetAdminCounters();

mixin _$ListUserProfiles on DwTableRequest<UserProfile> {
  ListUserProfiles get _self => this as ListUserProfiles;

  @override
  String get dwTypeName => 'ListUserProfiles';

  @override
  Map<String, Object?> toJson() => {
    if (_self.page != 1) 'page': _self.page,
    if (_self.pageSize != 10) 'pageSize': _self.pageSize,
    if (_self.search != '') 'search': _self.search,
    if (_self.role != null) 'role': _self.role!.name,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListUserProfiles &&
          other.page == _self.page &&
          other.pageSize == _self.pageSize &&
          other.search == _self.search &&
          other.role == _self.role;

  @override
  int get hashCode => Object.hash(
    ListUserProfiles,
    _self.page,
    _self.pageSize,
    _self.search,
    _self.role,
  );

  @override
  String toString() =>
      'ListUserProfiles(page: ${_self.page}, pageSize: ${_self.pageSize}, search: ${_self.search}, role: ${_self.role})';
}

ListUserProfiles $ListUserProfilesFromJson(Map<String, Object?> json) =>
    ListUserProfiles(
      page: json['page'] == null ? 1 : json['page']! as int,
      pageSize: json['pageSize'] == null ? 10 : json['pageSize']! as int,
      search: json['search'] == null ? '' : json['search']! as String,
      role: json['role'] == null
          ? null
          : DwJsonCodec.decodeEnum(json['role'], UserRole.values),
    );

mixin _$UserIdentifier on DwDataObject {
  UserIdentifier get _self => this as UserIdentifier;

  @override
  String get dwTypeName => 'UserIdentifier';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'kind': _self.kind.name,
    'value': _self.value,
    'addedAt': DwJsonCodec.encodeDateTime(_self.addedAt),
    if (_self.verifiedAt != null)
      'verifiedAt': DwJsonCodec.encodeDateTime(_self.verifiedAt!),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserIdentifier &&
          other.id == _self.id &&
          other.kind == _self.kind &&
          other.value == _self.value &&
          other.addedAt == _self.addedAt &&
          other.verifiedAt == _self.verifiedAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.kind,
    _self.value,
    _self.addedAt,
    _self.verifiedAt,
  );

  @override
  String toString() =>
      'UserIdentifier(id: ${_self.id}, kind: ${_self.kind}, value: ${_self.value}, addedAt: ${_self.addedAt}, verifiedAt: ${_self.verifiedAt})';
}

UserIdentifier $UserIdentifierFromJson(Map<String, Object?> json) =>
    UserIdentifier(
      id: json['id']! as int,
      kind: DwJsonCodec.decodeEnum(json['kind'], DwIdentifierKind.values),
      value: json['value']! as String,
      addedAt: DwJsonCodec.decodeDateTime(json['addedAt']),
      verifiedAt: json['verifiedAt'] == null
          ? null
          : DwJsonCodec.decodeDateTime(json['verifiedAt']),
    );

extension UserIdentifierCopyWith on UserIdentifier {
  UserIdentifier copyWith({
    int? id,
    DwIdentifierKind? kind,
    String? value,
    DateTime? addedAt,
    DwFieldPatch<DateTime> verifiedAt = const DwFieldPatch.keep(),
  }) => UserIdentifier(
    id: id ?? this.id,
    kind: kind ?? this.kind,
    value: value ?? this.value,
    addedAt: addedAt ?? this.addedAt,
    verifiedAt: verifiedAt.apply(this.verifiedAt),
  );
}

mixin _$UserCard on DwDataObject {
  UserCard get _self => this as UserCard;

  @override
  String get dwTypeName => 'UserCard';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'profile': _self.profile.toJson(),
    if (_self.identifiers.isNotEmpty)
      'identifiers': [for (final e in _self.identifiers) e.toJson()],
    if (_self.termsAcceptedAt != null)
      'termsAcceptedAt': DwJsonCodec.encodeDateTime(_self.termsAcceptedAt!),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserCard &&
          other.id == _self.id &&
          other.profile == _self.profile &&
          dwListEquals(other.identifiers, _self.identifiers) &&
          other.termsAcceptedAt == _self.termsAcceptedAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.profile,
    Object.hashAll(_self.identifiers),
    _self.termsAcceptedAt,
  );

  @override
  String toString() =>
      'UserCard(id: ${_self.id}, profile: ${_self.profile}, identifiers: ${_self.identifiers}, termsAcceptedAt: ${_self.termsAcceptedAt})';
}

UserCard $UserCardFromJson(Map<String, Object?> json) => UserCard(
  id: json['id']! as int,
  profile: $UserProfileFromJson(json['profile']! as Map<String, Object?>),
  identifiers: json['identifiers'] == null
      ? const []
      : DwJsonCodec.decodeList(
          json['identifiers'],
          (e) => $UserIdentifierFromJson(e! as Map<String, Object?>),
        ),
  termsAcceptedAt: json['termsAcceptedAt'] == null
      ? null
      : DwJsonCodec.decodeDateTime(json['termsAcceptedAt']),
);

extension UserCardCopyWith on UserCard {
  UserCard copyWith({
    int? id,
    UserProfile? profile,
    List<UserIdentifier>? identifiers,
    DwFieldPatch<DateTime> termsAcceptedAt = const DwFieldPatch.keep(),
  }) => UserCard(
    id: id ?? this.id,
    profile: profile ?? this.profile,
    identifiers: identifiers ?? this.identifiers,
    termsAcceptedAt: termsAcceptedAt.apply(this.termsAcceptedAt),
  );
}

mixin _$GetUserCard on DwSingleRequest<UserCard> {
  GetUserCard get _self => this as GetUserCard;

  @override
  String get dwTypeName => 'GetUserCard';

  @override
  Map<String, Object?> toJson() => {'profileId': _self.profileId};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GetUserCard && other.profileId == _self.profileId;

  @override
  int get hashCode => Object.hash(GetUserCard, _self.profileId);

  @override
  String toString() => 'GetUserCard(profileId: ${_self.profileId})';
}

GetUserCard $GetUserCardFromJson(Map<String, Object?> json) =>
    GetUserCard(profileId: json['profileId']! as int);

mixin _$ChangeUserRole on DwActionCommand<UserProfile> {
  ChangeUserRole get _self => this as ChangeUserRole;

  @override
  String get dwTypeName => 'ChangeUserRole';

  @override
  Map<String, Object?> toJson() => {
    'profileId': _self.profileId,
    'role': _self.role.name,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangeUserRole &&
          other.profileId == _self.profileId &&
          other.role == _self.role;

  @override
  int get hashCode => Object.hash(ChangeUserRole, _self.profileId, _self.role);
}

ChangeUserRole $ChangeUserRoleFromJson(Map<String, Object?> json) =>
    ChangeUserRole(
      profileId: json['profileId']! as int,
      role: DwJsonCodec.decodeEnum(json['role'], UserRole.values),
    );
