// GENERATED BY dartway generate. DO NOT EDIT.
part of 'profile.dart';

mixin _$UserProfile on DwDataObject {
  UserProfile get _self => this as UserProfile;

  @override
  String get dwTypeName => 'UserProfile';

  @override
  Map<String, Object?> toJson() => {
    'id': _self.id,
    'accountId': _self.accountId,
    'firstName': _self.firstName,
    if (_self.lastName != null) 'lastName': _self.lastName,
    if (_self.gender != null) 'gender': _self.gender!.name,
    if (_self.avatarUrl != null) 'avatarUrl': _self.avatarUrl,
    if (_self.phone != null) 'phone': _self.phone,
    if (_self.email != null) 'email': _self.email,
    'role': _self.role.name,
    if (_self.agreedForMarketing)
      'agreedForMarketing': _self.agreedForMarketing,
    'joinedAt': DwJsonCodec.encodeDateTime(_self.joinedAt),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          other.id == _self.id &&
          other.accountId == _self.accountId &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.gender == _self.gender &&
          other.avatarUrl == _self.avatarUrl &&
          other.phone == _self.phone &&
          other.email == _self.email &&
          other.role == _self.role &&
          other.agreedForMarketing == _self.agreedForMarketing &&
          other.joinedAt == _self.joinedAt;

  @override
  int get hashCode => Object.hash(
    _self.id,
    _self.accountId,
    _self.firstName,
    _self.lastName,
    _self.gender,
    _self.avatarUrl,
    _self.phone,
    _self.email,
    _self.role,
    _self.agreedForMarketing,
    _self.joinedAt,
  );

  @override
  String toString() =>
      'UserProfile(id: ${_self.id}, accountId: ${_self.accountId}, firstName: ${_self.firstName}, lastName: ${_self.lastName}, gender: ${_self.gender}, avatarUrl: ${_self.avatarUrl}, phone: ${_self.phone}, email: ${_self.email}, role: ${_self.role}, agreedForMarketing: ${_self.agreedForMarketing}, joinedAt: ${_self.joinedAt})';
}

UserProfile $UserProfileFromJson(Map<String, Object?> json) => UserProfile(
  id: json['id']! as int,
  accountId: json['accountId']! as int,
  firstName: json['firstName']! as String,
  lastName: json['lastName'] as String?,
  gender: json['gender'] == null
      ? null
      : DwJsonCodec.decodeEnum(json['gender'], UserGender.values),
  avatarUrl: json['avatarUrl'] as String?,
  phone: json['phone'] as String?,
  email: json['email'] as String?,
  role: DwJsonCodec.decodeEnum(json['role'], UserRole.values),
  agreedForMarketing: json['agreedForMarketing'] == null
      ? false
      : json['agreedForMarketing']! as bool,
  joinedAt: DwJsonCodec.decodeDateTime(json['joinedAt']),
);

extension UserProfileCopyWith on UserProfile {
  UserProfile copyWith({
    int? id,
    int? accountId,
    String? firstName,
    DwFieldPatch<String> lastName = const DwFieldPatch.keep(),
    DwFieldPatch<UserGender> gender = const DwFieldPatch.keep(),
    DwFieldPatch<String> avatarUrl = const DwFieldPatch.keep(),
    DwFieldPatch<String> phone = const DwFieldPatch.keep(),
    DwFieldPatch<String> email = const DwFieldPatch.keep(),
    UserRole? role,
    bool? agreedForMarketing,
    DateTime? joinedAt,
  }) => UserProfile(
    id: id ?? this.id,
    accountId: accountId ?? this.accountId,
    firstName: firstName ?? this.firstName,
    lastName: lastName.apply(this.lastName),
    gender: gender.apply(this.gender),
    avatarUrl: avatarUrl.apply(this.avatarUrl),
    phone: phone.apply(this.phone),
    email: email.apply(this.email),
    role: role ?? this.role,
    agreedForMarketing: agreedForMarketing ?? this.agreedForMarketing,
    joinedAt: joinedAt ?? this.joinedAt,
  );
}

mixin _$GetMyProfile on DwSingleRequest<UserProfile> {
  @override
  String get dwTypeName => 'GetMyProfile';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is GetMyProfile;

  @override
  int get hashCode => (GetMyProfile).hashCode;

  @override
  String toString() => 'GetMyProfile()';
}

GetMyProfile $GetMyProfileFromJson(Map<String, Object?> json) =>
    const GetMyProfile();

mixin _$UpdateMyProfile on DwActionCommand<UserProfile> {
  UpdateMyProfile get _self => this as UpdateMyProfile;

  @override
  String get dwTypeName => 'UpdateMyProfile';

  @override
  Map<String, Object?> toJson() {
    final json = <String, Object?>{
      if (_self.firstName != null) 'firstName': _self.firstName,
    };
    DwJsonCodec.writePatch(json, 'lastName', _self.lastName, (v) => v);
    DwJsonCodec.writePatch(json, 'gender', _self.gender, (v) => v.name);
    DwJsonCodec.writePatch(json, 'avatarFileId', _self.avatarFileId, (v) => v);
    return json;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateMyProfile &&
          other.firstName == _self.firstName &&
          other.lastName == _self.lastName &&
          other.gender == _self.gender &&
          other.avatarFileId == _self.avatarFileId;

  @override
  int get hashCode => Object.hash(
    UpdateMyProfile,
    _self.firstName,
    _self.lastName,
    _self.gender,
    _self.avatarFileId,
  );
}

UpdateMyProfile $UpdateMyProfileFromJson(Map<String, Object?> json) =>
    UpdateMyProfile(
      firstName: json['firstName'] as String?,
      lastName: DwJsonCodec.readPatch(json, 'lastName', (v) => v! as String),
      gender: DwJsonCodec.readPatch(
        json,
        'gender',
        (v) => DwJsonCodec.decodeEnum(v, UserGender.values),
      ),
      avatarFileId: DwJsonCodec.readPatch(
        json,
        'avatarFileId',
        (v) => v! as int,
      ),
    );
