// GENERATED BY dartway generate. DO NOT EDIT.
part of 'settings.dart';

mixin _$AppSettings on DwDataObject {
  AppSettings get _self => this as AppSettings;

  @override
  String get dwTypeName => 'AppSettings';

  @override
  Map<String, Object?> toJson() => {
    if (_self.appName != 'DartwayStarter') 'appName': _self.appName,
    if (!_self.signUpEnabled) 'signUpEnabled': _self.signUpEnabled,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          other.appName == _self.appName &&
          other.signUpEnabled == _self.signUpEnabled;

  @override
  int get hashCode => Object.hash(_self.appName, _self.signUpEnabled);

  @override
  String toString() =>
      'AppSettings(appName: ${_self.appName}, signUpEnabled: ${_self.signUpEnabled})';
}

AppSettings $AppSettingsFromJson(Map<String, Object?> json) => AppSettings(
  appName: json['appName'] == null
      ? 'DartwayStarter'
      : json['appName']! as String,
  signUpEnabled: json['signUpEnabled'] == null
      ? true
      : json['signUpEnabled']! as bool,
);

extension AppSettingsCopyWith on AppSettings {
  AppSettings copyWith({String? appName, bool? signUpEnabled}) => AppSettings(
    appName: appName ?? this.appName,
    signUpEnabled: signUpEnabled ?? this.signUpEnabled,
  );
}

mixin _$GetAppSettings on DwSingleRequest<AppSettings> {
  @override
  String get dwTypeName => 'GetAppSettings';

  @override
  Map<String, Object?> toJson() => const {};

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is GetAppSettings;

  @override
  int get hashCode => (GetAppSettings).hashCode;

  @override
  String toString() => 'GetAppSettings()';
}

GetAppSettings $GetAppSettingsFromJson(Map<String, Object?> json) =>
    const GetAppSettings();

mixin _$SaveAppSettings on DwActionCommand<AppSettings> {
  SaveAppSettings get _self => this as SaveAppSettings;

  @override
  String get dwTypeName => 'SaveAppSettings';

  @override
  Map<String, Object?> toJson() => {
    if (_self.appName != null) 'appName': _self.appName,
    if (_self.signUpEnabled != null) 'signUpEnabled': _self.signUpEnabled,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SaveAppSettings &&
          other.appName == _self.appName &&
          other.signUpEnabled == _self.signUpEnabled;

  @override
  int get hashCode =>
      Object.hash(SaveAppSettings, _self.appName, _self.signUpEnabled);
}

SaveAppSettings $SaveAppSettingsFromJson(Map<String, Object?> json) =>
    SaveAppSettings(
      appName: json['appName'] as String?,
      signUpEnabled: json['signUpEnabled'] as bool?,
    );
